### ISSUE TITLE
Add labels, helper text, error markers and icons to form fields

### ISSUE THREAD

**Issue by vegegoku** [DominoKit/domino-ui#11]
- [x] add labels to form fields
- [x] add error markers to form fields
- [x] add helper text to form fields
- [x] add icons on left side and right side of the form field

**Comment by schube** [comment]
+1

**Comment by rjeeb** [comment]
Now every form element can have the following elements:

- Helper texts: which convey additional guidance about the input field, such as how it will be used
- Error markers: which display instructions on how to fix the unaccepted input
- Label: label for the field

In addition to that, `ValueBox` elements ( `TextBox`, `TextArea`, `DateBox` ) can have the following elements:

- Word counter: which shows the length of the input
- Addons ( left addon, right addon ) : which provide the user with the ability to add left and right element 
to the value box element.
