### ISSUE TITLE
Implement FlexLayout.

### ISSUE THREAD

**Issue by rjeeb** [DominoKit/domino-ui#116]

**Comment by rjeeb** [comment]
Demo page can be found:
https://dominokit.github.io/domino-ui-demo/index.html?theme=indigo#flex-layout

**Comment by masterdany88** [comment]
![screenshot_2018-09-20-16-12-15](https://user-images.githubusercontent.com/1161910/45824612-b33b9700-bcf0-11e8-8c50-23e296dbe1ae.png)
When I've added fews blocs they did not fit screen.
