### ISSUE TITLE
Tag field enhancement (open the select list on focus, navigate the list with arrows)

### ISSUE THREAD

**Issue by markposterone** [DominoKit/domino-ui#118]
When tag with select "has focus" (the list is open) arrow up and down should change the selection and then enter would close the list and make a new tag. When one selects something and there is a new placeholder for new tag "Friends name" this should have focus (open the list) automatically if there are any value in the list to select. If not, it should probably navigate away to a next field. Currently if I want to select few values, I need to click on placeholder, list is open, click again to select, click again on placeholder, ... otherwise: on focus list is open, arrow down, enter - new tag, new list opened arrow-down enter new tag. Off course I am talking about desktop use, for mobile, you have to tap anyway. If the list is open, Tab key should close it when navigating to a new field. Esc key should simply close the list and stay there.

**Comment by rjeeb** [comment]
Now the tag input field has keyboard navigation. Also,in order to delete already selected values, we've provided a shortcut for that `ctrl+backspace`, this will delete the last selected value.
