### ISSUE TITLE
Bug with drag and drop and accepted files types

### ISSUE THREAD

**Issue by RaulPampliegaMayoral** [DominoKit/domino-ui#134]
When trying to upload a file using drag and drop, you can choose any file type. Use of accept atributte on FileUpload has no effect.

**Comment by vegegoku** [comment]
For this to really works correctly one should read the file and parse the magic numbers for the known files formats.

the accept attribute only works for the select file dialog as it is a hint to the OS when opens the dialog, which is not the case for the drag and drop.

**Comment by RaulPampliegaMayoral** [comment]
I can manage this with the onAddFile event rejecting the file if not meets the requierements, so i think it can be closed
