### ISSUE TITLE
Problem using addBeforeUploadHandler with FileUpload

### ISSUE THREAD

**Issue by RaulPampliegaMayoral** [DominoKit/domino-ui#135]
The add handler is called after the uploading, it should be called before the uploading.

**Comment by vegegoku** [comment]
@RaulPampliegaMayoral now you can do something like even when the auto upload is enabled 
```java
fileUpload
...
.onAddFile(fileItem -> {
                    if(fileItem.getFile().name.equals("test1.txt")){
                        fileItem.cancel();
                    }
});
```

and this should for example prevent adding the file and it wont be uploaded.

i will not close this bug until you confirm it as resolved.

**Comment by vegegoku** [comment]
@RaulPampliegaMayoral can you confirm if this is fixed for you?

**Comment by RaulPampliegaMayoral** [comment]
@vegegoku i'm out till wenesd
