### ISSUE TITLE
Badge problem with mobile view

### ISSUE THREAD

**Issue by RaulPampliegaMayoral** [DominoKit/domino-ui#136]
When you have lot of text the list with badge is not viewing well:

![2018-10-23 17_19_48-ui-demo](https://user-images.githubusercontent.com/13700946/47371574-5dd81880-d6e8-11e8-8494-3738cc0ed0e8.png)

**Comment by vegegoku** [comment]
Thank you fir reporting, we will provide a fix as soon as possible

**Comment by RaulPampliegaMayoral** [comment]
i think that just positioning the span badge  as the first child it'd be enough:

![imagen](https://user-images.githubusercontent.com/13700946/47373793-d2ad5180-d6ec-11e8-9736-69e8d75766cd.png)

What do you think?

**Comment by vegegoku** [comment]
Yah that might work but will need to make the default way to add a badge.

**Comment by vegegoku** [comment]
Now badges by default for simple list item will be appended as first element, for rich list items can be appended to the header.
later we will support creating a list item from a template instead of having a fixed structure.
