### ISSUE TITLE
Allows to set the height and width with value and GWT Unit

### ISSUE THREAD

**Issue by foal** [DominoKit/domino-ui#142]
Now there is only string argument in all size related operations. 
``` java
table.styler(s -> s.setMarginBottom(1 + Unit.EM.getType()))
```
Better to have:
``` java
table.styler(s -> s.setMarginBottom(1, Unit.EM))
```
or
``` java
table.styler(s -> s.setMarginBottom(Styles.dim(1, Unit.EM)))
```

**Comment by foal** [comment]
I am not a CSS specialist, but if the solution will handle cases like `calc(100vh - 123px)` (e.g. `Styles.calc( sub(100, Unit.VH, 123, Unit.PX))`). 
Please, note that GWT Unit enumeration doesn't contain all possible CSS units e.g `vh`. See https://github.com/gwtproject/gwt/issues/8435 .

**Comment by vegegoku** [comment]
The fix adds a Unit class that allow producing unit strings using this syntax `unit.of(number)`
example
```java
element.style().setMargin(Unit.px.of(10));
element.style().setMargin(Unit.em.of(10));
```
with static import of Unit this is reduced to 
```java
element.style().setMargin(px.of(10));
element.style().setMargin(em.of(10));
```
supported units : ` px`,`q`,`mm`,`cm`,`in`, `pt,`pc`, `em`, `rem`,`ex`,`ch`,`vw`,`vh`,`none`

more about units can be found here 
https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Values_and_units

also a new `Calc` class have been added which produce calc strings
example:
```java
element.style()
                .setHeight(Calc.sub(vh.of(100), px.of(267)));
```
