### ISSUE TITLE
File upload enhancement

### ISSUE THREAD

**Issue by RaulPampliegaMayoral** [DominoKit/domino-ui#143]
It would be good to allow setting the url to the files Items once they are created.

Use case:

- File upload folder based on the id returned by the server on the rpc call that create the data object. Once the folder is created, the files can be uploaded to that folder  transparently for the user

**Comment by vegegoku** [comment]
@RaulPampliegaMayoral if setting the url in the onAddFile handler will be sufficient for this use case then i have a fix ready. eg
```java
fileUpload.onAddFile(fileItem -> {
    fileItem.setUrl("someUrl");
});
```

**Comment by vegegoku** [comment]
@RaulPampliegaMayoral so what you actually need is access to the file items of the FileUpload, you will set it to manual upload and only before you upload the file you want to set the url, Right?

**Comment by RaulPampliegaMayoral** [comment]
i think so

**Comment by vegegoku** [comment]
> i think so

in this case just call `getAddedFileItems` and then on each you can call `setUrl`.

**Comment by RaulPampliegaMayoral** [comment]
perfect i did not see that method to establish the url. Was it before?

**Comment by vegegoku** [comment]
@RaulPampliegaMayoral should we consider this as done?
