### ISSUE TITLE
Use PECS (Producer extends and Consumer super) princip for methods with generic arguments

### ISSUE THREAD

**Issue by foal** [DominoKit/domino-ui#145]
For example `changeHandler` for `HasChangeHandlers' should be defined (according to PECS) as
```java
    T addChangeHandler(ChangeHandler<? super V> changeHandler);
```
so, for example for the `String`, the user will able to set the changeHandler that takes the `CharSequence` or even `Object` but not only `String` as now.

More info for PECS [PECS (Producer Extends Consumer Super)](http://books.google.ru/books?id=ka2VUBqHiWkC&pg=PA136&lpg=PA136&dq=bloch+effective+java+pecs+mnemonic&source=bl&ots=yYKnPjt-P-&sig=JGT8qexAAldJ5xYPepbBQ5uude0&hl=en&sa=X&ei=Cb3GUv-sNIuK5ATM7oD4Dw&ved=0CCgQ6AEwAA#v=onepage&q=bloch%20effective%20java%20pecs%20mnemonic&f=false) and [Get and Put Principle](http://books.google.ru/books?id=zaoK0Z2STlkC&pg=PA19&lpg=PA19&dq=Naftalin+and+Wadler+Get+and+Put+Principle&source=bl&ots=6Xuqgc-XGO&sig=W9eFVjUg2Wi3no0bQS4359Fhu-k&hl=en&sa=X&ei=QLzGUvzMNsXZ4QTE1YGYDw&ved=0CCoQ6AEwAA#v=onepage&q=Naftalin%20and%20Wadler%20Get%20and%20Put%20Principle&f=false)

**Comment by vegegoku** [comment]
Can you please specify the case where it didnt work fir you as expected, since form fields has specific datatype for each , TextBox is String, CheckBox is boolean ...and so on.

**Comment by foal** [comment]
The case may be a very simple: assume I have a DoubleBox and a TextBox and want to use the same changeHandler for both fields. With PECS I can define one like `private final ChangeHandler<Object> handler = this::onChange;`  Without I need the following construction
```java
	private final ChangeHandler<Double> doubleHandler = this::onChange;
	private final ChangeHandler<String> stringHandler = this::onChange;
```

But beside this example, the following the PECS is the right way for the any Java API. It removes unnecessary limitations from the methods with generic arguments.

**Comment by vegegoku** [comment]
@foal I will try to get this done as soon as possible
