### ISSUE TITLE
SelectHeaderFilter behind table body

### ISSUE THREAD

**Issue by doctorj** [DominoKit/domino-ui#152]
When table is set to fixed, select items are not visible, they are behid table body.

When table is not fixed, all items are visible but if height of rows is less than height of Select you have to scroll to view all select items.

![datatable-select](https://user-images.githubusercontent.com/360289/48983511-1a5e3900-f0f0-11e8-8e08-404781c622f9.png)

**Comment by rjeeb** [comment]
fixed https://github.com/DominoKit/domino-ui/commit/7dc395a8e1d7ac0f85c988a158ede14c4b3f4b21
