### ISSUE TITLE
Enable easy internationalization

### ISSUE THREAD

**Issue by doctorj** [DominoKit/domino-ui#162]
Some elements have hard coded english text, usually for placeholders:

TextHeaderFilter: "Search"
HeaderBarPlugin.ClearSearch: "Clear filters" (tooltip)
HeaderBarPlugin.SearchTableAction: "Search"
Tree/Search: "START TYPING..."

It would be nice to have methods to set custom text for such components.

**Comment by vegegoku** [comment]
I will work on them soon.

**Comment by vegegoku** [comment]
> TextHeaderFilter: "Search"

You can do `someFilter.getField().setPlaceHolder("some place holder")` or you can pass the place holder in creation.

> HeaderBarPlugin.ClearSearch: "Clear filters" (tooltip)
> HeaderBarPlugin.SearchTableAction: "Search"

added setters for both and for other header plugin actions.

> Tree/Search: "START TYPING..."

for search added a setter for the placeholder, for the tree added getters for the search and some other elements, get then set the tool-tip or the place holder

if there is more like this please re-open and add a comment.
Thank you for reporting this.

**Comment by doctorj** [comment]
Select element has text "No results matched" when no item match search text.

**Comment by doctorj** [comment]
When using SelectionPlugin, column that is added has tooltip text "Select" hardcoded
