### ISSUE TITLE
Map component

### ISSUE THREAD

**Issue by hadmir** [DominoKit/domino-ui#167]
It seems map component (OpenStreetMap, Google, etc) is missing.

**Comment by vegegoku** [comment]
You should be able to integrate https://github.com/TDesjardins/gwt-ol into a simple div
@TDesjardins can you please confirm that gwt-ol works with domino-ui?

**Comment by TDesjardins** [comment]
@hadmir Short update: It works like described. @vegegoku and me are working on a solution to facilitate the integration of a map component into a domino-ui-application.

**Comment by TDesjardins** [comment]
@hadmir I forget to mention. Not finished but already works:

The domino addon:
https://github.com/DominoKit/domino-ui-addons/tree/master/domino-ui-ol-addon

A sample application:
https://github.com/TDesjardins/domino-map-demo
