### ISSUE TITLE
Placement of DatePicker

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#179]
I have the following code:

    DateBox setPickerStyle = DateBox.create("Geburtsdatum")
	  .setPopoverPosition(PopupPosition.TOP)
	  .setPickerStyle(DateBox.PickerStyle.POPOVER);

It does what it is usually supposed to do - displays the datepicker as Popover to the top.
But if there is not enough screen space, I think it should automatically pop to the button, see screenshot.

<img width="831" alt="datebox placement" src="https://user-images.githubusercontent.com/9572844/52563924-fc58c880-2e02-11e9-9c0c-8d4cec01cc7e.png">

**Comment by vegegoku** [comment]
You should use he top-down position instead of of just top 
https://github.com/DominoKit/domino-ui/blob/f9e4f033c93c7cae004f8101ed64d8e20a4987cd/src/main/java/org/dominokit/domino/ui/popover/PopupPosition.java#L13
