### ISSUE TITLE
Responsive DateTable hidding certains columns

### ISSUE THREAD

**Issue by RaulPampliegaMayoral** [DominoKit/domino-ui#180]
When having a data table with lot of colums the view on mobile is difficult:

![imagen](https://user-images.githubusercontent.com/13700946/52629615-608a9380-2eba-11e9-97bc-da94265112b7.png)

It would be great if the data table has the ability to hide certains columns in mobile view

**Comment by vegegoku** [comment]
now in the when defining the column config you can use `showOn(ScreenMedia)` and/or `hideOn(ScreenMedia)` to control when the column should be shown or hidden.

**Comment by RaulPampliegaMayoral** [comment]
Interesting. I didnt know about this feature in domino

**Comment by RaulPampliegaMayoral** [comment]
@vegegoku 
ColumnHeaderFilterPlugin its not applying the showOn and hideOn method:

![imagen](https://user-images.githubusercontent.com/13700946/52695283-5923c280-2f6c-11e9-932d-63db15ec53db.png)

![imagen](https://user-images.githubusercontent.com/13700946/52695301-7062b000-2f6c-11e9-9769-3e53198c5500.png)

It needs to define the applyScreenMedia like TableConfig
