### ISSUE TITLE
Add removeFormElement to FieldsGrouping

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#181]
Could you please add a `removeFormElement` (and maybe `removeAllFormElements`) to `FieldsGrouping`?

Background: I am adding and removing form elements dynamically.
Currently, fields I removed from the form are still referenced and evaluated in the FieldsGrouping, thus my form does not validate.

Thank you!

**Comment by vegegoku** [comment]
Sorry for being late on this, i miss understood the request, but then realized its easily doable.
