### ISSUE TITLE
Touch problem with selects

### ISSUE THREAD

**Issue by RaulPampliegaMayoral** [DominoKit/domino-ui#184]
When working with a device with touch events support, Select component is not working properly. If i want to scroll down select options will be closed.

I think event listener touched and touchmove from DropDownMenu can be removed:

````
        document.addEventListener("click", listener);
        document.addEventListener("touchend", evt -> {
            if (!touchMoved) {
                closeAllMenus();
            }
            touchMoved = false;
        });
        document.addEventListener("touchmove", evt -> this.touchMoved = true);
````
Attached a simple html 
with the javascript simulating the example. With those events in mobile simulation when scrolling down select is closed. If those events are removed i can scroll down and select properly

[example.zip](https://github.com/DominoKit/domino-ui/files/2874972/example.zip)

**Comment by vegegoku** [comment]
@RaulPampliegaMayoral thank you for reporting will provide a fix very soon.
