### ISSUE TITLE
Add Image to Card Header

### ISSUE THREAD

**Issue by DevFlorian** [DominoKit/domino-ui#186]
It would be nice if you could add an Image to an Card Header.
I'm thinking of something that looks like this:
![image](https://user-images.githubusercontent.com/40760073/53052190-4e05f080-349e-11e9-8503-659513d03e77.png)

**Comment by vegegoku** [comment]
You can now use the `card.setHeaderLogo(...)` to add any node or element including images to the header of the card.

```java
Card.create("Card Title", "Description text here...")
                 .setHeaderLogo(img("http://placehold.it/48x48"))
...

Card.create("Card Title", "Description text here...")
                 .setHeaderLogo(img("http://placehold.it/48x48").css(Styles.img_circle))
...
```

![image](https://user-images.githubusercontent.com/5379625/53645300-3e766c80-3c41-11e9-9508-3e26e5aeb8c5.png)
