### ISSUE TITLE
Prohibit DateBox::openOnFocus() on modal DateBox.

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#190]
I switched my DateBox from DateBox.PickerStyle.POPOVER with openOnFocus() to MODAL. Now, the modal dialog did not close properly (or was reopened by the openOnFocus() Method I guess).

I suggest:
1.) Throw an exception for openOnFocus() with a MODAL DateBox (so the developer is aware of the mistake)
2.) change "openOnFocus()" to "setOpenOnFocus()"

**Comment by vegegoku** [comment]
Datebox should open when using TAB and takes focus

**Comment by schube** [comment]
Not resolved for Firefox.
(But resolved for Chrome)

**Comment by vegegoku** [comment]
@schube there was a reference issue in one of the lambda that prevent picking up the correct listener instance, fixed that and should work as expected now.
