### ISSUE TITLE
Implement window like modal

### ISSUE THREAD

**Issue by tsatatwer** [DominoKit/domino-ui#196]
Is it possible to implement the window like modal component?

**Comment by vegegoku** [comment]
@tsatatwer you mean the window control based on modals

**Comment by tsatatwer** [comment]
Hi ,

any update about this issue .Thanks

**Comment by vegegoku** [comment]
I am sorry for the delay, i am being overwhelmed with the amount of work i have to do, i will start working on this ASAP.

Thank you for the reminder.

**Comment by vegegoku** [comment]
The feature is implemented now, the demo site is under refactoring right now, i will need sometime until i can add a sample. but here is the summary :

The window is basically a modal dialog so what ever apply for a modal applies for the window with some extra features :

- Can be maximized/restored
- Can be close from the close button in the header bar.
- Initially it is not a modal and does not block the content behind it.
- Initially it is draggable , this can be set to false.
- by default it has an absolute position and moves with page scrolling, can be set to fixed to stay on same place all the time.
- Can change the header background, by default it matches the theme color.

![Peek 2019-06-12 02-44](https://user-images.githubusercontent.com/5379625/59314020-0361eb80-8cbc-11e9-9252-355fcc070199.gif)
