### ISSUE TITLE
Add support to sort a data table column programatically

### ISSUE THREAD

**Issue by eguardiola** [DominoKit/domino-ui#198]
The sort can be set programatically by firing a event but the sort icon is not updated to refelct the new sorting direction:

```java
this.table.fireTableEvent(new SortEvent<>(SortDirection.ASC, fullNameColumnConfig));
```

**Comment by vegegoku** [comment]
@eguardiola this have been implemented, but instead of firing the event you need to use the sort plugin itself to do the sort so everything will work as if you clicked the column for the sort.

`sortPlugin.sort(direction, column)`
