### ISSUE TITLE
Add the possibility of hiding image preview from the file upload

### ISSUE THREAD

**Issue by RaulPampliegaMayoral** [DominoKit/domino-ui#201]
When there is not much space in a page it would be nice to have the option of hide the image preview from the file upload.

Also it would be nice if it had the hideOn option enabled

**Comment by rjeeb** [comment]
the file image is accessible from the `FileItem`
```
fileUpload.onAddFile(fileItem -> {
    fileItem.getFileImage().hide();
    // or using hideOn
    fileItem.getFileImage().hideOn(ScreenMedia.MEDIUM_AND_DOWN);
})
```
And you can apply this on all files or on specific files depends on the case.

**Comment by vegegoku** [comment]
@RaulPampliegaMayoral is this still an issue or should we close it?!

**Comment by RaulPampliegaMayoral** [comment]
@vegegoku i have not been able to test it. Give me some more time.

You can also close the issue and reopen if I'll see something wrong

**Comment by vegegoku** [comment]
OK thank you.
