### ISSUE TITLE
Selection/activation of treeItem inside a Tree is confusing.

### ISSUE THREAD

**Issue by foal** [DominoKit/domino-ui#204]
Now to select some node (`TreeItem`) in the tree (`org.dominokit.domino.ui.tree.Tree`) (deselect current if any, expand all parents and select the given node) is not a trivial task if you do not know how :)

Essential way call the `org.dominokit.domino.ui.tree.Tree.setActiveItem(TreeItem)` doesnot work - it just colapse the tree.

The current way is to call the `org.dominokit.domino.ui.tree.TreeItem.show(boolean)` method with `true` and then the `org.dominokit.domino.ui.tree.TreeItem.activate(boolean)` again with `true`, something like this
```java
treeItem.show(true).activate(true);
```

**Comment by vegegoku** [comment]
You can now use the shorter method `treeItem.select()`
