### ISSUE TITLE
Set locale for DatePicker

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#21]
Currently the datepicker (see https://vegegoku.github.io/domino-ui/index.html?theme=indigo#forms/datepicker ) displays the values in English only.
It would be good to set a locale, so one can see German/French/.... names for months and weekdays.

**Comment by vegegoku** [comment]
It already does if you check the sample the datepicker accept a datetimeformat, and in the sample it already display french and english
https://vegegoku.github.io/domino-ui/index.html?theme=indigo#forms/datepicker

**Comment by schube** [comment]
I am sorry, I just wanted to close my issue and then I saw you already commeted. You are to fast :-)
