### ISSUE TITLE
Drag & drop, Sortable component

### ISSUE THREAD

**Issue by masterdany88** [DominoKit/domino-ui#210]
It would be very useful component that will allow You to drag, sort and drop elements like collections.
There are a tons of libraries ready to be used, JSinterop simple wrapper could do the job:
https://codepen.io/rainner/pen/YGrzpv
http://farhadi.ir/projects/html5sortable/
https://lukasoppermann.github.io/html5sortable/index.html
http://camohub.github.io/jquery-sortable-lists/index.html

**Comment by vegegoku** [comment]
Drag drop have been added
