### ISSUE TITLE
Update MDI Icons with latest version (3.6.95)

### ISSUE THREAD

**Issue by foal** [DominoKit/domino-ui#211]
Please, update MDI Icons with latest version (3.6.95) from https://materialdesignicons.com

**Comment by vegegoku** [comment]
I will try to update them as soon as possible, actually i have processor implemented but i need to merge the changes with the master branch after some cleanup

**Comment by foal** [comment]
Anyway, there is a file generated from 3.6.95 for references.

[MdIcons.java.zip](https://github.com/DominoKit/domino-ui/files/3231948/MdIcons.java.zip)

**Comment by vegegoku** [comment]
Can you share with me the link to the meta json file?

**Comment by vegegoku** [comment]
Now the icons will be synced with every build, this might be changed later to avoid unexpected breaking changes, but it is good to stay-up to date all the time.

you can also make use of some new generated sources like `MdiByTagFactory` that allows you to get a list of icons by tag, also the `MdiIcon` class now has the `getMetaInfo` whicj returns the meta data used for the icon creation.

**Comment by foal** [comment]
As I can see, now you get the 3.0.39 version (MdiIconsProcessingStep) of the icon set, but there is a new one - https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/v3.6.95/meta.json

**Comment by vegegoku** [comment]
@foal i will make it load from master always
and will also make it fetch the css and the fonts

**Comment by vegegoku** [comment]
@foal i made it to build from master branch - we can switch to specific version if we face issues - and it will update the icons, the css and the fonts, but i will hold on this just a little bit until i update the demo site.
