### ISSUE TITLE
Don't make breadcumbs items clickable by default

### ISSUE THREAD

**Issue by RaulPampliegaMayoral** [DominoKit/domino-ui#212]
By default when abreadcumb item is added on the breadcumb a clickevent is added automatically that make the item active.

It would be nice that by default dont be this click event active, and have the posibility to add it programatically if needed.

**Comment by vegegoku** [comment]
@RaulPampliegaMayoral The fix will not change the default behavior but it is now easier to turn it of using : 

```java
Breadcrumb.create().setAllowNavigation(false);
```

**Comment by RaulPampliegaMayoral** [comment]
Thanks @vegegoku!!
