### ISSUE TITLE
Too long tree element

### ISSUE THREAD

**Issue by foal** [DominoKit/domino-ui#214]
Hi, if I add to long tree element it looks a little bit ugly. It takes the icon space on the left side and cuts off the right side.
![image](https://user-images.githubusercontent.com/458209/58898549-18a6ab00-86fb-11e9-9d4e-19d893a2777d.png)

It will be nice if the left side will be aligned as the rest of the elements and the right side will have an ellipsis (text-overflow: ellipsis;) instead of cut.

**Comment by foal** [comment]
Like below
![image](https://user-images.githubusercontent.com/458209/58899008-30cafa00-86fc-11e9-9613-13b8d084ff61.png)

**Comment by foal** [comment]
Looks like the left side (icon) is correct. The effect on the first screenshot caused by manual editing...

**Comment by foal** [comment]
![image](https://user-images.githubusercontent.com/458209/58902574-a5edfd80-8703-11e9-82af-e6fe995771a9.png)

**Comment by foal** [comment]
A possible solution for long items
![image](https://user-images.githubusercontent.com/458209/58904110-25310080-8707-11e9-9ba7-2a063c80c18a.png)

**Comment by vegegoku** [comment]
the commit fix the long item issue, but regarding showing a popup is a very complex solution, instead for now you can just set a tooltip with the default position `treeItem.setTooltip("the tree item title")`
