### ISSUE TITLE
Loader is not seen correctly when there is a lot of content

### ISSUE THREAD

**Issue by RaulPampliegaMayoral** [DominoKit/domino-ui#216]
If i have a page with too much content the loader will overlay over all content positioning the text at the center. If I'm on top from the page i won't view the loading text making an ugly effect

![imagen](https://user-images.githubusercontent.com/13700946/59086210-54ab5d00-8901-11e9-925d-c70f4b1c3f98.png)

![imagen](https://user-images.githubusercontent.com/13700946/59086248-79073980-8901-11e9-84b8-8e260efbb854.png)

**Comment by vegegoku** [comment]
@RaulPampliegaMayoral looking into this, limiting the mask to to the visible view-port is very complicated, and works only for few use cases when the masked element is the whole content panel, knowing that masking the body element works fine with the current implementation, if we are to have an option to limit the mask to the visible view-port then we need to count for scrolling, which means we will also need to track the attach/detach cycle of not just one loader mask but also for multiple loaders might show up together. so all this complication is to solve very few special cases.

instead i implemented a `LoadingTextPosition` option with values `TOP`,`MIDDLE`, and `BOTTOM`.
which will set the position of the loading text and effect to `10%`, `50%` and `90%` respectively, later if we found that this not enough we can enhance it to be flexible.

**Comment by vegegoku** [comment]
@RaulPampliegaMayoral I am closing the issue, but you still can test and comment, and we can re-open it if needed :smiley:

**Comment by RaulPampliegaMayoral** [comment]
@vegegoku 

I cant see the loader positioning correctly. I'm defining the loader this way:

````
loader = Loader.create(container, LoaderEffect.STRETCH).setLoadingText("Cargando...");
loader.setLoadingTextPosition(LoadingTextPosition.TOP);
````
and this is the code generated:
![image](https://user-images.githubusercontent.com/13700946/59745688-9dee9b80-9275-11e9-8721-4db54bea27f5.png)

But cant see any css rule that is applying to the loading-top
