### ISSUE TITLE
ScrollTop doesn't work on IE11

### ISSUE THREAD

**Issue by TDesjardins** [DominoKit/domino-ui#217]
On IE11 the ScrollTop doesn't work. There is a Nullpointer at: 
https://github.com/DominoKit/domino-ui/blob/master/domino-ui/src/main/java/org/dominokit/domino/ui/scroll/ScrollTop.java#L28

The Button doesn't appear and there is an error message in the browser console. Also occures on the domino-ui demo site.

**Comment by vegegoku** [comment]
@TDesjardins Do you have any suggested solution in mind? all i could find is some polyfills

**Comment by TDesjardins** [comment]
@vegegoku Not in mind and didn't searched for a solution, yet. Don't know if this can be done without polyfills. At least we can disable this feature on IE11 (respectively on browsers that don't have this property) to avoid errors.

**Comment by TDesjardins** [comment]
Works for me! Thanks!
