### ISSUE TITLE
ModalDialog is not modal

### ISSUE THREAD

**Issue by FrankHossfeld** [DominoKit/domino-ui#220]
Steps to reproduce:

* create a ModalDialog
* open it

everything is **ok**.

Now, imagine you have a cancel-button inside the ModalDialog. Once pressed, the user should be informed, that all of his changes get lost. Therefore, 

* create a MessageDialog
* open it

Now, both Dialogs are no longer modal.

**Comment by FrankHossfeld** [comment]
After some time spending in investigation, I was able to identify the problem.

In case two modals get open, let's call them modal01 and modal02, and modal01 gets opened before modal02, then it is necessary to close modal02 before modal01.

Changing the closing order (close modal01 before modal02) will cause the problem.

**Comment by rjeeb** [comment]
Now closing modals work both ways (i.e. in the order or different order)
