### ISSUE TITLE
Problem with Row grid and hideOn/showOn

### ISSUE THREAD

**Issue by RaulPampliegaMayoral** [DominoKit/domino-ui#223]
Hi!

If i have a row and i want to hide/show the content based on the screen media i would do:

````
Row.create()
    .addColumn(Column.span(3,3,3,6)
                    .appendChild(Card.create("content 1")))
    .addColumn(Column.span(3,3,3,6)
                    .appendChild(Card.create("content 2"))) 
    .addColumn(Column.span(3,3,3,6)
                    .appendChild(Card.create("content 3")))
    .addColumn(Column.span(3,3,3,6)
                    .appendChild(Card.create("content 4")))
    .hideOn(ScreenMedia.MEDIUM_AND_UP)
    .showOn(ScreenMedia.MEDIUM_AND_DOWN)
````
The showOn property is overloading the display : grid from the Row.

**Comment by RaulPampliegaMayoral** [comment]
I'm using the showOn because i want to show one row only over medium and down and other Row over medium and up.

If i don't use the showOn property there are some times that the content is not showing (f.e from 1000px to 1200px)

**Comment by vegegoku** [comment]
I dont think i understand the last comment

**Comment by RaulPampliegaMayoral** [comment]
Basically i have 2 div that i want to show depending on the device. But i was using hideOn in the bad way. I should use .hideOn(ScreenMedia.LARGE_AND_UP) for one div and .hideOn(ScreenMedia.MEDIUM_AND_DOWN) for the other.
With this configuration i can avoid using .showOn method.

I hope to have explained myself well
