### ISSUE TITLE
 ProgressBar css : default color has the priority

### ISSUE THREAD

**Issue by nchamouard** [DominoKit/domino-ui#224]
The color of the ProgressBar is always #337ab7 (defined in progressbar.css), the css property overrides the bg-l-1-orange #ffa726 given by progressBar.setBackground(Color.ORANGE_LIGHTEN_1)

it was still working correctly a few days ago, the problem may be related to recent the css restructurations

**Comment by nchamouard** [comment]
striped() and animate() do not work either

**Comment by rjeeb** [comment]
Thanks for reporting that, I'll fix these problems today.
