### ISSUE TITLE
Problem with sheet modal and iexplorer11

### ISSUE THREAD

**Issue by RaulPampliegaMayoral** [DominoKit/domino-ui#225]
When try to open the right sheet modal, the overlay is shown but not the modal

![imagen](https://user-images.githubusercontent.com/13700946/59527741-b3ae3a80-8edc-11e9-9632-84197bdb6e66.png)

This happens with left and right sheet modal but not with top and bottom sheet modals.

![imagen](https://user-images.githubusercontent.com/13700946/59527848-fec84d80-8edc-11e9-9fb4-35e689ad6358.png)

**Comment by vegegoku** [comment]
We will work on this ASAP.
 but one advice here you and your client should stop using IE before it is too late. 😉
