### ISSUE TITLE
Missaligned floating labels

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#23]
Sometimes floating labels are missaligned. It is hard to describe, so please look at the screenshot.
<img width="489" alt="dominoui" src="https://user-images.githubusercontent.com/9572844/40062013-7d439eb8-585a-11e8-9999-776e2dd6daf4.png">

**Comment by vegegoku** [comment]
fixed with https://github.com/DominoKit/domino-ui/issues/14
