### ISSUE TITLE
Allows disabling AddValues input in the TagsInput field programmatically 

### ISSUE THREAD

**Issue by foal** [DominoKit/domino-ui#231]
Hi, I need to have custom TagInput that takes values from external fields

foal @foal 15:05
custom property editor
How I can disable original tagTextInput?
I found only one way - set maxSize to 0, but it updates TagInput only on the first add
![image](https://user-images.githubusercontent.com/458209/59607118-01ac8380-9113-11e9-8d82-07a8ff3f8055.png)

before add
 
after add
![image](https://user-images.githubusercontent.com/458209/59607102-f8bbb200-9112-11e9-8fc7-071d1187b875.png)

Rafat J. Al-Barouki @rjeeb 15:10
so you want to add the values from the code without user interaction

foal @foal 15:10
Yes

Rafat J. Al-Barouki @rjeeb 15:10
did you try to set readonly to true?
actualy disable() method

foal @foal 15:11
I tried, but I need to remove the tags too :)
with RO it isn't possible

Rafat J. Al-Barouki @rjeeb 15:11
so you need to play with the tags but you don't need the text box

**Comment by rjeeb** [comment]
Now there are two methods to disable/enable user input
```
tagsInput.disableUserInput();
tagsInput.enableUserInput();
```

**Comment by foal** [comment]
Just one note - I suggest to initialize the variable `userInputEnabled` with `true` e.g. 
```java
private boolean userInputEnabled = true;
```
Now it is false by default and may work incorrectly on `fireChangeEvent` in case of exceedsMaxSize

**Comment by rjeeb** [comment]
yes sure it should be true by default, I'll fix that thanks for your great feedback.
