### ISSUE TITLE
Add updateRecord in LocalListDataStore

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#242]
In a `LocalListDataStore` (which I use for a `DataTable`), we have `addRecord` and `removeRecord`, but no `updateRecord`. Could you add `updateRecord` please?

Related to that:
I do not understand why `addRecord`/`removeRecord` calls `load()` internally, which triggers `fireUpdate()`, but `setData` does not. I think `setData` should also trigger `fireUpdate()`
So in my code i now have to call `setData` (with my updated list of records, because there is no `updateRecord`) and then `load()`, so the `DataTable` shows the correct data.

Thank you

**Comment by vegegoku** [comment]
In this case are we talking about updating the record with the same reference of the original record, meaning that i am just updating the same instance of the record or we are talking about a completely new instance that i want to replace existing record?

**Comment by schube** [comment]
We are talking about a "completely new instance that i want to replace existing record"
Thanks

**Comment by rjeeb** [comment]
New methods have been added to support this:
- `updateRecord(record)`
- `updateRecord(index, record)`
- `updateRecords(records)`
- `updateRecords(startIndex, records)`

**Comment by schube** [comment]
Thank you for your hard work! Very appreciated!
