### ISSUE TITLE
CheckBox text label can't be hidden separately on specific devices.

### ISSUE THREAD

**Issue by HMIDeer** [DominoKit/domino-ui#250]
checkBox.getLabelElement().hideOn(ScreenMedia.MEDIUM_AND_UP);" hides the complete CheckBox on medium and up devices instead of only the text label.

**Comment by vegegoku** [comment]
You can now use `checkbox.getLabeleTextElement().....`

**Comment by HMIDeer** [comment]
If setting the checkbox to readonly the lable is still present but it should be hidden e.g. as i've defined on medium and up devices

**Comment by vegegoku** [comment]
i will try to fix this soon
