### ISSUE TITLE
Add a repeat option to CSS ANIMATIONS

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#252]
Could you add an option to repeat an animation N times please?
Something like:

```
   Animation.create(btnAddLicences)
            .transition(Transition.SHAKE)
            .duration(1000)
            .repeat(5)
            .animate();
```

I do not know, how you would handle `duration` and `repeat`, so in the given example, if the whole animation would be 5 times 1000 or 1000. You decide :-)

Thank you!

**Comment by vegegoku** [comment]
You can now use the repeat feature, the duration is standard animation property, so this means for the sample you posted above the animation will run for the duration of 50000
