### ISSUE TITLE
Change behavior when clicking TreeItem with children

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#267]
I have a Tree with nested SubItems.
Currently, there is a "+" or "-" sign which indicates, if the node is collapsed or not.

When I click on a TreeItem label to select it, the collapse state toggles automatically.

There is no distinction, if the user clicks on the label to select the TreeItem or if he clicks the +/- icon, to collapse/expand the TreeItem.

Please change the behavior, so both kind of clicks can be distinguished.

With other words:
* A click on the label should NOT change the collapse/expanse state
* A click on +/- label should toggle collapse/expand, but should not select/activate the TreeItem

**Comment by vegegoku** [comment]
We will make is configurable on how you want to expand/collapse the tree item, 
- click anywhere
- click on the left icon
- click on the right +/-

also will add the ability to change the +/- to use any icons pair.

**Comment by vegegoku** [comment]
Ok the final implementation went to have only 2 options for the toggle , `any` and `icon` when any is selected it will expand/collapse when ever the tree item is clicked anywhere, while icon will only expand/collapse if the left icon is clicked, and clicking the title wont toggle the tree item.

the right side expand/collapse indicator are now clickable and always active in regards of the toggle Target option for the tree, this means you still can toggle the item when the toggle target is icon but icon might not exist.

to change the toggle behavior call `myTree.setToggleTarget(TggleTarget)`

**Comment by schube** [comment]
Perfect, thank you!
