### ISSUE TITLE
Make Column spans readable

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#268]
One can set Column spans with

    public static Column span(int xLarge, int large, int medium, int small, int xsmall)

or with for example

    public Column onXSmall(OnXSmall onXSmall)

but the set values cannot be read.
Please add getters.

**Comment by vegegoku** [comment]
use like this 
`someColumn.getOnLargeStyle().getSpan().getValue()` this will return an integer value for the span where 0 means full span while other numbers are the actual span number.

use the same for the offset
`someColumn.getOnMediumOffsetStyle().getOffset().getValue()`  this will return the value of the offset where -1 means none.
