### ISSUE TITLE
ButtonSize lacks size DEFAULT

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#271]
The ButtonSize enum needs a size "DEFAULT".
Also, related to this issue, when using a vanilla Button, calling "getSize" returns NULL.

**Comment by vegegoku** [comment]
@schube the NULL is correct because default dont actually have a size, when the button has a size there will be a css class added to set the size for the button, but when there is no size set then there is no css class, so the css class for the default does not exists actually.

**Comment by schube** [comment]
@vegegoku 
Yes, I understand, that it is how you handle it **internally** within DominoUI.

But for an API user, this is confusing and also it is not consistent, because StyleType for example has a default value.

Thank you!

**Comment by vegegoku** [comment]
@schube actually there is a big difference, the ButtonSize default does not exist as a style while the StyleType default is an actual style that exists, now for example if you try to get the StyleType for default that will return `default` but in case of ButtonSize even if i add the enum it will still return null. so it is null either way.

**Comment by vegegoku** [comment]
The proposed solution for this is to introduce a new Style `medium`, there will be no more default/empty size style, the button will always have a size style, the css properties for a button size will be extracted from the button with no size and used in the new css class .

**Comment by schube** [comment]
great, thank you!
