### ISSUE TITLE
DataTable column headers aren't displayed

### ISSUE THREAD

**Issue by HMIDeer** [DominoKit/domino-ui#272]
Creating a DataTable with a empty TableConfig and adding the columns afterwards leads to a missing table header. As well as the plugins

**Comment by vegegoku** [comment]
@HMIDeer this will break all plugins, think about plugins that do some work after headers added, then do we expect the headers to be added?! this could happen at any point which means such plugin wont ever get to be executed.

i would suggest that we have a method to reset the table when ever a new column is added after the table config have already been consumed by the table before, but this looks like an overkill to me.

another suggestion is to have a method to reset the table once i am done adding new columns, but this is just like creating the table from scratch with a ready config.

So in general i would like to understand your use case to have a better insight on the problem and try to figure the required solution.

**Comment by vegegoku** [comment]
No response.

**Comment by HMIDeer** [comment]
@vegegoku Sorry for the late reply but I was concentrating on the low hanging fruits of my application. Now that I've encountered the problem again I will add a proper explanation. In some cases we are using not only columns which are known e.g. a index or description but also columns which based on data. These colummns are dynamically and could be changed (added/removed) on data refreshing. The reset or maybe better reInit of a table i think would be a proper solution for that. What do you think?

**Comment by HMIDeer** [comment]
Any opinion about that?

**Comment by vegegoku** [comment]
I would suggest that you build the datatable from scratch everytime, create a new config and recreate the table.

**Comment by HMIDeer** [comment]
Ok, but this means I need to redraw the complete dialog every time the data is refreshed. Currently the table.element() method is just called on the first visit

**Comment by vegegoku** [comment]
why would you draw the complete dialog, i need to see some code to understand the exact use case

**Comment by HMIDeer** [comment]
Assume I have a dialog which contains a DataTable. The table has columns which are always there but additonally some more columns could be added if the data changes. This data table is rendered the first time the user enters the dialog by appending it to the content panel of a Layout. To refresh the data a separate FAB is used which starts the process of getting the data from the server and after this is finished update the data in the DataTable by calling setData. In that case the element() method is just called once, which I think is responsible for rendering the table, header etc. I can replace the TableConfig and also the DataTable object but it won't get rendered as long as I am calling the element() method again?
