### ISSUE TITLE
Disable Selection-Plugin on selected Row for Data-table

### ISSUE THREAD

**Issue by whiteKnightz** [DominoKit/domino-ui#280]
Disable Selection-Plugin checkbox and selection for a certain row based on data of a field in the Row of the Data-table

**Comment by vegegoku** [comment]
you can now use 
```
selectionPlugin.setSelectionCondition((dataTable, tableRow) -> tableRow.getRecord().....);
```
which should return a boolean to decide if the selection for the row will be enabled or not.
