### ISSUE TITLE
Make search() method in SuggestBox public

### ISSUE THREAD

**Issue by doctorj** [DominoKit/domino-ui#283]

**Comment by doctorj** [comment]
Here's my use case:
I don't want to query backend every time user types something in SuggestBox and since data set is large I can't store it in local store. It would be nice if SuggestBox starts search on user press enter, but since that's not the case I simulate that behaviour like this:
I have a TextBox where user can type first n letters and press enter. I fetch subset of data that match that pattern from backend and populate LocalSuggestBoxStore of SuggestBox. Then I hide TextBox, unhide SuggestBox and call search method that opens SuggestBox dropdown menu so user can choose item.

**Comment by vegegoku** [comment]
OK, so if we make it configurable to make suggest box search on enter instead of every typed key will this solve the issue?

**Comment by TDesjardins** [comment]
> OK, so if we make it configurable to make suggest box search on enter instead of every typed key will this solve the issue?

Then it isn't a SuggestBox, right?

**Comment by vegegoku** [comment]
@TDesjardins i am not sure if using it in a different way means it is not a suggest box anymore or not. we just change how the suggestions are triggered.

another solution would be to change the delay before the suggestion are shown up so the use might type more letters and we end up with a refined set of records.

So what do you think?

**Comment by doctorj** [comment]
Yes, we call component that lets us filter as we type SuggestBox. But it has suggestions and it is a Box, even if suggestions are triggered differently. If you decide to implement it you can name it LazySuggestBox? It is not something that I need urgent, I changed search method to public in my local repo and I use it that way.

**Comment by TDesjardins** [comment]
> I don't want to query backend every time user types something in SuggestBox

Is there a special reason for this? You don't want this but what about your users? It sounds like a bad user experience. By the way the SuggestBox don't search on every keyevent. It have a delay for waiting for a new type event. So your users will anyway type more than one or two characters before the request is started.

**Comment by vegegoku** [comment]
@TDesjardins @doctorj yes and we can make this delay adjustable so we can let the user type more characters for such cases. so  what do you think?

**Comment by TDesjardins** [comment]
@vegegoku I think the possibility to adjust the delay is useful.
@vegegoku What are the disadvantages when making method "search" public besides the extra effort for API maintainance?

**Comment by doctorj** [comment]
@vegegoku sounds good, thank you.

**Comment by vegegoku** [comment]
@TDesjardins no really about the disadvantage as much as it is about fixed the real use case and problem, yet the search method is called internally and there is some login to when it should be called, could expose that logic instead, beside overriding this method might lead to wrong behaviors. but i am not against exposing a public method for the search.

**Comment by TDesjardins** [comment]
@vegegoku Agree, so you even mentioned some additional disadvantages.
@doctorj Is the approach to adjust the delay a satisfactory alternative to your origin suggestion?

**Comment by doctorj** [comment]
@TDesjardins  yes, it will be very usefull

**Comment by vegegoku** [comment]
Now you can change the delay before triggering the search using `suggestBox.setTypeAheadDelay(milliseconds)` the default remains the same `200`

if later on we find that we still need to expose a search method we will do it.
