### ISSUE TITLE
Add bordered styles to buttons.

### ISSUE THREAD

**Issue by rjeeb** [DominoKit/domino-ui#288]
It would be great if buttons have a new bordered style.

Buttons can have bordered styles by using:
`button.bordered();`
Also, border color can be specified by using:
`button.bordered(Color.RED);`

**Comment by TDesjardins** [comment]
Is this really needed? In my opinion this should be done with CSS.

**Comment by rjeeb** [comment]
It can be done with CSS of course but this for simplifying things only, when you are working with button types then you need to worry about all these things in order to make it work for all types so domino-ui now provides that for you internally without worrying about these details.

**Comment by TDesjardins** [comment]
> It can be done with CSS of course but this for simplifying things only, when you are working with button types then you need to worry about all these things in order to make it work for all types so domino-ui now provides that for you internally without worrying about these details.

So you have to maintain extra code for simplifying things that are bad practices. Colors should specified in  CSS not in the Code. Why should I set a color for a border in Java Code when I can set it in CSS? So also the designer can change it without asking the very busy developer 😆

**Comment by rjeeb** [comment]
Setting the border color is optional so you either use it or use your custom css styles to set the color for the button it is your choice as a developer to choose between these two options.

making this change is not a bad practice, domino-ui provides a set of styles to simplify and re-use these styles whenever needed but you can always customize things, our lib provides these colors and all our components support these colors in their APIs so it doesn't make sense to not provide this in button's API. Moreover, when you set a color using domino-ui component APIs, you actually add a predefined style that sets the color of your component to the color value so you can always customize that and add whatever style you need. Setting the border color of a button is exactly like setting the background of that button and these two options are provided by APIs.
