### ISSUE TITLE
Let enter key press for DelayedInputText be customizable

### ISSUE THREAD

**Issue by RaulPampliegaMayoral** [DominoKit/domino-ui#291]
When you press enter at the suggest box component the default action is filter the suggestions.
In some cases maybe want to make other action when this key is pressed

**Comment by RaulPampliegaMayoral** [comment]
@vegegoku but with this commit the delayed action and the enter key action is the same.  How would you do to have an action for the key pressed and another one when enter key is pressed?

**Comment by vegegoku** [comment]
@RaulPampliegaMayoral so want to execute 2 actions not override the existing one?

**Comment by RaulPampliegaMayoral** [comment]
Yes, for example, i want to launch a search to the server with the text value when enter is pressed, but allow to suggest just as it is being done

**Comment by vegegoku** [comment]
And how would you coordinate between the 2 actions in this case, i mean the search on server is an async action, and you have to wait for its completion?! then you can call the find method or something, the new behavior allows to put any logic in there, the only other thing i can think of is to inject some sort of calls after the results are returned from the server.

**Comment by vegegoku** [comment]
And one more thing, when you check your pull request it does almost the same as my commit since it completely override the entry key delayed action?!

**Comment by RaulPampliegaMayoral** [comment]
> 
> 
> And one more thing, when you check your pull request it does almost the same as my commit since it completely override the entry key delayed action?!

I defined two actions:

````
private DelayedAction delayedAction = () -> {
    };
private Runnable enterKeyPressedAction = () -> DelayedTextInput.this.delayedAction.doAction();
````

Defining the default action of enterKeyPressedAction the same as the delayed one.

**Comment by vegegoku** [comment]
@RaulPampliegaMayoral that code preserve the default dehavior until you call `public void setEnterKeyPressed(Runnable keyPressedAction)` which you added in the PR too, my commit does the same , it preserve the default behavior until you set the delayed action in the suggest box..am i right?

**Comment by RaulPampliegaMayoral** [comment]
Yep, but if i'm not wrong with this:
````
inputElement.addEventListener(EventType.keypress.getName(), evt -> {
            if (ElementUtil.isEnterKey(Js.uncheckedCast(evt))) {
                DelayedTextInput.this.delayedAction.doAction();
            }
        });
````
When enter is pressed you are executing the same action as the delayed one. I proposed that this action be different.

**Comment by vegegoku** [comment]
notice the suggest box has a new setter for the delayed action, and that setter also set it for the delayed input, now you can do something like this :
```
mySuggestBox.create("some label", myStore)
   .setDelayedAction(()->{
//let me do whatever i want when the enter key is pressed. i can get the store using the getStore method or the get the search text from the getInputElement. 
});
```

**Comment by RaulPampliegaMayoral** [comment]
ok i think i got it. Let the delayedAction check if enter is pressed. Isn't it? If so i think it can solve my use case

**Comment by vegegoku** [comment]
Why it is only triggered when the key enter is pressed.

**Comment by vegegoku** [comment]
Ok i got it now, you want the action to be executed only when the enter key is pressed and after the delay period ends?!.. right?!

**Comment by RaulPampliegaMayoral** [comment]
I think i'm not explaining well.

What i'm looking for is something like the suggestions from the explorer. While you are writing is suggestin differents url (this is accomplish with the delayedtextinput if i'm not wrong). But if you click enter whith some text (and not over the suggestions) the browser will do a search.

By now, when you click enter in the SuggestBox the delayedtextinput will be execute, making the same suggestions. 

I must notice that i'm making a remote suggestios search.

**Comment by vegegoku** [comment]
ok so if you wan to inject another enter key action without the delay trigger you can just attach a simple enter key listener in the suggestbox input element 
```
KeyboardEvents.listenOn(SuggestBox.create("some label", someStore).getInputElement())
                .onEnter(evt -> {
                    DomGlobal.console.info("we can do a full search here");
                });
```

**Comment by RaulPampliegaMayoral** [comment]
@vegegoku Yes, i had already done something similar, but then the two events are triggered making 2 request to the server. I was trying to remove the eventlistener for the inputelement but as far as i know this is not possible without the reference to the eventlistener.

I have been watching other issues and maybe my problem is related to  #283

**Comment by vegegoku** [comment]
Ok now i understand what you want, in this case we can split the delay action from the enter key action.

**Comment by RaulPampliegaMayoral** [comment]
Thanks @vegegoku!! I think i was no able to explain my self very well. I must put this example first.

Sorry for bother you!!

**Comment by vegegoku** [comment]
No 100% cool and ok, i also took my time understanding the issue, anyway i got it fixed now - i hope so -
you can now set the `onEnterAction` which is defaulted to the delayed action and can overridden separately

**Comment by RaulPampliegaMayoral** [comment]
It's very close to my pull request. I think it can work perfectly!

Thanks again for the time expended on this
