### ISSUE TITLE
margin-bottom in DataTable with record details plugin destroys layout

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#298]
**Describe the bug**
A style definition of `margin-bottom: 0` in `.table td .form-group` results in display errors in the record detail view.

**To Reproduce**
Use a DataTable with the Record Details Plugin.
Place a TextBox within the record details.

**Screenshots**
![Bug](https://imgur.com/tWw3qZl.png)

![Without margin-bottom: 0](https://imgur.com/b1tHM14.png)

**Desktop (please complete the following information):**
 - OS: osX
 - Browser Chrome
 - Version 77

**Comment by vegegoku** [comment]
This should be fixed with the new fields
