### ISSUE TITLE
A dropdown button within the left panel of layout is cut off.

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#30]
Please see screenshot:
<img width="527" alt="dropdowncutoff" src="https://user-images.githubusercontent.com/9572844/40497562-d3d2bd8a-5f7c-11e8-9987-9534ba249f3f.png">

It is just a simple dropdown button:

		DropdownButton dp = DropdownButton.create("test")
				.addAction(DropdownAction.create("Action"))
				.addAction(DropdownAction.create("Another action"))
				.addAction(DropdownAction.create("Something else here"))
				.separator()
				.addAction(DropdownAction.create("Separated link"));

**Comment by vegegoku** [comment]
Thank you for reporting, we will fix this asap
