### ISSUE TITLE
Allow datatable multiselect plugin to select row range when shift key is pressed with click

### ISSUE THREAD

**Issue by vegegoku** [DominoKit/domino-ui#300]
In a datatable with a selection plugin that allows multi select when one row is selected then press shift key and select another row all records between the 2 selected rows will be also selected.

**Comment by schube** [comment]
Thank you so much!

**Comment by schube** [comment]
It works (almost) perfectly, thank you again.
One small issue: If, let's say, 20 records are selected at once, the selection-event is fired 20 times, instead of once.
