### ISSUE TITLE
BasicFormElement performs invalidate() for valid editor elements

### ISSUE THREAD

**Issue by adrian-haenni** [DominoKit/domino-ui#302]
**Describe the bug**
When saving a GWT Editor, the (valid) Form Elements become red colored because of calling updateValidationStyles() from invalidate() in ValueBox. The colorization is only shortly visible right before the editor disappears. It's because BasicFormElement performs invalidate() caused by its showErrors(List<EditorError> errors) method even for valid editor elements. 

**To Reproduce**
Save a GWT editor with Domino UI Form Elements using a GWT driver.

**Expected behavior**
Color of Form Elements should not change right before editor is successfully saved and disappears.

**Cause**
showErrors(List<EditorError> errors) method is called by com.google.gwt.editor.client.impl.ErrorCollector when saving. GWT ErrorCollector passes collected errors to the editor. It will pass empty error collection to the editor so that it can clear any existing errors when problems are fixed. Therefore we must invalidate for non-empty list and clear invalid for empty ones!

**Comment by adrian-haenni** [comment]
**Possible Solution**
```
    @Override
    public void showErrors(List<EditorError> errors) {
        final List<String> editorFormElementErrors = errors.stream()
                .filter(e -> this.equals(e.getEditor()))
                .map(EditorError::getMessage)
                .collect(Collectors.toList());

        if(editorFormElementErrors.isEmpty()) {
            clearInvalid();
        } else {
            invalidate(editorFormElementErrors);
        }
    }
```

**Comment by vegegoku** [comment]
fixed on branch https://github.com/DominoKit/domino-ui/tree/form-fields-revamped
