### ISSUE TITLE
DateBox not rendered correctly on FireFox/Windows

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#303]
**Describe the bug**
See screenshot, the blue DateBox does not display the years, they are cut off by the scroll bar.
The green DateBox works, although.

**To Reproduce**
Open https://demo.dominokit.org/forms/datepicker?theme=indigo
with FireFox (70.0.1) on Windows 10, scroll to the bottom where the DateBoxes are, open DateBox, click on the year.

**Screenshots**
![Buggy blue DateBox](https://i.imgur.com/cPc7XhC.png)
![Green working DateBox](https://i.imgur.com/hV0xxeC.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser FireFox
 - Version 70.0.1

**Comment by vegegoku** [comment]
fixed in the new form fields branch https://github.com/DominoKit/domino-ui/tree/form-fields-revamped
