### ISSUE TITLE
[Form fields] SelectHeaderFilter - dropdown not visible

### ISSUE THREAD

**Issue by doctorj** [DominoKit/domino-ui#308]
Select in table header - when clicked, dropdown opens behind table body and is not visible.

**Comment by vegegoku** [comment]
I have been testing this and could not reproduce

**Comment by vegegoku** [comment]
I was able to reproduce the case and should be fixed very soon.

**Comment by vegegoku** [comment]
the fix made more issues with the datatable, will need to find a better solution, most likely will need to change how we open the popup.
