### ISSUE TITLE
[Form fields] SelectionPlugin checkbox

### ISSUE THREAD

**Issue by doctorj** [DominoKit/domino-ui#309]
Tables with SelectionPlugin have checkbox inside header. After first click on that checkbox it moves up (and stays there, checked or not).
![Peek 2019-12-01 18-11](https://user-images.githubusercontent.com/360289/69918148-b131a400-146e-11ea-9867-53a416307ebc.gif)

**Comment by vegegoku** [comment]
fixed on branch https://github.com/DominoKit/domino-ui/tree/form-fields-revamped

**Comment by doctorj** [comment]
After first click on checkbox that is inside table row (not table header) it moves up (and stays there, checked or not).
I also noticed one more thing: this only happens when single checkbox is clicked; when all checkbox are selected at once (by clicking check box in the header) none of checkboxes move up.
![chk](https://user-images.githubusercontent.com/360289/76162444-25e73f00-613e-11ea-88d6-0d5a8cee859e.png)
This is how it looks after checking/unchecking.
