### ISSUE TITLE
DropdownButton caret position

### ISSUE THREAD

**Issue by doctorj** [DominoKit/domino-ui#312]
DropdownButton caret icon is not verticaly aligned, it looks like it is closer to bottom than top.

![ddb](https://user-images.githubusercontent.com/360289/69918182-3452fa00-146f-11ea-8ad1-3d6d04804206.png)

**Comment by vegegoku** [comment]
fixed on branch https://github.com/DominoKit/domino-ui/tree/form-fields-revamped
