### ISSUE TITLE
Data table vertical scrollbar not visible

### ISSUE THREAD

**Issue by FrankW76** [DominoKit/domino-ui#316]
**Describe the bug**
When the datatable has a horizontal scrollbar, the vertical scrollbar is only visible when the horizontal scrollbar is scrolled to right.

**To Reproduce**
1. Go to https://demo.dominokit.org/datatable?theme=indigo
2. Open the data table samples
3. Scroll down to basic table - fixed example
4. Make sure your browser is small enough so that a horizontal scrollbar appears
5. You will no longer see the vertical scrollbar. It is only visible when scrolling to the right.

**Expected behavior**
Vertical scrollbar should be visible at all times

**Screenshots**
![image](https://user-images.githubusercontent.com/4488423/71088199-2eaf2100-219e-11ea-86bc-5dbf3101ff47.png)
![image](https://user-images.githubusercontent.com/4488423/71088257-4f777680-219e-11ea-879f-9ceaaf19d180.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 79

**Comment by salashnik** [comment]
i propose simple fix for this. see PR #494 

commit 9fb5463 - previous version of this fix,  but i replace it by solution with less changes (3e6a0f2)
