### ISSUE TITLE
Make TimeBox keyboard editable

### ISSUE THREAD

**Issue by FrankW76** [DominoKit/domino-ui#319]
**Is your feature request related to a problem? Please describe.**
Selecting times using your mouse in a TimePicker is to time consuming when user has to enter a lot of times.

**Describe the solution you'd like**
Apart from selecting the time in the timepicker, the timepicker should also be editable.

This editing should be as smart as possible.
If you type a 3 for example, the text should jump after the : because you can't have a 3x hour.
If you type a 9 after the :, auto modify to 09. Because 9x seconds are not possible

For example you can look at the 3rd box on this page: https://www.igniteui.com/editors/time-picker

**Comment by rjeeb** [comment]
`InputTimeBox` element was added and can be used as follows:

```
InputTimeBox timeBox1 = InputTimeBox.create()
                .setLabel("Clock 12");
InputTimeBox timeBox2 = InputTimeBox.create()
                .setLabel("Clock 24")
                .setClockStyle(ClockStyle._24);
```

The element adds pattern and regex by default to check if the input matches the expected value, if the value is not matched, then the element will be invalid and a message will be shown saying that the input is not matched.

> Note: for the smart input, this feature is incremental and we will work on this feature in the soon future.
