### ISSUE TITLE
FileUpload problem with responseText and response type is arraybuffer

### ISSUE THREAD

**Issue by RaulPampliegaMayoral** [DominoKit/domino-ui#320]
**Describe the bug**
An exception is happening when server is throwing an internal error (500) and the responseType is other than text

**To Reproduce**
1. Create FileUpload
2. Add
````
fileItem.addBeforeUploadHandler((request, form) -> {
                            request.responseType = "arraybuffer";
                        });
3. Upload file
````

**Expected behavior**
Launch errorHandlers from fileItem

**Screenshots**
![imagen](https://user-images.githubusercontent.com/13700946/71092832-4d1a1a00-21a8-11ea-870f-44fe7912c847.png)

![imagen](https://user-images.githubusercontent.com/13700946/71092879-5e632680-21a8-11ea-913a-02086838fff3.png)
FileItem

**Desktop (please complete the following information):**

**Comment by RaulPampliegaMayoral** [comment]
The use case is i need to upload one file and download the file processed

**Comment by RaulPampliegaMayoral** [comment]
@rjeeb Do you think is a proper solution?

**Comment by RaulPampliegaMayoral** [comment]
@rjeeb This issue can be closed because i can set the default message and avoid the exception. Anyway the I think the PR is still valid for when the default text is not set.

Thanks

**Comment by vegegoku** [comment]
fixed with https://github.com/DominoKit/domino-ui/pull/322
