### ISSUE TITLE
Small CSS improvements for tabs

### ISSUE THREAD

**Issue by bykka** [DominoKit/domino-ui#325]
A title of tab is slightly shifted to the right because of
`.nav-tabs>li>a span{line-height:36px;margin-left:5px}`
this margin splits icon and text.
An idea is to put a blank space (`&nbsp;`) between icon and text instead of margin

A similar issue with underline (when tab is selected) - it's two pixels smaller from the right side because of
`.nav-tabs>li>a{margin-right:2px;`

I guess this margin can be simple removed.

Tested at https://demo.dominokit.org/components/tabs?theme=indigo
Last build on : 2019-12-26T09:47:27Z

**Comment by vegegoku** [comment]
@bykka Thank you for the enhancements, i will check them out as soon as possible.

**Comment by vegegoku** [comment]
> @bykka Thank you for the enhancements, i will check them out as soon as possible.

The **ASAP** took too long. :-)
