### ISSUE TITLE
Button does not receive click event when auto validation messages above it are added or removed

### ISSUE THREAD

**Issue by FrankW76** [DominoKit/domino-ui#329]
**Describe the bug**
When a field has autovalidation, it can happen that a click on the form button does not get a clickevent.

**To Reproduce**
This issue can be tested on https://demo.dominokit.org/forms/login-sample?theme=indigo
Take the first sample.

1. Enter a username, but don't enter a password.
2. Click on the login button
3. Now the password field is marked with a 'this field is required message'.
5. Now enter a password, and don't leave the field
6. Click on login
7. The login button does not receive a clickevent.

The reason is that as soon as the password field loses focus (on mouse down on the button), the auto validation kicks in. And the error message disappears. This causes the button to move up. Now, when your mousebutton goes up, your cursor will no longer be on the button, and thus the button will not receive a click.

**Expected behavior**
Not really sure... But the current behavior is not optimal.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chromium
 - Version 79

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vegegoku** [comment]
@FrankW76 we have added `setFixErrorsPosition(boolean fixPosition)` to all fields, can you please confirm if this will fix the issue for you?

**Comment by FrankW76** [comment]
> @FrankW76 we have added `setFixErrorsPosition(boolean fixPosition)` to all fields, can you please confirm if this will fix the issue for you?

For me this is ok
