### ISSUE TITLE
Select seems to ignore .dropdown()

### ISSUE THREAD

**Issue by FrankW76** [DominoKit/domino-ui#331]
**Describe the bug**
When I do a

`Select.create().dropdown()`

I would expect that the popup always appears below the Select, expect when there is really not enough room available. This doesn't seem to be the case. As I have always seems to appear above the Select, except when there is not enough room above.

**To Reproduce**
1. Create Select with a .dropdown()
2. Put in the somewhere in the middle of the screen
3. When you open it, it will open at the top of the Select and not at the bottom. Except when you place the Select in the top of the screen, then it will open below the Select

**Expected behavior**
When .dropdown() is set on a Select, always open below the Select, except when there is not enough room below the Select.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser Chrome

**Comment by FrankW76** [comment]
Please view : https://github.com/DominoKit/domino-ui/pull/333

**Comment by vegegoku** [comment]
The new behavior will by default dropdown unless there is no enough space, or will drop to the selected position as specified by `dropup()`/`dropdown()` methods if there is enough space. but will always drop to where we have more space if the desired position has no enough space.
