### ISSUE TITLE
Select popup positioning when resizing window

### ISSUE THREAD

**Issue by FrankW76** [DominoKit/domino-ui#334]
![ui-demo](https://user-images.githubusercontent.com/4488423/73182895-2c839f00-411a-11ea-9803-e0050c859328.gif)
**Describe the bug**
The popup of a Select doesn't take Window resizing into account

**To Reproduce**
1. Go to https://demo.dominokit.org/forms/form-sample?theme=indigo
2. Open a Select
3. Resize the Window
4. The select stays on it's original position

**Expected behavior**
The popup should remain correctly positioned when looking at the Select box itself

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 79

**Additional context**
For horizontal scrolling this works correct.
Not tested for vertical scrolling.

**Comment by dima99** [comment]
When scrolling vertically, the popup is moving over the app navigation bar, which is also incorrect behavior, i think.

**Comment by vegegoku** [comment]
Fixed for version 2 only
We had revisit our z-index startegy here, so this might require some testing and feedback before we release.
