### ISSUE TITLE
Implement Icon drop down button

### ISSUE THREAD

**Issue by rjeeb** [DominoKit/domino-ui#34]

**Comment by rjeeb** [comment]
Now you can create DropDownButton with an Icon with all button styles.

Example:
`DropdownButton.create(Icons.ALL.more_vert());`
`DropdownButton.createDefault(Icons.ALL.more_vert());`
`DropdownButton.createDanger(Icons.ALL.more_vert());`
`DropdownButton.createInfo(Icons.ALL.more_vert());`
`DropdownButton.createWarning(Icons.ALL.more_vert());`
`DropdownButton.createSuccess(Icons.ALL.more_vert());`
`DropdownButton.createPrimary(Icons.ALL.more_vert());`

Also, in case you create icon dropdown button, then most probably you don't need the caret element so we created two methods to show/hide the caret as follows:

`DropdownButton.create(Icons.ALL.more_vert()).hideCaret();`

Or

`DropdownButton.create(Icons.ALL.more_vert()).showCaret(); \\ this is the default`

What's more, there is a need to create the dropdown button with a background, so we created a method to set it as follows:

`DropdownButton.create(Icons.ALL.more_vert()).setBackground(Color.TRANSPARENT);`

**Comment by schube** [comment]
Very cool, thank you so much!!!
