### ISSUE TITLE
Drag and Drop problem (Edge, Iexplorer 11)

### ISSUE THREAD

**Issue by RaulPampliegaMayoral** [DominoKit/domino-ui#345]
**Describe the bug**
File upload dont work properly when dragging the file inside file upload div.

**To Reproduce**
1. Go to dominoUI demo site, advanced forms
2. Drag a file onto the hand icon
3. File Upload starts flickering and stop working properly

**Expected behavior**

**Screenshots**

![imagen](https://user-images.githubusercontent.com/13700946/74093058-11773e80-4acd-11ea-8f5d-bbacb30de42b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Iexplorer 11, Edge

**Comment by RaulPampliegaMayoral** [comment]
![imagen](https://user-images.githubusercontent.com/13700946/74093690-b3028e00-4ad5-11ea-8884-2769ed666965.png)

**Comment by RaulPampliegaMayoral** [comment]
I have to find a solution for this problem because microsoft explorer is the official navigator used in my company. I just figure out a solution:
````
        private EventTarget dndTarget = null;
        .......................
        formElement.addEventListener("dragover", evt -> {
        	if( dndTarget == null )
        	{
        		dndTarget = evt.currentTarget;
        		addHover();
        	}
        	
        	evt.preventDefault();
        });
        formElement.addEventListener("dragleave", evt -> {
        	if( dndTarget != null && dndTarget == evt.target )
        	{
                removeHover();
                dndTarget = null;
        	}
        	
        	evt.preventDefault();
        });
````

I have tested it and works correctly and could make a pull request.

@vegegoku @rjeeb  What do you think about it?

**Comment by vegegoku** [comment]
I am downloading some VMs to test this.

**Comment by RaulPampliegaMayoral** [comment]
Event chain is not the same with chrome and iexplorer.

Explorer:
![imagen](https://user-images.githubusercontent.com/13700946/74099783-6e9fde00-4b27-11ea-8fee-c7199c82b106.png)

Chrome
![imagen](https://user-images.githubusercontent.com/13700946/74099812-bd4d7800-4b27-11ea-9f3c-5a9e9c665e09.png)

**Comment by vegegoku** [comment]
> I have to find a solution for this problem because microsoft explorer is the official navigator used in my company. I just figure out a solution:
> 
> ```
>         private EventTarget dndTarget = null;
>         .......................
>         formElement.addEventListener("dragover", evt -> {
>         	if( dndTarget == null )
>         	{
>         		dndTarget = evt.currentTarget;
>         		addHover();
>         	}
>         	
>         	evt.preventDefault();
>         });
>         formElement.addEventListener("dragleave", evt -> {
>         	if( dndTarget != null && dndTarget == evt.target )
>         	{
>                 removeHover();
>                 dndTarget = null;
>         	}
>         	
>         	evt.preventDefault();
>         });
> ```
> 
> I have tested it and works correctly
> 
> @vegegoku @rjeeb What do you think about it?

Can you please specify where you added this solution?

**Comment by RaulPampliegaMayoral** [comment]
I modified the FileUpload class.
I think it must to be a better solution, i don't like too much the solution i propose

**Comment by RaulPampliegaMayoral** [comment]
Hi @vegegoku,

I just tried the solution but i'm facing the same mistake. Maybe I explained myself wrong before.
If the drag and drop operation starts out of the upload form all works correctly, but i see our users move the window explorer near the hand icon and drop the file there (drag and drop starts inside upload form).

I hope i explain myself :sweat_smile:

Thanks for your time and effort on this!!

**Comment by RaulPampliegaMayoral** [comment]
@vegegoku I've just made an screencast with my problem:

![20200209_223518](https://user-images.githubusercontent.com/13700946/74110483-45199d80-4b8d-11ea-87c7-c0fdfc2e6158.gif)

If I remove the pointer-events from children elements all work correctly. I know that this css rule prevent click events while drag and drop is active and maybe its not possible remove them.

**Comment by vegegoku** [comment]
@RaulPampliegaMayoral oh i see, i will reopen the issue and work on it again. Thank you for the screencasy

**Comment by RaulPampliegaMayoral** [comment]
@vegegoku thanks for the quickly solution!
I didn't do the pull request removing this lines because this will let pointer events while dragging the file and didn't know if it was acceptable.

Again, thaks for your work and support

**Comment by vegegoku** [comment]
@RaulPampliegaMayoral i was reading in MDN, and according to that i think leaving pointerEvents to default should not affect the FileUplaod component in our case.

**Comment by RaulPampliegaMayoral** [comment]
@vegegoku Agree.
I have a touch screen on my laptop and it would be possible while doing the drag operation touch to show file chooser, but i thinks is a very odd use case which is not worth considering.

**Comment by vegegoku** [comment]
> @vegegoku Agree.
> I have a touch screen on my laptop and it would be possible while doing the drag operation touch to show file chooser, but i thinks is a very odd use case which is not worth considering (and i guess the same is applicable to multitouch devices).

If i find enough time i will dig more into this.

**Comment by RaulPampliegaMayoral** [comment]
@vegegoku with this fix only will remove the the file-upload-hover class when leaving the main area of drag and drop. I have tested and works well for me.
Let me know what do you think...
