### ISSUE TITLE
The label of a RadioGroup isn't displayed

### ISSUE THREAD

**Issue by HMIDeer** [DominoKit/domino-ui#347]
**Describe the bug**
The label of a RadioGroup isn't displayed. When i am setting it using the setLabel method nothing shows up. If i am setting it directy in the RadioGroup.create method it is displayed.

**Comment by vegegoku** [comment]
@HMIDeer Can you please share with some sample code.

i am trying to set the label after creating the Radio and it seems to work as expected.

**Comment by HMIDeer** [comment]
@vegegoku I've refactored my code and it seems to be was my own mistake. If something in this direction comes up again i'll comment here. You can close the Issue :-)
