### ISSUE TITLE
Error setting right addon to null

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#35]
Thank you for the cool new decoration features.
However, removing (by setting it to null) a right addon (did not test with left addon), creates an error:
`emailTextBox.setRightAddon(null);` results in `(TypeError) : Cannot read property 'classList' of null` in Chrome

**Comment by rjeeb** [comment]
Thanks for reporting, this issue is fixed for both right and left addons

**Comment by vegegoku** [comment]
we can add methods to remove left and right add-on to avoid the null hack.

**Comment by vegegoku** [comment]
now you can `.removeLeftAddon()` or `.removeRightAddon()` to remove the addons.

**Comment by schube** [comment]
Unfortunately, removeRightAddOn was removed in one of the latest DominoUI versions.
Please bring it back (of course, also removeLeftAddOn)

**Comment by vegegoku** [comment]
@schube i can methods to remove right/left addons, but they will not be `removeRightAddon()` but instead `removeRightAddOn(some-add-on-element-here)`, i also can provide a `clearRightAddons()` to remove all right added addons

**Comment by schube** [comment]
That you be great! Looking forward to seeing your changes!

**Comment by vegegoku** [comment]
you can now remove an addon by reference or index or you can also remove all addons
