### ISSUE TITLE
Expose the cell info from the datatable

### ISSUE THREAD

**Issue by mamta** [DominoKit/domino-ui#353]
Hi, 
To set focus on a cell of a table, could you expose the cell info from the datatable as discussed in the gitter -
https://gitter.im/DominoKit/domino?at=5e2ec15b1a1c2739e30a6790

Thanks and regards,
Mamta

**Comment by vegegoku** [comment]
I have already implemented this enhancement
https://github.com/DominoKit/domino-ui/blob/e6005916c6ceb2f70c364fb1689855cbe2064eae/domino-ui/src/main/java/org/dominokit/domino/ui/datatable/CellRenderer.java#L23

**Comment by mamta** [comment]
Thanks :)
