### ISSUE TITLE
Create some kind of dictionary which can be easily replaced by a custom one

### ISSUE THREAD

**Issue by G3rmanW1ng** [DominoKit/domino-ui#360]
**Is your feature request related to a problem? Please describe.**
It is hard to set custom strings for each component e.g. for the hard coded required error message

**Describe the solution you'd like**
Replace hard coded strings/messages and create some kind of dictionary which contains all default string/messages.
This dictionary should be replacable to use custom strings

**Comment by vegegoku** [comment]
Labels are now interfaces with default methods that can be replaced with custom implementation from the DominoUIConfig
