### ISSUE TITLE
Introduce a new List component

### ISSUE THREAD

**Issue by vegegoku** [DominoKit/domino-ui#363]
We would love to have some feedback on what to be expected from such a component, as a replacement for the current ListGroup component.

**Comment by mamta** [comment]
Use of ul and li element for listGroup and listItem with select and multiselect - I know you are considering this reuirement already.

**Comment by elnicko** [comment]
Requirement for the selection design of the list item:
- add a method for setting the style/class of a list item when not selected and when selected (I believe currently the second one defaults to 'active'). 
    - Especially interesting for cases, where one wants to remove or replace the default selection check icon, as well as add context dependent selected/deselected styles
    - e.g. if the content is "Warning", I want to the user to see diifferent css classes ala "warning" or "warning-selected"). 
    - This will be also interesting for theming support.

**Comment by elnicko** [comment]
Requirement for the multi-selection

As the end-user I want to have a consistent user experience regarding multi-selection across my desktop and the web apps I'm using, that are written with domino-ui. 

Currently the staOKte is that the multiple selection support is incomplete. 
- Simple click on an item:
    - Clicking on the first item selects it (**OK**).
    - Clicking on the second item selects it (**NotOK**). It should deselect the first item and select the second one.
- Click with a keyboard-modifier (Shift/Ctrl) (all **NotOK**):
    - Pressing Shift and then clicking on another item should add all items between the one before the last clicked and the last clicked to the selection.
    - Pressing Ctrl and then clicking on another item should add the last clicked item to the selection.

**Comment by vegegoku** [comment]
> Requirement for the multi-selection
> 
> As the end-user I want to have a consistent user experience regarding multi-selection across desktop (Windows Explorer, Finder, FileRoller) and web apps written with domino-ui.
> 
> Currently the state is that the multiple selection support is incomplete or inconsistent with expected behavior:
> 
> * Simple click on an item:
>   
>   * Clicking on the first item selects it (**OK**).
>   * Clicking on the second item selects it (**NotOK**). It should deselect the first item and select the second one.
> * Click with a keyboard-modifier (Shift/Ctrl) (all **NotOK**):
>   
>   * Pressing Shift and then clicking on another item should add all items between the one before the last clicked and the last clicked to the selection.
>   * Pressing Ctrl and then clicking on another item should add the last clicked item to the selection.

this is a little bit confusing, the simple click is what implemented in the single select list, if it deselect the currently selected item and then select the new one, then it is not a multi select.

and regarding the ctrl/shift selection, even though it sounds like a convenient, it is actually not, taking the cntrl for example, once you marked the list as multi-select  then you can do this with just a click which serves both desktop and mobile users, while with shift key i can only see it working on the desktop, and wont work on mobiles.

**Comment by HMIDeer** [comment]
> 
> 
> > Requirement for the multi-selection
> > As the end-user I want to have a consistent user experience regarding multi-selection across desktop (Windows Explorer, Finder, FileRoller) and web apps written with domino-ui.
> > Currently the state is that the multiple selection support is incomplete or inconsistent with expected behavior:
> > 
> > * Simple click on an item:
> >   
> >   * Clicking on the first item selects it (**OK**).
> >   * Clicking on the second item selects it (**NotOK**). It should deselect the first item and select the second one.
> > * Click with a keyboard-modifier (Shift/Ctrl) (all **NotOK**):
> >   
> >   * Pressing Shift and then clicking on another item should add all items between the one before the last clicked and the last clicked to the selection.
> >   * Pressing Ctrl and then clicking on another item should add the last clicked item to the selection.
> 
> this is a little bit confusing, the simple click is what implemented in the single select list, if it deselect the currently selected item and then select the new one, then it is not a multi select.
> 
> and regarding the ctrl/shift selection, even though it sounds like a convenient, it is actually not, taking the cntrl for example, once you marked the list as multi-select then you can do this with just a click which serves both desktop and mobile users, while with shift key i can only see it working on the desktop, and wont work on mobiles.

I've seconded that. For me the first secenario is single selection and i am also thinking that crtl/shift selection can be only used on desktop but what about mobile? In that case on multi selection mode the items should be just selected with a single click/touch

**Comment by RaulPampliegaMayoral** [comment]
I think like @HMIDeer and think the multi selection should be with the single/touch event

**Comment by foal** [comment]
I am also for selection with a single/touch event.

**Comment by elnicko** [comment]
I can see how you perceive this @vegegoku &co. And it is definitely valid for mobile.

My comment was meant strictly as add-on functionality to enhance the desktop experience of working with dominu-ui lists and not to change the mobile behavior. 

There are complex productivity oriented web-apps that people/teams use on desktop and not on mobile. In fact these folks actually pay for their software. So far I cannot imagine them sifting through lists of hundreds of entries for hours every day and clicking every one of them separately and using the software with joy :-) So I thought this would be a welcome addition.

**Comment by vegegoku** [comment]
> I can see how you perceive this @vegegoku &co. And it is definitely valid for mobile.
> 
> My comment was meant strictly as add-on functionality to enhance the desktop experience of working with dominu-ui lists and not to change the mobile behavior.
> 
> There are complex productivity oriented web-apps that people/teams use on desktop and not on mobile. In fact these folks actually pay for their software. So far I cannot imagine them sifting through lists of hundreds of entries for hours every day and clicking every one of them separately and using the software with joy :-) So I thought this would be a welcome addition.
> 
> Maybe the behavior can be switched between mobile/desktop?

I made the new ListGroup in a way that allow the user of the library to add such fusnctionality if required, not a built in one , but can be done with the new implementation since the developer has more control over creating items.

Not saying we are not going to implement something like that built in, but might be something for other to contribute with first.

**Comment by elnicko** [comment]
Sure thing. Thank you for making this possible. I'm still evaluating the nalu/domino stack for a bigger project of mine (migrating from GWTP/GMD). I hope I can be of more help later.

**Comment by vegegoku** [comment]
> Sure thing. Thank you for making this possible. I'm still evaluating the nalu/domino stack for a bigger project of mine (migrating from GWTP/GMD). I hope I can be of more help later.

Please feel free to open issues and make requests, sometimes we got busy but we always come back to respond, and we are extremely active in the channel too

**Comment by vegegoku** [comment]
@elnicko added minimal support for selecting items with shift key

**Comment by rdeangelis83** [comment]
A little bit late but I like the behavior from the fabric ui list:
https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/basic

Clicking in the first row will extends the selection clicking somewhere else in the row will change the selection. Also shift and control is supported.  

A like this behavior specially if you also support keyboard navigation.

**Comment by vegegoku** [comment]
@rdeangelis83 i think i can add some enhancements and with that we end up with same behavior
