### ISSUE TITLE
Order of input and label element in form

### ISSUE THREAD

**Issue by mamta** [DominoKit/domino-ui#364]
Hi, in form, we are losing a point in Accessibility testing because of the different order of input and label element. It is expected that label should come before input element in dom. What do you think about it? 
Thanks and Regards

**Comment by TDesjardins** [comment]
Here is the link of the PR: https://github.com/DominoKit/domino-ui/pull/366

**Comment by vegegoku** [comment]
Following the discussion from the PR mentioned in previous comment, checkboxes are fixed now but still needs to work on other fields like Radion.
