### ISSUE TITLE
DateBox: Start week with monday

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#37]
The DateBox/DatePicker starts the week with Sunday, which is common in the US.
In Europe (or at least in German speaking countries), the week starts with Monday.
The locale is already set to "DateTimeFormatInfoImpl_de"

It would be a nice improvement to set the starting day of the week to Sunday/Monday.

Thank you!

**Comment by vegegoku** [comment]
will use css style to caps the letters
