### ISSUE TITLE
ModalDialog is cut off

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#384]
**Describe the bug**
ModalDialog is cut off

**To Reproduce**
Not sure. Some modals work.

**Screenshots**
Broken: https://files.gitter.im/DominoKit/domino/AtVe/image.png
OK: https://files.gitter.im/DominoKit/domino/8pmH/image.png

**Desktop (please complete the following information):**
 - OS: osX
 - Browser Chrome
 - Version 80

**Additional context**
Some modals work.
This modals has checkboxes and links in the body.

This Modal is opened with modal.open() in a Buttons click listener.

```
Button bestellenButton = Button.createDefault("Jetzt bestellen!")
                .setSize(ButtonSize.LARGE)
                .addClickListener(e -> {
                                 acceptTermsDialog.open();
                }
```

**Comment by vegegoku** [comment]
i could not reproduce, if you can upload a sample somewhere that would help

**Comment by vegegoku** [comment]
I pushed some fixes that might be related, can you please confirm if the issue persist?
