### ISSUE TITLE
Provide ref to tr-element of ColumnHeaderFilterPlugin

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#389]
**Is your feature request related to a problem? Please describe.**
I am using a DataTable with HeaderFilters to search for values. Currently, the search fields are always visible. I would like to have "browse/view" mode, where the whole header with filters is invisible and a "find" mode, where the search fields appear. How can I do that? I know, I could store a reference to each filter field and show/hide them with a loop or so. But I would like to have a reference to the "<tr>" element which contains all the search fields and show/hide that at once.

**Describe the solution you'd like**
A method to show/hide the table row with the filter-input-elements would be best.

**Describe alternatives you've considered**
Second best: a ref to the <tr> element of the table, so I can show/hide it myself

**Comment by schube** [comment]
super, thank you!!

**Comment by vegegoku** [comment]
the method in the HeaderFiltersPlugin is `getFiltersRowElement()`
