### ISSUE TITLE
DataTable sort arrows don't display auto sort order

### ISSUE THREAD

**Issue by FrankW76** [DominoKit/domino-ui#395]
**Describe the bug**
When specifying a column for autoSort on a DataGrid, the arrows in the header don't display correctly that this column is being sorted.

**To Reproduce**
1. Create a DataGrid with sorting
2. Specifty an auto-sorting column using setAutoSortBy, setAutoSortDirection and setAutoSort
3. The data in the DataGrid will be correctly sorted. But the sorting indicator in the header will not indicate the sorting order

**Expected behavior**
Sorting indicator should display the sorting order

**Screenshots**
![image](https://user-images.githubusercontent.com/4488423/79196757-ee506e80-7e30-11ea-8b70-ee59f4a3ac9a.png)

**Desktop (please complete the following information):**
 - OS: Windos 10
 - Browser Chrome

**Comment by vegegoku** [comment]
fix on #422
