### ISSUE TITLE
Add support to customize the searching logic of a Select

### ISSUE THREAD

**Issue by eguardiola** [DominoKit/domino-ui#396]
**Describe the solution you'd like**
I want to be able to customize the searching logic of a Select.

**Additional context**
If i search for 'bar foo' i want to find items with bar or foo on any position of the string.

**Comment by doctorj** [comment]
@vegegoku Remember how you resolved issue #285 by introducing a function to be used for filtering? Great solution. Maybe something similar can be applied here?

**Comment by vegegoku** [comment]
you can now implement the feature something like the following example

```java
Select.<String>create("Country")
                                .setSearchFilter((searchText, dropdownAction, caseSensitive) -> ((SelectOption<String>)dropdownAction.getValue()).getValue().contains(searchText))
```

**Comment by eguardiola** [comment]
amazing @vegegoku  thanks!

**Comment by vegegoku** [comment]
notice that the search happen on the drop down menu which a different component used by the select component, this why you get a dropDownAction as an argument to the filter, and from that you get the select option to filter.
