### ISSUE TITLE
DateBox shouldn't be opened on focus by default

### ISSUE THREAD

**Issue by dima99** [DominoKit/domino-ui#397]
**Describe the bug**
If I understand correctly, DateBox shouldn't open modal on focus by default, and should do it only if openOnFocus() called
I think, there is a mistake in DateBox.initDateBox() method:
  ...
  if (!openOnFocus || focused) {
    modal.open();
  }
  ...

should be:

  if (openOnFocus && focused) {
    modal.open();
  }

**Comment by vegegoku** [comment]
@dima99 i think it is working correctly, i have just tested in local demo site and it is working as expected, the condition serve a different purpose related to the popup itself.

**Comment by dima99** [comment]
Ok, I want modal in DateBox to be opened only when I click on calendar icon, not when DateBox gets focus. How can I achieve this?

**Comment by vegegoku** [comment]
yup, this is what i was saying, what you want is the default behavior. if this is not working for you, there should be something causing the issue, having a scenario would help.

**Comment by dima99** [comment]
Oh, I agree, I didn't correctly describe the problem, sorry... 
Everything is fine when DateBox gets focus by pressing TAB key.
But modal opens when DateBox gets focus by clicking on its input element.
So, I want modal to be opened only when I click on calendar icon, not on input element.
And yes, openOnFocus() is working as expected.

**Comment by vegegoku** [comment]
OK, now things are more clear, let me see what i can do about this. :+1:

**Comment by vegegoku** [comment]
Use `dateBox.setOpenOnClick(boolean)` but notice that if the click causes the input field to be focused and the `openOnFocus` is set to true it will still open the modal.
