### ISSUE TITLE
Support to use rounded style on BooleanHeaderFilter and the rest of HeaderFilters

### ISSUE THREAD

**Issue by eguardiola** [DominoKit/domino-ui#402]
I want to use rounded style on BooleanHeaderFilter and others but i can't to access the internal Select

**Comment by vegegoku** [comment]
I have checked and you can access the select of the BooleanHeaderFilter
https://github.com/DominoKit/domino-ui/blob/084ce367af3fcd076bb0e3d1e45039ecce2cf1f3/domino-ui/src/main/java/org/dominokit/domino/ui/datatable/plugins/filter/header/BooleanHeaderFilter.java#L62

**Comment by eguardiola** [comment]
ok, that was  fixed #344 
Close this. I'm not in the last domino version.
Thanks.
