### ISSUE TITLE
TagsInput bugs

### ISSUE THREAD

**Issue by dima99** [DominoKit/domino-ui#404]
**Describe the bug**
If TagsInput has a store of objects to be selected:
1. It is impossible to close its dropdown menu by clicking outside it.
2. When one option of TagsInput's dropdown menu is selected, it is impossible to open it again by clicking on tag text input.

**To Reproduce**
1. Go to https://demo.dominokit.org/forms/advanced-form-elements
2. Scroll down to "TAGS INPUT" card
2. Click on "Friend's name' in 'Friends' TagsInput
3. Click outside of menu that was dropped down. Menu doesn't close, there is no way to close it without selecting one of its options.
4. Select any option of menu, it closes now.
5. Click on "Friend's name' again. Dropdown menu doesn't open.

**Comment by vegegoku** [comment]
The fix includes general TagsInput behaviors

- Clicking outside closes the menu.
- Clicking again inside will open the menu.
- When focused the menu will be by default closed
- Start typing the menu will show up and a filter will be applied based on typed string.
- When focused press `Enter` or `Arrow down` to bring the menu up.
- When focused and menu is visible then press `Tab` the menu will get focus.
- When focused and the menu is closed press `Tab` to go to next field.
- Focus on tag and press `Delete` the tag will be removed.

**Comment by dima99** [comment]
Yes, it is working well now, thanks.
One more little issue: if tagTextInput is focused it is impossible to focus tag (for example for deletion by pressing Delete key), if you click on tag when tagTextInput is focused, focus returns to input.

**Comment by dima99** [comment]
It is very sad, but bugs appeared again...

**Comment by vegegoku** [comment]
> It is very sad, but bugs appeared again...

we didn't change anything related to the suggest box, can you please elaborate more on those bugs?

**Comment by dima99** [comment]
1. Go to https://demo.dominokit.org/forms/advanced-form-elements
2. Scroll down to "TAGS INPUT" card
3. Click on "Friend's name' in 'Friends' TagsInput
4. Scroll up to "SUGGEST BOX" card and try to focus any textbox and you will see

**Comment by vegegoku** [comment]
Ok so this is a different bug, can you please open a new issue.

**Comment by dima99** [comment]
Ok
