### ISSUE TITLE
mvn install error

### ISSUE THREAD

**Issue by zzj1213** [DominoKit/domino-ui#407]
[ERROR] Failed to execute goal on project mdi-icons-processor: 

Could not resolve dependencies for project org.dominokit:mdi-icons-processor:jar:1.0-SNAPSHOT:

 Failed to collect dependencies at org.dominokit.jackson:jackson-apt-processor:jar:1.0-SNAPSHOT -> org.dominokit.jackson:jackson-apt:jar:1.0-SNAPSHOT -> org.gwtproject.i18n:gwt-cldr:jar:1.0-SNAPSHOT: 

Failed to read artifact descriptor for org.gwtproject.i18n:gwt-cldr:jar:1.0-SNAPSHOT: Could not transfer artifact org.gwtproject.i18n:gwt-cldr:pom:1.0-SNAPSHOT from/to ojdbc-repo (${rhq.m2.repo.url.oracle}): 

Cannot access ${rhq.m2.repo.url.oracle} with type default using the available connector factories: BasicRepositoryConnectorFactory: 

Cannot access ${rhq.m2.repo.url.oracle} using the registered transporter factories: WagonTransporterFactory: Unsupported transport protocol -> 

what is the right .m2/setting.xml for domino-ui ?

**Comment by vegegoku** [comment]
Domino-ui pom file includes the repos that you need to build it, so can you please provide more information?
are executing the command on the project root folder? what is ` ${rhq.m2.repo.url.oracle}` repo ur?
are behind a proxy?

**Comment by zzj1213** [comment]
I first remove the **.m2/setting.xml**, then under domino-ui folder, **mvn clean**, then **mvn install**.

--------------mvn install error --------
[ERROR] Failed to execute goal on project mdi-icons-processor: Could not resolve dependencies for project org.dominokit:mdi-icons-processor:jar:1.0-SNAPSHOT: 

Failed to collect dependencies at org.dominokit.jackson:jackson-apt-processor:jar:1.0-SNAPSHOT -> org.dominokit.jackson:jackson-apt:jar:1.0-SNAPSHOT -> org.gwtproject.i18n:gwt-datetimeformat:jar:1.0-SNAPSHOT: 

Failed to read artifact descriptor for org.gwtproject.i18n:gwt-datetimeformat:jar:1.0-SNAPSHOT: Could not transfer artifact org.gwtproject.i18n:gwt-datetimeformat:pom:1.0-SNAPSHOT from/to vertispan-snapshots (https://repo.vertispan.com/gwt-snapshot/): Transfer failed for https://repo.vertispan.com/gwt-snapshot/org/gwtproject/i18n/gwt-datetimeformat/1.0-SNAPSHOT/gwt-datetimeformat-1.0-SNAPSHOT.pom
-------------end of mvn install error ------------

**gwt-datetimeformat-1.0-SNAPSHOT.pom** could not be found on the path: https://repo.vertispan.com/gwt-snapshot/org/gwtproject/i18n/gwt-datetimeformat/1.0-SNAPSHOT/

**Comment by niloc132** [comment]
The server seems to be responding (I manage that server), and in that directory I do see a .pom file for that build (`gwt-datetimeformat-1.0-20200309.133307-5.pom`), which is latest according to the maven-metadata.xml file:
```
      <snapshotVersion>
        <extension>pom</extension>
        <value>1.0-20200309.133307-5</value>
        <updated>20200309133307</updated>
      </snapshotVersion>
```

Perhaps try again with `-U` on your maven command, to force maven to check the server again? Can you share your maven version (something relatively recent I assume), and the full build log (in a pastebin or gist)?

**Comment by zzj1213** [comment]
mvn --version 

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 1.8.0_25, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.2", arch: "x86_64", family: "mac"
------------------------

mvn -U install

https://gist.github.com/zzj1213/e98bc326efe9428592da85dbb18b679b

**Comment by niloc132** [comment]
> sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

You are using an ancient version of Java 8 (released in 2014, if I'm reading this right), which does not recognize the Lets Encrypt project. Update java to anything after Java 8u101 (some time in 2016) and this will work correctly.

**Comment by zzj1213** [comment]
I upgrade jdk to the latest 14 version and the Let's Encrypt issue is gone, Thanks!

-----------------
 mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 14.0.1, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-14.0.1.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.2", arch: "x86_64", family: "mac"
---------------

But ran into new issue:
 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project domino-ui: 
**Fatal error compiling: java.lang.NoClassDefFoundError: javax/annotation/Generated: javax.annotation.Generated**

Only Java 8u101+ working, not working beyond Java 9?

**Comment by vegegoku** [comment]
@zzj1213 the gwt 2.8.2 does not work with jdk 14, you still need a latest jdk 8. or you can just wait a day or 2 till we upgrade to gwt 2.9 which was released today and works on jdk14. :smile:

**Comment by zzj1213** [comment]
Thanks for the help.   Got everything built and running.   Domino-ui is an enterprise grade open source framework.

**Comment by vegegoku** [comment]
@zzj1213 domino-ui is just one library within our set of tools as part of dominokit
you can checkout 

- domino-rest

- domino-history

- domino-jackson

- domino-mvp

- domino-aggregator

and you can always reach us at our [gitter channel ](https://gitter.im/DominoKit/domino)
