### ISSUE TITLE
Expose the DropDownMenu of the AbstractSelect

### ISSUE THREAD

**Issue by HMIDeer** [DominoKit/domino-ui#408]
To modify the entries displayed on open of a selects dropdown it should be possible to add a open handler at the DropDownMenu. Either by exposing the dropdown object or via a method at the select itself. With this approach the filter/deFilter method of the DropdownAction should also be changed to public to give the user the chance to just filter the entries he needs to be displayed in case of "onOpen".

**Comment by vegegoku** [comment]
Sorry for the delay on this, but normally i prefer to understand the usecase, exposing functions that were originally private is always a quick fix and sometimes it is the right fix, but it means that changing those methods later is harder as they become part of the public API, if there is no other solution for this usecase i will be happy to to apply this quick fix

**Comment by HMIDeer** [comment]
I want to hide/display the entries of a select dependent of other values from the data model before or during the select is opened instead of adding/removing the specific entries each time. With the suggested changes the user is able to create the select with each entry and just filters it afterwards if needed.
