### ISSUE TITLE
Any release?

### ISSUE THREAD

**Issue by Beelzenef** [DominoKit/domino-ui#42]
It would be lovely to have a release of domino-ui, before the arrival of GWT 3 😄

**Comment by rjeeb** [comment]
Before releasing domino-ui, it needs some features to be done as you can see in our road map. Currently we're working on DataGrid and we'll start working soon on other features. The great news is that after one week we will be able to work full day on domino-ui and this leads us to increase our progress and hopefully making a release in an appropriate time.
