### ISSUE TITLE
DateBox popup month and year selects appear in wrong position

### ISSUE THREAD

**Issue by FrankW76** [DominoKit/domino-ui#421]
**Describe the bug**
When you click on the month or year dropdown in a DateBox popup. 
The dropdown appears in the topleft corner of the browser. And the datebox closes.

**To Reproduce**
1. Download the latest domino-ui-demo project (https://github.com/DominoKit/domino-ui-demo)
2. Compile and run it
3. Browse (with correct port to) : http://localhost:59988/forms/datepicker
4. At the bottom. Under DATEBOX. Open the third datebox. 
5. Click on the month or year dropdown. 
6. DateBox will close, dropdown list will appear in top left corner

**Expected behavior**
Just open the dropdown at correct position

**Screenshots**
Open this DateBox
![image](https://user-images.githubusercontent.com/4488423/82899554-7c089900-9f5b-11ea-962d-c8d9c175b829.png)

Click on one of the dropdowns
![image](https://user-images.githubusercontent.com/4488423/82899448-4cf22780-9f5b-11ea-8194-3cca9307fe77.png)

Will result in :
![image](https://user-images.githubusercontent.com/4488423/82899505-67c49c00-9f5b-11ea-95c5-5691fa21e2ef.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version latest

**Comment by vegegoku** [comment]
can you reproduce this on the deployed demo site or only when you clone and build the demo locally?

**Comment by FrankW76** [comment]
Only when I clone and build locally

**Comment by FrankW76** [comment]
According to me the sort arrow now points in the wrong direction for autosort ?
In my application arrow is now pointing down when ASC. Then I have to click twice to switch to DESC.

**Comment by vegegoku** [comment]
i think the above comment is supposed to be in another issue?

**Comment by FrankW76** [comment]
Indeed...
Sorry
