### ISSUE TITLE
Css missing classes form button size

### ISSUE THREAD

**Issue by RaulPampliegaMayoral** [DominoKit/domino-ui#423]
**Describe the bug**
I'm trying to resize a circle button with the following code
````
button.setIcon(Icons.ALL.filter_remove_mdi())
                             .circle()
                             .setSize(ButtonSize.XSMALL)
````
but no css size is applying.

**To Reproduce**
1. Go to DominoKit buttons demo page (https://demo.dominokit.org/components/buttons)
2. Change manually css class to button (xs in this case)
3. No css resize is applied

**Expected behavior**
Resize button and icon

**Screenshots**
![imagen](https://user-images.githubusercontent.com/13700946/82995037-5c2cb000-a003-11ea-84aa-28b114228483.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome

**Comment by vegegoku** [comment]
I have checked some really old version of the code and went way back in history and it does not seems like we ever had other than the 2 sizes for the circle buttons.

tried to add some and the results were not good since those other sizes seems to be too small to fit an icon or anything in them.

**Comment by RaulPampliegaMayoral** [comment]
According the screenshot I see that small circle button and normal circle button have the same size. I just only needed the small button size for some filter buttons, so I made my custom size:

![imagen](https://user-images.githubusercontent.com/13700946/83961969-dc230780-a898-11ea-96ff-6c28cf0bb8c5.png)

This buttons have the following css:
````
.btn.circle.sm {
	width: 30px;
	height: 30px;
}
.btn.circle.sm i {
    font-size: 15px;
    position: relative;
    left: 2px;
    top: 1px;
}
````

I dont know if you would be interested in adding this style. If so i could make a PR with the changes.

**Comment by vegegoku** [comment]
Yes sure, and thank you.
