### ISSUE TITLE
MultiSelect: Don't close DropDown after item was selected/unselected

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#427]
The `MultiSelect` element closes the inner DropDown when an item is selected/unselected, which makes it hard to change many items quickly.

There is already an option/method 
`myMultiselect.getOptionsMenu().setCloseOnEscape(closeOnEscape)`

I suggest to implement something similar like
`myMultiselect.getOptionsMenu().setCloseOnItemSelected(boolean)`

**Comment by vegegoku** [comment]
use `setAutoCloseOnSelect`

**Comment by schube** [comment]
Thank you. 
When you select some elements, then click somewhere else so the Dropdown is closed, then you re-open the Dropdown and unselect ALL itesm, an execption occures:
`Uncaught Error: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0`

**Comment by vegegoku** [comment]
I could not reproduce this in the demo site, i would like to see how you create and use the multi select.
but i found that there is some other issues with the multi select that needs work and fix.
so can you please share the a sample code which causes the exception.

**Comment by schube** [comment]
It does not happen any more.
Maybe you fixed it in a recent version of DominoUI or I changed some logic in my app. But I am not aware of such a change and also, the `java.lang.IndexOutOfBoundsException` reported initially came from a DominoUI component, not my code.
Nevertheless, it works now.

Thank you!!
