### ISSUE TITLE
Make TabsPanel::activateTab(Tab) public and also add TabsPanel::activateTab(int tabIndex)

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#43]
I have a TabsPanel with two Tabs. The user activated the second tap and presses a button. Now i want to activate the first tap programmatically. How can I do it? There are no methods currently, right? TabsPanel::activateTab is private
Can you make TabsPanel::activateTab(Tab) public and also add a TabsPanel::activateTab(int tabIndex) method?

**Comment by vegegoku** [comment]
you can now activate a tab using one of the following :

- call `someTab.activate()`
- call `someTabsPanel.activateTab(someTab)`
- call someTabPanel.activateTab(someTabIndex)`
