### ISSUE TITLE
KeyboardEvents crashes in combination with browser auto-suggest

### ISSUE THREAD

**Issue by gkresic** [DominoKit/domino-ui#436]
Create `org.dominokit.domino.ui.forms.TextBox` and listen for Enter on it:

```
TextBox input = TextBox.create();
KeyboardEvents.listenOn(input).onEnter(this::onEnter);
```

However, if such input is filled by picking value that browser suggests (click on input -> browser shows popup -> arrow down -> enter), exception is thrown in `KeyboardEvents.java:33` because `keyboardEvent.key` is undefined. If that matters, `keyboardEvent.type` is `"keydown"` at the same moment.

Browser is Chrome 84 on Linux 64bit.

If simply ignoring event without key attribute is proper way to handle this, I may provide this simple pull request.

**Comment by vegegoku** [comment]
I think we had this issue discussed on gitter sometime ago, it is a bug in chrome. So yah a PR is welcome, as long as the original functionality remains working.
