### ISSUE TITLE
Specialize every use of elemento.IsElement

### ISSUE THREAD

**Issue by gkresic** [DominoKit/domino-ui#439]
`elemento.IsElement` vars/params misses specialization on many places:

* `BaseDominoElement.appendChild/insertFirst/setContent`
* `Animation.create`
* `Card.appendDescriptionChild`
* `Chip.setRemoveIcon`
* ...

I'm not classifying this as bug, but it generates warnings and conflicts with `@Override` annotation in derived classes.

If simply substituting `IsElement` with `IsElement<?>` would suffice, I can submit pull request as I encounter non-specialized usage.

**Comment by vegegoku** [comment]
PRs are always welcome.
