### ISSUE TITLE
TagsInput, convert text to Tag on focus lost.

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#440]
My users enter some text into a `TagsInput` and sometimes they forget to press ENTER, so the text is not converted to a TAG and `myTagInput.addChangeHandler(evt -> GWT.log(evt))` just provides an empty array.

Please add an option which converts the text entered to a `Tag` on focus lost.

**Comment by vegegoku** [comment]
now losing focus while there is a value typed already will behave as if you pressed enter.
