### ISSUE TITLE
SelectOption elements doesnt build correct

### ISSUE THREAD

**Issue by masterdany88** [DominoKit/domino-ui#443]
Using such code:
```
        Select<TimeZoneDto> timeZonew = Select.create("TEST");
        for (TimeZoneDto t : timeZones) {
            timeZonew.appendChild(SelectOption.create("q", "E"));
        }
        card.appendChild(timeZonew);
```
```
public class TimeZoneDto {
    private String displayName;
    private String systemName;
}
```

I am getting such result:
![image](https://user-images.githubusercontent.com/1161910/86462810-8b35f000-bd2c-11ea-895f-5db37221ce9e.png)
Select option doesnt go to select input, but are below.

**Comment by vegegoku** [comment]
Use :

`timeZonew.appendChild(SelectOption.<TimeZoneDto>create("q", "E"));`
