### ISSUE TITLE
DropDownMenu::isOpened() returns the wrong value

### ISSUE THREAD

**Issue by NickGaens** [DominoKit/domino-ui#444]
When clicking outside a `DropDownMenu`, the following piece of code comes into play: `document.addEventListener(EventType.click.getName(), evt -> DropDownMenu.closeAllMenus());`.

If I use `DropDownMenu::isOpened()` some time later, it (wrongfully) returns `true`.

However, whenever I call `DropDownMenu::close()` manually, `DropDownMenu::isOpened()` returns `false` afterwards, which is correct.

**Comment by NickGaens** [comment]
For the sake of completeness: `DropDownMenu::isOpened()` also (wrongfully) returns `true` after having selected an auto-closable action.

**Comment by vegegoku** [comment]
@NickGaens i could not reproduce this issue, can you please prepare a small sample that reproduce this issue.

**Comment by vegegoku** [comment]
@NickGaens reminder

**Comment by NickGaens** [comment]
I can no longer reproduce this in my project so it seems. Can be closed.
