### ISSUE TITLE
FileUpload: Chromium uses DropEffect.MOVE per default

### ISSUE THREAD

**Issue by Corburn84** [DominoKit/domino-ui#446]
Using drag&drop on the fileupload, Chromium (Chrome & Edge Chromium) is using DropEffect.MOVE.
Dropping an e-mail from Outlook to the fileupload, Outlook deletes the mail because of that setting.

Please overwrite the DropEffect to DropEffect.COPY (which is the default in other browsers btw.).

For further details, please find the following links:
Bug report at Google:  [https://bugs.chromium.org/p/chromium/issues/detail?id=1066975](https://bugs.chromium.org/p/chromium/issues/detail?id=1066975)
Discussion on microsoft side: [https://answers.microsoft.com/en-us/msoffice/forum/all/drag-and-drop-works-however-deletes-email-can-we/865f60c3-7980-4465-8a19-4d60b0ae5aba?rtAction=1575537469456&page=2](https://answers.microsoft.com/en-us/msoffice/forum/all/drag-and-drop-works-however-deletes-email-can-we/865f60c3-7980-4465-8a19-4d60b0ae5aba?rtAction=1575537469456&page=2)

**Comment by vegegoku** [comment]
@Corburn84 i have checked and i didnt find any place where we set the DropEffect manually, so it is supposed to be on the default.
anyway i added some API to set the default and to allow the override of the DropEffect but this will require more testing from your side.

will wait for your feedback before closing this issue.

**Comment by Corburn84** [comment]
@vegegoku Thank you for the fast response and help. :)

That is correct, you don't set the DropEffect, so the browser's default is being used. Normally, this should be fine.
Other browsers use "DropEffect.COPY", while Chrome uses "DropEffect.MOVE", which leads to the bad behaviour when droppping Mails from Outlook. To get rid of that we need to replace the DropEffect. We solved it in our project by adding an eventlistener, where we change the DropEffect:

`fileUp.addEventListener(EventType.drop,evt -> ((DragEvent) evt).dataTransfer.dropEffect = DataTransfer.DropEffect.COPY.toString().toLowerCase());
`
`fileUp.addEventListener(EventType.dragover, evt -> ((DragEvent) evt).dataTransfer.dropEffect = DataTransfer.DropEffect.COPY.toString().toLowerCase());
`

An override should be fine. Otherwise, everyone using the fileupload will end up changing the DropEffect, because I don't think that anyone wants the mails to be deleted.

Test from my side is ok for sure 👍 I'm looking forward to test 1.0 asap :)

**Comment by vegegoku** [comment]
@Corburn84 ok then, i am going to bring one last change, in which i will keep it to the browser default but allow users to override it.
you can use the `fileUpload.setDropEffect(DropEffect dropEffect)` to change the drop effect instead of the long events code above.

**Comment by Corburn84** [comment]
Perfect! Thank you very much :)
