### ISSUE TITLE
Allow to enter date into DateBox with keyboard.

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#45]
I have a signup form where the user enters email, firstname, lastname and birthdate.
He can input all values via keyboard and jump to the next field with the TAB-key.
When the focus is set on the DateBox, nothing happens.

It would be cool, if the user could enter a date. (Please consider the allowed dat format (Datebox::setPattern).
and/or (I am not sure about that)
open the DatePicker, so the user knows how to enter a valid date.

At the moment, nothing happens and the user thinks there is a bug.

**Comment by vegegoku** [comment]
Thank you for the feedback,
@rjeeb is working on the field masking feature, once he is done we will implement a datebox with pattern masking, but for now we can make the date picker appears when the date field take the focus, pressing Enter key will also the picker. i will fix the focus issue as soon as possible.

**Comment by vegegoku** [comment]
I have added the openOnFocus method that will allow the dialog to show up when the field is focused, if the dialog is closed the focus will go back to the date box, to reopen the dialog press enter or space, tab will move to next field.
this is not the final solution , i will leave this open until the field masking is ready and apply a better fix.

**Comment by rjeeb** [comment]
Now the user can enter the text that matches the pattern, and after exit the field, the value will be formatted according to the pattern and if it is invalid the field will be invalidated with an error message which can be set using the following method:
`dateBox.setInvalidFormatMessage("Error message"); // default "Invalid date format"`

**Comment by schube** [comment]
Very good!
