### ISSUE TITLE
Can't set a placeholder on a SuggestBox

### ISSUE THREAD

**Issue by FrankW76** [DominoKit/domino-ui#453]
**Describe the bug**
`SuggestBox.create("Your friends", localstore).setPlaceholder("This is the placeholder));`

Above code will not result in a placeholder. The suggestbox is just empty. It seems to sometimes work when giving focus to the box, or execute the setPlaceHolder after a timeout of 2 seconds or more...

**To Reproduce**
1. SuggestBox.create("Your friends", localstore).setPlaceholder("This is the placeholder));

**Expected behavior**
See a placeholder

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Latest version

**Comment by rjeeb** [comment]
@FrankW76 This is related to this issue https://github.com/DominoKit/domino-ui/issues/459, once it got fixed then this will be fixed.

As a workaround, you can set the label floating to true so the placeholder will be shown:
`suggestBox.setFloating(true).setPlaceholder("test placeholder");`

**Comment by vegegoku** [comment]
fixed with #459
