### ISSUE TITLE
RadioGroup shows Required-Indicator and there is no way to remove it

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#455]
`RadioGroup` with `.setRequired(true, "Please enter your name")` gets a "*" (asterisk) to the label.

This is especially annoying, when the label is set to "", then you just have a "*" and then the radio buttons.

Also, this was not the case with older releases of DominoUI.

Please make an option to enable/disable this required indicator.

**Comment by vegegoku** [comment]
use `setShowRequiredIndicator(boolean)` to disable the indicator for the RadioGroup

**Comment by schube** [comment]
Thank you, works as expected!
