### ISSUE TITLE
[MessageDialog] Add functionality to change BackGroundcolor to the Okbutton

### ISSUE THREAD

**Issue by JaviTio** [DominoKit/domino-ui#457]
Class: MessageDialog

New Feature
It would nice to have the possibility to change the backgroundcolor/style of the default Okbutton that have MessageDialog

**Describe the solution you'd like**
Have a method to set the backgroud color of the button, like is the setOkButtonText method.

**Comment by vegegoku** [comment]
you can now use one of the static create method that takes an okButtonProvider to provide your own ok button, or use the getter to apply some style to the provided button.
