### ISSUE TITLE
RadioGroup ignores setValue in readOnly-mode

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#458]
**Describe the bug**
I have a form with `TextBox`es and `RadioGroup`s.
All elements are set to read-only (`.setReadOnly(true)`)

Now, when a TextBox t gets a value set programmatically with `.setValue("new Value")`, the value is displayed and can also be read with `.getValue()`

But on a RadioGroup r, when the value set programmatically with `.setValue("new Value")`, the value is NOT displayed and `.getValue()`returns `null`.

Workaround:
1. Set RadioGroup to readOnly(false)
2. Set value on RadioGroup
3. Set RadioGroup to readOnly(true)

**Expected behavior**
Same as with textboxes

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version latest

**Comment by vegegoku** [comment]
@schube thank you for reporting, i checking the code i dont see a check for readonly when set the field value, the bug could somewhere else, can you please share how you initialize the RadioGroup and its Radios and how you then set the value.
thanks
