### ISSUE TITLE
Allow custom icons for MessageDialog

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#46]
I love the simplicity of MessageDialog but there is one feature missing: Setting a custom icon (and an according color I guess).

Currently, we only have 3 icons:
    private HTMLElement successIcon = MessageDialog.createMessageIcon(Icons.ALL.done().asElement());
    private HTMLElement errorIcon = MessageDialog.createMessageIcon(Icons.ALL.clear().asElement());
    private HTMLElement warningIcon = MessageDialog.createMessageIcon(Icons.ALL.error().asElement());

In my current usecase I need a "download Icon" for example. (Download starts in background, I want to display an info to the user).

**Comment by vegegoku** [comment]
Those Icons are not just icons, they are Icons with predefined styles and animation, so changing to your own defined icon means you will need to define the icon, the styles and the animation which is already doable with the custom header content feature as shown in the example in the demo page
something like this :
```java
HTMLElement heart = Icons.ALL.favorite().asElement();
heart.classList.add(Styles.font_72, Styles.m_b_15, Color.RED.getStyle());

MessageDialog customHeaderContent = MessageDialog.createMessage("Custom header",
        "You can customize the header content",
        () -> Notification.create("Dialog closed").show())
        .onOpen(() -> Animation.create(heart)
                .duration(400)
                .infinite()
                .transition(Transition.PULSE)
                .animate())
        .appendHeaderContent(heart);
```

here it is up to you if you want the animation part or not , like this:

```java
HTMLElement heart = Icons.ALL.favorite().asElement();
heart.classList.add(Styles.font_72, Styles.m_b_15, Color.RED.getStyle());

MessageDialog customHeaderContent = MessageDialog.createMessage("Custom header",
        "You can customize the header content",
        () -> Notification.create("Dialog closed").show())
        .appendHeaderContent(heart);
```
 my point is that the header is fully customized.

**Comment by schube** [comment]
Thank you! I agree, you can customize it heavily. Also, it is not just replacing the icon because of the animations. But I would like to choose the success/error/warning method and reuse everything like colors/animations but still use a custom icon. If I need more customization, I would use the customHeaderContent.

Maybe an overloaded method for success/error/warning:
MessageDialog.createMessage("title", "text").success(MY_CUSTOM_ICON);

**Comment by vegegoku** [comment]
as long as you say you only need to change the icon but keep the styles and every thing else then i can implement something like that.

**Comment by schube** [comment]
it would be a nice feature I think

**Comment by vegegoku** [comment]
Done
use `.success(someIcon)` or `.error(someIcon)` or `.warning(someIcon)`

the icon will change, but the animation will remain the same. since it is a complex animation to be overloaded and a better choice would be to use custom header content.
