### ISSUE TITLE
Infinite notifications?

### ISSUE THREAD

**Issue by gkresic** [DominoKit/domino-ui#461]
Currently, all notifications have finite duration which makes then unsuitable for informing user of some on-going background process (for example long request).

Providing some large value (e.g. `Integer.MAX_VALUE`) as duration doesn't work because there is no way to programatically close such notifications after background process finishes (`Notification.close()` is private). Also, such notifications should NOT have close button visible (or at least that button visibility should be configurable).

So I propose following changes:

1. treat negative duration values as "infinite duration"
1. make close() method public
1. allow close button to be hidden

Also, I've noticed that closing animation doesn't use `close()` method, but instead just removes element from DOM. Didn't test, but it looks like that would break notification stack if notifications with different durations are used.

If proposed changes look good to maintainers, I can provide a pull request.

**Comment by vegegoku** [comment]
Interesting.! the change for the duration would be done in the animation class not notification class.

> treat negative duration values as "infinite duration"

I would prefer to add something like infinite, or at least `autoClose(boolean)`, this will decide to wither the close will be called by the end of the in transition and out transition delay or should wait for the close to be manually clicked/called.

> make close() method public

we could do that, but we will introduce an internal private close method that will have the same code from the current close method, the public close will call the private close to prevent users from overriding the close behavior.
the private close now should be the one triggering the close animation in case of manual close.

> allow the close button to be hidden

we could introduce something to do so, or even expose the close button.

it looks simple but I think it needs some testing and a deeper lock especially the animation and the close behavior.

**Comment by gkresic** [comment]
> > make close() method public
> 
> we could do that, but we will introduce an internal private close method that will have the same code from the current close method, the public close will call the private close to prevent users from overriding the close behavior.
> the private close now should be the one triggering the close animation in case of manual close.

Why not simply declare `close()` as `public` **and** `final`?

**Comment by FrankW76** [comment]
+1 for these enhancements

**Comment by vegegoku** [comment]
> > > make close() method public
> > 
> > 
> > we could do that, but we will introduce an internal private close method that will have the same code from the current close method, the public close will call the private close to prevent users from overriding the close behavior.
> > the private close now should be the one triggering the close animation in case of manual close.
> 
> Why not simply declare `close()` as `public` **and** `final`?

I was thinking about the user wants to override it to add some checks or something like, but now thinking about it he could remove the call to super.
maybe as you suggest but also add something to handle close events. not sure if we need it notification though.
