### ISSUE TITLE
UI Content placeholders/loaders

### ISSUE THREAD

**Issue by masterdany88** [DominoKit/domino-ui#472]
Did You consider to implement such ui locker/loader placeholder:
https://medium.com/@praveencnaik/content-placeholder-the-new-design-trend-for-audience-involvement-e2ab533d7304

**Comment by vegegoku** [comment]
Isnt this something you implement in the app not in the UI library, since the in the app you know what content you have while the lib have no way to tell what are you implementing?!

**Comment by masterdany88** [comment]
Agree with You, but some generic could be served from library. Like f.e. for card.

**Comment by vegegoku** [comment]
a card by itself is a placeholder, it is just an empty div.
