### ISSUE TITLE
Domino ui components in  UiTemplate

### ISSUE THREAD

**Issue by jhonToni** [DominoKit/domino-ui#479]
Can I use domino ui components in `com.google.gwt.uibinder.client.UiTemplate` template file ?

example of template file: 

```
<ui:UiBinder
        xmlns:ui="urn:ui:com.google.gwt.uibinder"
        xmlns:g="urn:import:com.google.gwt.user.client.ui"
xmlns:d="urn:import:org.dominokit.domino.ui.forms">


    <g:DecoratorPanel>


        <d:TextBox ui:field="myTextBox"></d:TextBox>

    </g:DecoratorPanel>
</ui:UiBinder>
```

**Comment by vegegoku** [comment]
UiBinders only works for widgets, domino-ui components are not widgets, they are elements. so no you can't use them.
one of our future plans is to implement a templating engine for domino-ui.
