### ISSUE TITLE
Stepper: description in step header does not wrap

### ISSUE THREAD

**Issue by NickGaens** [DominoKit/domino-ui#481]
**Describe the bug**
When setting a somewhat longer string as the description of a Step, no wrapping occurs. Instead, 

**To Reproduce**
This issue can be easily reproduced on the demo-page of DominoUI ([link](https://demo.dominokit.org/forms/steppers)).
Edit the `data-step-label` of the first step of the horizontal Stepper example as such: `data-step-label="Contact name step Contact name step Contact name step`. Note the text is simply cut off if the Stepper is rendered horizontally.

**Expected behavior**
I would expect the description to word-wrap and become multiline e.g.

**Additional context**
I tried to manipulate the `after` pseudo-element of the `div` with class `step-title` to no avail.

**Comment by vegegoku** [comment]
I am already mid-way implementing the new stepper component :wink:

**Comment by NickGaens** [comment]
Did I already mention the fact that that is simply awesome?

**Comment by vegegoku** [comment]
Steppers have been redesigned
