### ISSUE TITLE
ClassCastException upon using the browsers autocomplete.

### ISSUE THREAD

**Issue by NickGaens** [DominoKit/domino-ui#484]
**Describe the bug**
The stacktrace:

```
Uncaught Error: java.lang.ClassCastException

at fWh_g$.SJf_g$ [as createError_0_g$] (Throwable.java:120)
at fWh_g$.aKf_g$ [as initializeBackingError_0_g$] (Throwable.java:112)
at fWh_g$.LJf_g$ (Throwable.java:66)
at fWh_g$.pKf_g$ (Exception.java:29)
at fWh_g$.xKf_g$ (RuntimeException.java:29)
at new fWh_g$ (ClassCastException.java:27)
at Gsj_g$ (InternalPreconditions.java:154)
at Ssj_g$ (InternalPreconditions.java:138)
at Rsj_g$ (InternalPreconditions.java:133)
at VTg_g$ (Cast.java:155)
at X7p_g$.Wrk_g$ [as lambda$0_269_g$] (BaseModal.java:124)
at o6p_g$.p6p_g$ [as handleEvent] (BaseModal.java:123)
```

This occurs when having a TextBox and the browser suggests a string using a small dropdown menu in which the user can simply click on an item.

![Screen Shot 2020-10-08 at 4 47 20 PM](https://user-images.githubusercontent.com/467715/95474931-f7f10400-0985-11eb-9e0d-a707469856d1.png)

**Comment by timmattison** [comment]
I ran into something similar with another GWT project. The browser was returning a JavaScriptObject to GWT which wasn't a Java.Lang.String, it was a UInt8Array (from memory, name may be slightly different). My fix was to check if the object was a String and if not simply call .toString() to convert it.

**Comment by niloc132** [comment]
`Uint8Array` is indeed a browser type, but it can't really be used as a string - and calling toString() on a typed array like that probably won't do what you want:
```
> Uint16Array.of(1, 2, 3).toString()
< "1,2,3"
```

Probably instead you want to do `new String(stringBytes, Charset.forName("UTF-8"))` on your typedarray to actually turn those bytes as unicode into a string, or something like that. Note that you will either need to `Js.uncheckedCast` the typed array, or copy the bytes into a real java `byte[]`.

Broadly speaking, it doesn't make sense to add a typecheck and toString any time you get a value from JS that should be a string yet isn't - either the JsInterop describing the JS api is wrong, or the JS is wrong and should return a proper string in a case like yours @timmattison. That said, seeing the example would help to make a better guess as to what is wrong.

**Comment by timmattison** [comment]
Mine was definitely a special case where .toString() worked although I won't say that it made sense. 😄 

I was getting an array of integers that looked suspiciously like the ASCII character values I was expecting. So I tried it, it worked, and that's where I left it for now. I'll go back and see if there's a better way to fix mine.

**Comment by FrankHossfeld** [comment]
macOS 10.15.7, Chrome: Version 86.0.4240.198 (Offizieller Build) (x86_64)

Sometimes, during auto completion, a CCE happened, caused by: 
`KeyboardEvent keyboardEvent = (KeyboardEvent)Js.cast(evt);`in class `BaseModal`
