### ISSUE TITLE
fileItem.readableFileSize() -> wrong file size calculation

### ISSUE THREAD

**Issue by Corburn84** [DominoKit/domino-ui#488]
Method fileItem.readableFileSize() calculates with 1000 Bytes (threshold) instead of 1024 Bytes per kilobyte, leading to wrong file sizes in the file item box.

E.g.: a file with 25MB is being displayed 26.4MB.

**Comment by vegegoku** [comment]
@Corburn84 would you like to make a PR to fix this?
