### ISSUE TITLE
Set specific step at a stepper to active

### ISSUE THREAD

**Issue by HMIDeer** [DominoKit/domino-ui#493]
Add a possbility to set a specific step active without stepping through all previous one. A use case would be to skip a step in case in a previous one is something selected which makes it unnecessary to show it to the user anymore

**Comment by vegegoku** [comment]
use either `stepper.activateStep(int index)` or `stepper.activateStep(Step step)` , the step should not be disabled, if you need to jump to a disabled step it should be enabled first.

or use `step.setActive()` which will behave the same.
