### ISSUE TITLE
Provide GroupingPlugin with public accessors to collapse or expand all groups

### ISSUE THREAD

**Issue by FrankW76** [DominoKit/domino-ui#497]
**Is your feature request related to a problem? Please describe.**
I would like to add a button to my DataTable : Expand all groups / Collapse all groups.
This is however not possible since I cannot access the needed things in the GroupingPlugin

**Describe the solution you'd like**
Have public access to all current groups.
Or have public expandAll / collapseAll methods.

So when I create a button I can access these methods

**Comment by FrankW76** [comment]
Please take a look at PR https://github.com/DominoKit/domino-ui/pull/498

**Comment by vegegoku** [comment]
fixed in #498
