### ISSUE TITLE
Select.setValue(null) call doesn't set value to null

### ISSUE THREAD

**Issue by dima99** [DominoKit/domino-ui#504]
**To Reproduce**
Select<String> select = Select.create();
select.appendChild(SelectOption.create("value1", "value1"));
select.appendChild(SelectOption.create("value2", "value2"));
select.setValue("value1");
assert select.getValue().equals("value1");
select.setValue(null);
assert select.getValue() == null;

**Comment by vegegoku** [comment]
Here is the possible fix
```
 @Override
    public Select<T> setValue(T value, boolean silent) {
        for (SelectOption<T> option : getOptions()) {
            if (Objects.equals(option.getValue(), value)) {
                select(option, silent);
            }
        }
        return this;
    }
```
in the setValue method, should check if the value is null, then we call `clear`

same for MultiSelect

```
@Override
    public MultiSelect<T> setValue(List<T> value, boolean silent) {
        if (isNull(value))
            return this;
        for (SelectOption<T> option : getOptions()) {
            if (value.contains(option.getValue())) {
                select(option, silent);
            }
        }
        return this;
    }
```
before return from the null check should call `clear`

this might be a good issue for a PR

**Comment by dima99** [comment]
> in the setValue method, should check if the value is null, then we call `clear`

not just clear(), don't forget about changeHandlers

**Comment by dima99** [comment]
Something like that:
```
@Override
public Select<T> setValue(T value, boolean silent) {
    for (SelectOption<T> option : getOptions()) {
        if (Objects.equals(option.getValue(), value)) {
            select(option, silent);
        }
    }
    if (value == null) {
        clear();
        if (!silent)
            changeHandlers.forEach(c -> c.onValueChanged(getValue()));
    }    
return this;
}
```

**Comment by vegegoku** [comment]
But i would say that clear should call the change handlers :thinking:

**Comment by dima99** [comment]
Yes, you're right.
But if you call change handlers from clear(), then you'll run into "Maximum call stack size exceeded" because of that code in AbstractSelect constructor:
```
addChangeHandler(value -> {
    if (isNull(value)) {
        clear();
    }
});

```

**Comment by vegegoku** [comment]
> Yes, you're right.
> But if you call change handlers from clear(), then you'll run into "Maximum call stack size exceeded" because of that code in AbstractSelect constructor:
> 
> ```
> addChangeHandler(value -> {
>     if (isNull(value)) {
>         clear();
>     }
> });
> ```

this should be removed

**Comment by vegegoku** [comment]
fixed.
