### ISSUE TITLE
Stepper should allow to circumvent the forced vertical direction on small devices

### ISSUE THREAD

**Issue by NickGaens** [DominoKit/domino-ui#506]
**Is your feature request related to a problem? Please describe.**
A Stepper with a horizontal direction will force itself to switch to the vertical direction when viewed on a 'small' device, e.g. a portrait iPad.

**Describe the solution you'd like**
I would like to optionally prevent the described behavior from happening. My suggestion would be to rename the `forceVertical` flag of Stepper to something like `forceVerticalDirectionForSmall` (defaulting to `true`) and exposing it via a setter. The `MediaQuery` listeners (on lines 147 and 152) should be revised accordingly then, though.

**Comment by vegegoku** [comment]
adding the css class `dui-responsive` to the stepper or stepper tracker should now make it switch to vertical layout for small screens.
