### ISSUE TITLE
Longbox.setValue ignores "disableFormatting"

### ISSUE THREAD

**Issue by Corburn84** [DominoKit/domino-ui#507]

**Comment by Corburn84** [comment]
Longbox test = LongBox.create().setPlaceholder("Test with 12 digits")
						   .disableFormatting()
						   .setMaxLength(12);
test.setValue(12345L);  --> "12,345" instead of "12345"

**Comment by doctorj** [comment]
Actually NumberBox (in this case LongBox) does not ignore disableFormating. You can compare different behaviour by typing number into empty box and then switching focus. Value in box with disableFormating does not change.

Probelm here is this line:
`test.setValue(12345L);`

setValue method calls `doSetValue(E value)`, here it is:
```
@Override
protected void doSetValue(E value) {
    if (nonNull(value)) {
        getInputElement().element().value = getNumberFormat().format(value);
    } else {
        getInputElement().element().value = "";
    }
}
```
As you can see getNumberFormat is called:
```
protected NumberFormat getNumberFormat() {
    if (nonNull(getPattern())) {
        return NumberFormat.getFormat(getPattern());
    } else {
        return NumberFormat.getDecimalFormat();
    }
}
```
And if you don't have pattern set you'll end up with decimal format.

So, you should call setPattern() on your LongBox, for example:
```
LongBox test = LongBox.create().setPlaceholder("Test with 12 digits")
				.setPattern("#")
				.disableFormatting()
				.setMaxLength(12);
test.setValue(12345L);
```
