### ISSUE TITLE
Progress bar / unreadable text

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#509]
**Describe the bug**
When a progress bar has a text and a value of 0 (or any other small value, for example value of 10 and maxValue is 10000), the text is not readable, because it is white on a light gray background.

**Expected behavior**
 Firstly, the default should be a readable text.
 Secondly, I would wish for a method to set the text color

**Screenshots**
![](https://user-content.gitter-static.net/76144483bec55e36519fc6fec3985596630e0332/68747470733a2f2f66696c65732e6769747465722e696d2f3561386232336364643733343038636534663864653236342f435253452f7468756d622f42696c6473636869726d666f746f2d323032302d31312d32352d756d2d31362e35382e35372e706e67 "Screenshot")

Thank you!!

**Comment by mrabusalah** [comment]
Hello friend, is it ok for you to have a way to change the font color ?

**Comment by mrabusalah** [comment]
Hello friend, 
you can use this way to change the font color of ProgressBar 

```
Progress.create()
        .appendChild(ProgressBar
                .create(500)
                .showText()
                .success()
                .setValue(3)
                .styler(style -> style.setColor("black"))
        )
)
```
