### ISSUE TITLE
Errors while trying to add Domino-UI support to an existing GWT-2.9.0 project

### ISSUE THREAD

**Issue by Oberonc** [DominoKit/domino-ui#512]
I have a project I wrote in java using GWT-2.9.0 and am interested in using domino-ui as it's UI framework.
After I added support for domino-ui as described in [getting started](https://github.com/DominoKit/domino-ui/wiki/Getting-started) and attempting to compile the code I get the following errors:
   _Ignored 3 units with compilation errors in first pass.
Compile with -strict or with -logLevel set to TRACE or DEBUG to see all errors.
   [ERROR] Errors in 'org/dominokit/domino/ui/utils/BodyObserver.java'
      [ERROR] Line 27: The constructor MutationObserver((MutationRecord[] records, MutationObserver observer) -> {}) is undefined
      [ERROR] Line 28: Lambda expression's parameter records is expected to be of type JsArray<MutationRecord>
   Tracing compile failure path for type 'org.dominokit.domino.ui.utils.BodyObserver'
      [ERROR] Errors in 'org/dominokit/domino/ui/utils/BodyObserver.java'
         [ERROR] Line 27: The constructor MutationObserver((MutationRecord[] records, MutationObserver observer) -> {}) is undefined
         [ERROR] Line 28: Lambda expression's parameter records is expected to be of type JsArray<MutationRecord>
   [ERROR] Hint: Your source appears not to live underneath a subpackage called 'client'; no problem, but you'll need to use the <source> directive in your module to make it accessible_

Here is how to reproduce it:
1. Start new GWT-2.9 project with maven support and sample code
2. Add the 2 repositories described in getting started method 2 to the pom.xml file.
3. Add the 2 dependencies described in getting started method 4 to the pom.xml file
4. Try to compile the code using the GWT compiler (see errors I get above)

**Comment by vegegoku** [comment]
This is because domino-ui is still using gwt-2.8.2 and elemental2-RC1 release.

We are currently working on releasing dominokit libs with support for latest GWT-2.9 and latest elemental2 and migration to all new gwt modules.

**Comment by Oberonc** [comment]
This is the only issue I encounter when using GWT-2.9.0.
Is there a roadmap on how fast/when will this migration happen ?

**Comment by vegegoku** [comment]
domino-ui 1.0.0-RC1 is now in maven central and works with gwt 2.9.0 and elemental2 1.1.0
