### ISSUE TITLE
Expose DropDownMenu and provide an example using it

### ISSUE THREAD

**Issue by Oberonc** [DominoKit/domino-ui#513]
One of the things I feel is missing in your framework is an example on how to use a drop down menu (popup menu).
Suppose I capture a right click ("contextmenu") event and want to provide my own menu instead of the browser default.
How do I do that ?

**Comment by vegegoku** [comment]
```java
        HeaderAction headerAction=HeaderAction.create(Icons.ALL.more_vert()
                .clickable());
        DropDownMenu dropDownMenu=DropDownMenu.create(headerAction)
                .setPosition(DropDownPosition.BOTTOM)
                .addAction(DropdownAction.create("Action 1").addSelectionHandler(value -> Notification.createInfo(value).show()))
                .addAction(DropdownAction.create("Action 2").addSelectionHandler(value -> Notification.createInfo(value).show()));


        headerAction.addClickListener(evt -> {
            dropDownMenu.open();
            evt.stopPropagation();
        });
```

this is an example to build one for a card header action. you can do the same for context menu.

**Comment by vegegoku** [comment]
You will need to use https://developer.mozilla.org/en-US/docs/Web/API/Element/contextmenu_event
you prevent the default event and open the dropdown menu, and you can specify a custom dropdown position to open the dropdown menu on mouse location
