### ISSUE TITLE
Missing a simple "Hello world" example

### ISSUE THREAD

**Issue by Oberonc** [DominoKit/domino-ui#514]
After looking through the 2 sample apps and the demo app I conclude:
1. They are all using some other frameworks as well
2. Overly complicated and not a good place to start learning how to use DominoUi framework.

Can you add a simple standalone example of using the framework ?
Maybe a single .java file which contains a GWT entry code and some code in the onModuleLoad() method.

Thanks

**Comment by vegegoku** [comment]
You can get that exactly by creating a project using the [domino-cli](https://github.com/DominoKit/domino-cli) 
after installing the cli tool issue the following command to generate such sample:

`dominokit gen app -t basic -n [name] -g [groupId]` just change the name and the group id as you need.
