### ISSUE TITLE
Slider showing current value

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#517]
Currently, the slider does not show its value initially. Currently, you have to select a "SLIDERS WITH THUMB" as in https://demo.dominokit.org/components/sliders?theme=indigo ,drag the slider a little bit and then you can see the value.

Or you have to add a value field manually to show the value.

It would be nice, if there was a default/built-in way to show the value.

Maybe like like the 3rd slider in https://www.jqueryscript.net/images/Simple-Nice-jQuery-Value-Range-Slider-Plugin-Fresh-Slider.jpg

Or like https://d2d3qesrx8xj6s.cloudfront.net/img/screenshots/9fa0e32fdbdd6197737230ebf5c4f443728471f5.jpeg

Or like https://reactnativeelements.com/img/slider_screenshot.png

There are many ways and you know best which fits to the overall design of DominoUI. But I am asking for an easy way to show the value.

Thank you!

**Comment by vegegoku** [comment]
> Hello my friend, I hope everything is okay, and you are well.
> Is it fit for you to get the value by hovering the slider ?

What about adding a flag to make the bubble always visible?!

**Comment by mrabusalah** [comment]
Nice idea, we can add it as an optional attribute by default will be disabled, when set it true it will be appeared.
What is your opinion ?

**Comment by schube** [comment]
> What about adding a flag to make the bubble always visible?!

Yes!!!

**Comment by vegegoku** [comment]
Add a config to keep the thumb always visible.
