### ISSUE TITLE
LocalSuggestBoxStore crashes SuggestBox.getValue()

### ISSUE THREAD

**Issue by gkresic** [DominoKit/domino-ui#521]
**Describe the bug**
`LocalSuggestBoxStore` overrides `missingValueProvider` and `missingEntryProvider` from `SuggestBoxStore` with null-unsafe implementation which doesn't work well with `SuggestBox`.

**To Reproduce**
```
LocalSuggestBoxStore<String> store = new LocalSuggestBoxStore<>();
SuggestBox<String> emailInput = new SuggestBox<>("email", "E-mail", store);
emailInput.getValue();
```

**Expected behavior**
Should not crash :)
Either:
1. `LocalSuggestBoxStore.setMissingValueProvider` and `LocalSuggestBoxStore.setMissingEntryProvider` should ban setting `null` values (like `setSuggestionFilter` does)
1. their getters should propagate to `SuggestBoxStore`'s getters (which provides sane default) in case of `null` (best case, IMHO, but I'm not sure if support for explicit `null`s is required somewhere else)
1. `SuggestBox` should gracefully handle `null` values in that attributes

**Comment by vegegoku** [comment]
I am going to implement the second suggested solution since it solves the issue and still give the user the ability to reset to default behavior in case the values were set before with none null values :+1:

**Comment by vegegoku** [comment]
The super is an interface with the default method..so this won't work, we will have to apply some default behavior in the LocalSuugestStore
