### ISSUE TITLE
Add option to hide Card's logo container

### ISSUE THREAD

**Issue by gkresic** [DominoKit/domino-ui#524]
Currently, Card's `logoContainer` adds 10px margin from the left edge even if logo is unset. To be worse, that container doesn't have any distinguishing CSS class so it's not easy to hide.

Two things could be beneficial here:

1. modify `setHeaderLogo(Node node)` to hide `logoContainer` if `node` is `null`

1. append unique CSS class name to that container so it can be styled properly by subclasses

**Comment by vegegoku** [comment]
The header logo will be hidden by default unless it is set, a null logo will clear the container and hide it, also added a method to remove the header logo as an option to clear and hide the container instead of using null.
