### ISSUE TITLE
Button in form should be sent by pressing ENTER-key

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#54]
It would be cool, if a button could be declared as a "default submit" button, and it's action is executed, if the user presses ENTER while in a form field.

Think of a login form with username/password. The user enters the credentials and hits ENTER.

Currently, one has to add a listener to each form field to achieve the same behavior, which leads to boilerplate code.

**Comment by vegegoku** [comment]
We have provided a field grouping option to make validation of form field a lot easier, and with the addition of the editors support, this can now be easily achieved by adding a keypress listener on the fields that can cause submit, other wise hitting tab and focus on the button then hit enter also works.
