### ISSUE TITLE
select value not visible due to padding-right: 40px on .select-value

### ISSUE THREAD

**Issue by happyhua** [DominoKit/domino-ui#549]
Is it necessary to have padding-right: 40px on .select-value?

It makes the most selected value in a filter not visible, see screenshots below.

![image](https://user-images.githubusercontent.com/23259391/120920625-0aac0c00-c6c0-11eb-95ce-07d1ba29b7f9.png)
![image](https://user-images.githubusercontent.com/23259391/120920659-2fa07f00-c6c0-11eb-889b-22a331d48439.png)

**Comment by vegegoku** [comment]
this will be fixed with the a future RC release. it is already addressed and fixed locally
