### ISSUE TITLE
Select: Typ letters to jump to correct option

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#56]
I have a `org.dominokit.domino.ui.forms.Select` with 50 entries/options.
This is a rather long list and if I want to select an entry which starts with "Z" like "Zulu", i have to scroll like forever. 
I would like to open the options list, hit "Z" on the keyboard and the list jumps to the first entry, starting with "Z".

(just like a normal HTML select).

PS: I really want a Select, i do not want a text field with autocomplete or something else.

**Comment by rjeeb** [comment]
Search feature has been added to the select and it can be configured as follows:

- By default any select is searchable unless it is configured to be non-searchable
`select.setSearchable(false);`
- A method to clear the search value was added
`select.clearSearch();`
- If no results were found with a specific search value, no search results element will be shown with the following text `No results found "[your search value]"`. However, this element can be configured by using the following method:
`select.setNoSearchResultsElement([your html element]);`

**Comment by schube** [comment]
Very cool, thank you!
