### ISSUE TITLE
DateBox: setOpenOnClick(false) & setPickerStyle(PickerStyle.POPUP) does not work  as expected

### ISSUE THREAD

**Issue by FrankHossfeld** [DominoKit/domino-ui#561]
**Describe the bug**
Setting up a DateBox using

```

DateBox.create("myDateBox",
                            new Date(),
                            new DateTimeFormatInfoImpl_de_DE())
               .setPickerStyle(DateBox.PickerStyle.POPOVER)
               .setOpenOnClick(false); 
```

does not work as expected. This configuration should only open the picker in case the date icon is clicked - similar to the behavior in case the PickerStyle is MODAL. But the popover is also shown in case the field gets focus or a click inside the field (not the icon) occurs.

**Expected behavior**
the picker only opens in case the date icon is clicked.

**Additional context**
I'll provide a PR. :-)

**Comment by vegegoku** [comment]
Sorry It seems I forget to add my comments here.

The current behavior is the correct behavior for this feature, if we want to make it only open popup on icon click maybe we need to implement a new flag or find a way to override the current one.

**Comment by FrankHossfeld** [comment]
Using PickerStlye.MODAL and setting openOnClick to true changes the behavior of the date box in this way, that the picker  only opens if hte date icon gets clicked. 

Using PrickerStyle.POPUP, openOnClick has no effect. Or, do I miss something.

**Comment by vegegoku** [comment]
Ok so we have inconsistent behavior. right?

**Comment by FrankHossfeld** [comment]
Yes, I think so. The popup is always created in this way:

```
Popover.createPicker(this, this.datePicker)
                .position(this.popupPosition)
                .styler(style -> style.add(DatePickerStyles.PICKER_POPOVER));
```

It does not respect the value of openOnClick. Setting openOnClick to **false** opens the popup when the field gets focused or you click inside the field. In case openOnClick is **false** we need to create the popup i this way:

```
Popover.createPicker(this.calendarIcon, this.datePicker)
                .position(this.popupPosition)
                .styler(style -> style.add(DatePickerStyles.PICKER_POPOVER));
```

So, the popup appears only if the calendar icon is clicked. And, we need to make sure, to recreate the popup in case **setOpenOnCick** is called to respect the new value.

**Comment by FrankHossfeld** [comment]
@vegegoku Think, we can close this one ... PR is merged.
