### ISSUE TITLE
Mouse cursor on Thumbnail

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#57]
my mouse cursor becomes a "hand" symbol, if I hover over a "Thumbnail". There is no link and no listener, I am just displaying an image, so this is confusing for the user who thinks, there is something to click on.

    final Thumbnail banner = Thumbnail.create().setContent(Elements.img("./assets/app-banner.jpg").asElement());

**Comment by vegegoku** [comment]
The image element now is wrapped into a div element instead of anchor element, this will remove the pointer cursor, user of the lib can add an anchor element as a wrapper for the content and the pointer cursor will be used then.
