### ISSUE TITLE
Bottom border and not corner radius of the card background image

### ISSUE THREAD

**Issue by bykka** [DominoKit/domino-ui#594]
Inline styles to fix for better background image presentation
Delete bottom border CSS style and add border-radius 

Here is a video with the issue

https://user-images.githubusercontent.com/489997/137594569-d687d8b5-17f3-47d8-b564-ec07ecbfadac.mp4

**Comment by vegegoku** [comment]
Is this only related to the demo site or you have issues in the components, the styles in the video are for the demo site only.

**Comment by vegegoku** [comment]
user should be able to customize this .
