### ISSUE TITLE
Using the DatePickers navigate before buttons could lead to an inconsistent year select field

### ISSUE THREAD

**Issue by HAC-jh** [DominoKit/domino-ui#597]
**Describe the bug**
Inconsistency between the different fields which displays the year at the DatePicker 

**To Reproduce**
Choose 1971 at the select and use the before button to choose a date e.g. december 1970. The date will be displayed correctly at the header and also the calendar but the select itself is now empty.

**Expected behavior**
All fields which are available should display the same year.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/74547492/138401041-c1cb5b65-beca-480a-976c-d8efd28e2cb6.png)
![grafik](https://user-images.githubusercontent.com/74547492/138401076-d2b5b73e-92d9-4086-aefa-c7625664bd73.png)

**Additional context**
Next year the problem will appear with 1972 since the min/max year is calculated using the actual date - 50

**Comment by vegegoku** [comment]
calendars re-implemented in version 2.x.x
