### ISSUE TITLE
There is no possibility to define a min/max year at a DateHeaderFilter

### ISSUE THREAD

**Issue by HAC-jh** [DominoKit/domino-ui#598]
**Describe the bug**
The DatePicker has the possibility to define a min/max year. This possibily is also passed to the DateBox but not to the DateHeaderFilter.

**Expected behavior**
A new constructor/create method for the DateHeaderFilter to define a min/max year

**Comment by vegegoku** [comment]
added a  new method `withDateBox` to access the datebox
