### ISSUE TITLE
Make it possible to customize multi-selection datatable checkboxes

### ISSUE THREAD

**Issue by masterdany88** [DominoKit/domino-ui#604]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to set up checkbox style for Data table in Selection Plugin. Only Color is settable.

**Describe the solution you'd like**
Constructor parameter on Selection plugin that will take checkbox style

**Describe alternatives you've considered**
Maybe passing whole widget like checkbox to Plugin will also be good solution

**Comment by vegegoku** [comment]
now the user have control over creating the checkbox using `setCheckBoxCreator(Supplier<CheckBox> checkBoxCreator)`
