### ISSUE TITLE
Add support for Indeterminate checkbox state

### ISSUE THREAD

**Issue by masterdany88** [DominoKit/domino-ui#605]
**Is your feature request related to a problem? Please describe.**
Check box can be Indeterminate. But it should be if it takes in charge more slave check-boxes (like in list or table), see https://material.angular.io/components/checkbox/examples

**Comment by masterdany88** [comment]
https://kstatic.googleusercontent.com/files/4d0c3af7eb1dd111d3584349c3feb60047de36b1fc413e53b71d9c4175358447ccc39fb5382c91832b7a1fbeb69bd7b71f52e6407dce2abedc8c2f7fdb1e284f

**Comment by masterdany88** [comment]
![Screenshot_20211108_123415](https://user-images.githubusercontent.com/1161910/140735049-b9600e8c-b7fb-44ca-a33e-1be8f878a637.png)

**Comment by vegegoku** [comment]
implemented in version 2.x.x
