### ISSUE TITLE
Use a different directory path for CSS

### ISSUE THREAD

**Issue by jhickman** [DominoKit/domino-ui#612]
Importing domino CSS through the URL `"{module-short-name}/css/domino-ui.css"` is fine, but domino-ui.css contains imports that use fairly common filenames such as "colors.css" and "style.css".    It's not uncommon for applications to already have a "css" path for `<public>` resources, so there's a high chance that the domino files may interfere with (or visa versa) the application css files in the compiled output. 

For the CSS file location, I would suggest changing the `<public>` directory from "css" to something namespaced to domino ui, such as "domino-css", and update the host page `<link>` tags to: 
```xml
<link type="text/css" rel="stylesheet" href="{module-short-name}/domino-css/domino-ui.css"> 
<link type="text/css" rel="stylesheet" href="{module-short-name}/domino-css/themes/all-themes.css">
```

The obvious alternative is to make sure the application either uses a different `<public>` directory for CSS, or guarantee there are no filename conflicts.  However, if an application uses multiple 3rd party libraries that all use the same path, that will be a much harder issue to alleviate.

**Comment by vegegoku** [comment]
@jhickman I am thinking of adding a prefix to those imported file names, like `domino-ui-*` this way we wont break existing applications?

e.g `colors.css` become `domino-ui-colors.css`

**Comment by jhickman** [comment]
I think that would satisfy any potential conflicts
