### ISSUE TITLE
add the ability to start loader with a timeout to stop the effect

### ISSUE THREAD

**Issue by vegegoku** [DominoKit/domino-ui#615]
add a method `start(timeout)` if the timeout is reached before we manually call `stop` the loader will automatically stop.

**Comment by salashnik** [comment]
Hi! You add small bug in commit

```java
      if (timeOutTimer.isRunning()) {
        timeOutTimer.cancel();
      }```

no null check here :( must be somtjing like 

```java
      if (nonNull(timeOutTimer) && timeOutTimer.isRunning()) {
        timeOutTimer.cancel();
      }```

**Comment by salashnik** [comment]
i create small PR #616

**Comment by vegegoku** [comment]
Yes I didnt test it, the idea poped up in my mind and just added it while working on a different project. My mistake . Thank you for the PR . Should be merged now

**Comment by rjeeb** [comment]
Implemented in https://github.com/DominoKit/domino-ui/commit/e86fa36a3f09bc0fa7bfe4834a85d76d9be021b9
