### ISSUE TITLE
Booklist tutorial producing unexpected results

### ISSUE THREAD

**Issue by gdiscord** [DominoKit/domino-ui#628]
**Describe the bug**
Followed the domino bookstore tutorial and having an issue when running the application to display the list of books

**To Reproduce**
1. Follow instructions here right to the end: https://github.com/DominoKit/domino-mvp/wiki/Book-list

**Expected behavior**
According to the very last point of the instructions, Once all 3 servers are running refresh the browser and click on books, a book list should show up.

**Screenshots**
Only the headings of the book list table are shown instead of a book list, and there is a runtime java error thrown when checking the chrome dev tools.
(https://github.com/gdiscord/screenshot/blob/main/domino_booklist_error.png)

**Additional context**
project available on GitHub here: https://github.com/gdiscord/dominobookstore

**Comment by vegegoku** [comment]
As per the instructions in the Wiki you need to add `@Path("books")` to your service class here 
https://github.com/gdiscord/dominobookstore/blob/a809f2ca2b2ca413303e2da06c8acd2e8fd0fa66/library/library-shared/src/main/java/org/dominokit/samples/library/shared/services/BooksService.java#L10

which is missing in your case 

Please check the instructions again, the code is fully posted there, check the step that says

```
Edit the BooksService interface to add a methods that represent the CRUD operations for book resource
```
and the service code below it.

**Comment by gdiscord** [comment]
You're right, though the code was copy/pasted, for some reason the @Path("/books") had been removed by the compilation process? Not sure how that was possible, but thanks for resolving the issue.
