### ISSUE TITLE
for label is set to null if the label is not set using set label instead of factory/constructor

### ISSUE THREAD

**Issue by vegegoku** [DominoKit/domino-ui#644]
If field is created with a constructor without a label, then later we call setLabel, then the label for attribute will have null value as the field input element id is not set yet.

**Comment by mamta** [comment]
Hi, I updated domino-ui to 1.0.0-RC12, but still getting null as shown in the screenshot.

https://github.com/mamta/MyTestProject/blob/main/MyTestProject-client/src/main/java/com/example/mytestproject/client/ui/application/content/screen01/Screen01Component.java#L3
![01](https://user-images.githubusercontent.com/419394/161750952-14be5e56-d61d-4fdb-b0b5-6f13db6dcad5.JPG)
6

**Comment by vegegoku** [comment]
The project does not load the static resources for me...
![image](https://user-images.githubusercontent.com/5379625/161855652-e38a8143-73ba-403b-b082-4d3b16f2af9b.png)

**Comment by vegegoku** [comment]
I reproduced the issue with my own project.
