### ISSUE TITLE
Modal Window: Content exceeds modal window if content is scrollable

### ISSUE THREAD

**Issue by bschmelcher** [DominoKit/domino-ui#646]
**Describe the bug**
When opening a modal window with scrollable content (content is exceeding the browser window size), the content is exceeding the modal window. So the content is shown on the underlying main frame of the web application without the background of the modal window.

**To Reproduce**
1. Go to 'https://demo.dominokit.org/components/modals'
2. Click on 'Modal Window' in the Card with title 'Window'
3. Enable fullscreen of modal window
4. Make browser window small (height of browser window should be less than the displayed content, so the modal window is scrollable)
5. Scroll down
6. See error, content is exceeing the modal window and is now shown without background on the underlying main frame.

**Expected behavior**
When scrolling in a modal window, the height of it should be based on the actual content instead of browser window size. So when you scroll down inside the modal window, the content should still be visible inside it, not exceeding it.

**Screenshots**
![image](https://user-images.githubusercontent.com/102970139/161554486-b94b7511-b2be-46dc-9fdd-9c8a3d7fd66d.png)

**Desktop:**
 - OS: Windows
 - Browser Chrome
 - Version  99.0.4844.84

**Comment by vegegoku** [comment]
as a workaround for this until it is fixed try to add the following to your own application style sheet : 

```css
.modal .modal-content .modal-body {
    max-height: calc(100% - 49px);
    overflow-y: auto;
}
```

**Comment by bschmelcher** [comment]
Hi @vegegoku, thanks for your quick reply.

I changed the css to also take the footer into account, because if there are buttons in the footer of the modal window, your proposed solution lead to two scrollbars (one for the main content of modal window, one because the footer is outside of that):

![image](https://user-images.githubusercontent.com/102970139/162211620-10eb6d36-ce2e-4b69-a72f-d52ceaf2e8ff.png)

Here is the updated code:

```
.modal .modal-content {   
    max-height: 100%;   
    overflow-y: auto;   
}
```

Also, I noticed if a modal window is not in fullscreen and the screen is too small, it gets cut off and there's no scrollbar:
![image](https://user-images.githubusercontent.com/102970139/162217069-0defed99-2ef3-48b9-ad4e-5b440908b2fa.png)

Here is the sample code I used:
```
Layout layout = Layout.create("ModalWindow").show(ColorScheme.BLUE);
        layout.getContentPanel().appendChild(
        Card.create("Window", "Use window to create modals that can be maximized and move.")
            .appendChild(
                Row.create()
                    .appendChild(
                        Column.span3()
                            .appendChild(
                                Button.createDefault("MODAL WINDOW")
                                    .addClickListener(
                                        evt -> {
                                          new Window("Modal window")
                                              .setFixed()
                                              .setDraggable(false)
                                              .setSize(IsModalDialog.ModalSize.SMALL)
                                              .setModal(true)
                                              .apply(
                                                  self ->
                                                      self.appendChild(
                                                              Paragraph.create(SAMPLE_CONTENT))
                                                          .appendChild(
                                                              Paragraph.create(SAMPLE_CONTENT)))
                                              .appendFooterChild(Button.createPrimary("FooterButton"))
                                              .open();
                                        }))))
            .element());
```

**Comment by vegegoku** [comment]
I think the actual and ultimate solution is to implement the dialogs/windows with flex box instead of the current implementation, and make the body grow, make sure to hide the header and footer when they are empty and give the dialog/window a max-height equals to the view-port height. as for the double scroll bars when the window is maximized we can implement something like what  we do when a modal is dialog is open and hide the scrollbars for the main container/body.
