### ISSUE TITLE
Make Enter a valid input for Numberboxes

### ISSUE THREAD

**Issue by bschmelcher** [DominoKit/domino-ui#647]
**Is your feature request related to a problem? Please describe.**
Enter key is not a valid input for Numberboxes. 
Since we don't want to validate input everytime it changes, we do that using a changehandler which is added to textboxes, numberboxes, etc.
This changehandler is normally executed if focus is lost or Enter key is pressed. Since enter is not a valid input for numberboxes, the changehandler is not called when enter is pressed which is kind of confusing for users, so they always have to focus out of the element to get validation.
Since this is working for all other implementations of AbstractValueBox except TextArea, this seems to be inconsistent.

**Describe the solution you'd like**
Enter key should be a valid input for numberboxes to trigger the changeHandler.

**Comment by vegegoku** [comment]
@bschmelcher Thank you for reporting, we had an issue related to this today in one of our application on an older version of domino-ui. so lets summaries this like the following : 

- We can trigger validation based on tow events either `input` or `change` , for input it means to trigger the change handlers every time we press any key while the field is focused, while `change` means to trigger the change handlers only when the field lost focus. 

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event

The thing we can do here is to add a key listener instead of `input` or `change` for Enter key only to do the same as the `change` event which calls the change handlers. that is a proposed solution that I need to test first.

- Validation will triggered automatically on fields when ever they lose focus, but that totally controllable without the need to use change handlers and is very flexible using FieldsGrouping, for example : 

Assume we have field1, field2, field3

 ```java
 import elemental2.dom.EventListener;
import org.dominokit.domino.ui.forms.DoubleBox;
import org.dominokit.domino.ui.forms.FieldsGrouping;
import org.dominokit.domino.ui.forms.IntegerBox;
import org.dominokit.domino.ui.forms.TextBox;
import org.dominokit.domino.ui.forms.validations.ValidationResult;
import org.dominokit.domino.ui.keyboard.KeyboardEvents;

public class SampleForm {

    private TextBox field1;
    private IntegerBox field2;
    private DoubleBox field3;

    private FieldsGrouping fieldsGrouping = FieldsGrouping.create();

    public SampleForm() {

        field1 = TextBox.create("field1")
                .groupBy(fieldsGrouping);

        field2 = IntegerBox.create("field2")
                .groupBy(fieldsGrouping);

        field3 = DoubleBox.create("field3")
                .groupBy(fieldsGrouping);

        fieldsGrouping
                .addValidator(() -> {
                    //do some validation and return some validation result
                    return ValidationResult.valid();
                })
                .setAutoValidation(false);

        EventListener onEnterListener = evt -> {
            if (fieldsGrouping.validate().isValid()) {
                //do something on enter only if all fields are valid
            }
        };
        KeyboardEvents.listenOn(field1.getInputElement())
                .onEnter(onEnterListener);
        KeyboardEvents.listenOn(field2.getInputElement())
                .onEnter(onEnterListener);
        KeyboardEvents.listenOn(field3.getInputElement())
                .onEnter(onEnterListener);

    }
}
```

You can use this as workaround if you cant wait until we do the fix.

**Comment by vegegoku** [comment]
One more thing about this, regarding change handlers they are supposed to be called when the value is changed, currently this is handled completely by the browser which can detect a value change when the field lost focus and firing a `change` event, when the value is not changed the event wont be fired and so the change handlers wont be called.

Now knowing that handling `input` or keyboard events to call the change handlers means either that we call the change handler always even if the value did not actually change or to manually track old/new value and trigger the change handlers based on that, the 2nd option is not actually a good one and requires tons of work and handling of edge cases, for example to make sure change handlers are not being called twice.

so a better option is follow the example code above and maybe we can provide an easier API to write such code.

**Comment by bschmelcher** [comment]
yes, the workaround is working for me.

Maybe it would also make sense for all input elements (except TextArea and the like) to just call unfocus() on the element or go to the next element (like Tab does) when Enter is pressed which would trigger the normal browser change event. Also, I think that would make sense in general because the usual behavior of web applications is like that.

Maybe that could still be controlled via an API so if some use cases require the current behavior, that would also be possible.

**Comment by vegegoku** [comment]
Notice that there is no built-in way to perform such transition from focused element to the next element using javascript as this is not supported by the browser, a behavior like this might require some tracking of the form fields and their order. so this needs a lot of thoughts.

Meanwhile I am trying to make the above construct be much simpler and shorter to implement, so far with the new API you can do it like this
```java
import elemental2.dom.EventListener;
import org.dominokit.domino.ui.forms.CheckBox;
import org.dominokit.domino.ui.forms.FieldsGrouping;
import org.dominokit.domino.ui.forms.IntegerBox;
import org.dominokit.domino.ui.forms.TextArea;
import org.dominokit.domino.ui.forms.TextBox;
import org.dominokit.domino.ui.forms.validations.ValidationResult;
import org.dominokit.domino.ui.keyboard.KeyboardEvents;

public class SampleForm {

    private TextBox textBox;
    private IntegerBox integerBox;
    private CheckBox checkBox;

    private TextArea textArea;

    private FieldsGrouping fieldsGrouping = FieldsGrouping.create();

    public SampleForm() {

        textBox = TextBox.create("field1");
        integerBox = IntegerBox.create("field2");
        checkBox = CheckBox.create("field3");
        textArea = TextArea.create("field4");

        fieldsGrouping.group(textBox, integerBox, checkBox, textArea)
                .setAutoValidation(false)
                .addValidator(ValidationResult::valid)
                .setReadOnly(true);

        EventListener onEnterListener = evt -> {
            if (fieldsGrouping.validate().isValid()) {
                //do something on enter only if all fields are valid
            }
        };
        KeyboardEvents.listenOnKeyDown(textBox, integerBox,checkBox, textArea)
                .onEnter(onEnterListener);
    }
}
```

**Comment by vegegoku** [comment]
I have been searching and it seems all the solutions I could find are either complex or does not seems to support some edge cases, an idea to implement this in a simple way is to limit this to elements grouped by a fieldGrouping and has this implemented in the fieldsGrouping as it already knows what form elements it is grouping.

Still needs to handle cases of same field grouped by more than one group.

**Comment by bschmelcher** [comment]
Just to clarify again,
my use case is actually that we want to trigger the validation of single elements if Enter is pressed, independent from if they are in a FieldsGrouping or not.
So if a user changes the value of a single field and presses Enter, the validation is done and we update the CSS of that field based on the validation result. We do that using a changehandler (and with the workaround also with an EventListener on Enterkey) for that single element.

In the updated code, the validation is done for all elements in fieldsGrouping when Enter is pressed, that still would be a nice improvement but that doesn't really affect my main use case because I would just have to validate the current focused element if focus is lost or Enter is pressed.


Also to add to this:
> Notice that there is no built-in way to perform such transition from focused element to the next element using javascript as this is not supported by the browser, a behavior like this might require some tracking of the form fields and their order. so this needs a lot of thoughts

I just tried to add a keylistener on enter which does a unfocus. That triggers the validation because focus is lost and there would be no need to keep track of the elements, the focus is just lost and users would have to klick in the next field. That would maybe not be an as elegant implementation as the Tab behavior but would still solve my issue if we could just set this via an API.

**Comment by vegegoku** [comment]
I have just pushed a commit that has several enhancements: 

- DominoUIConfig now has an option to enable/disable moving the focus to the next form field when in a form field the user press enter key, this will disabled by default and can be enabled/disabled globally from DominoUIConfig
```java
DominoUIConfig.INSTANCE.setFocusNextFieldOnEnter(true);
```
And there should be no need to manually add the enter key listener nor to use the workaround above

- A simpler API introduced in both `KeyBoardEvents` and `FieldsGrouping` to make easier to build something like the code above 

```java
import org.dominokit.domino.ui.forms.CheckBox;
import org.dominokit.domino.ui.forms.FieldsGrouping;
import org.dominokit.domino.ui.forms.IntegerBox;
import org.dominokit.domino.ui.forms.TextArea;
import org.dominokit.domino.ui.forms.TextBox;
import org.dominokit.domino.ui.forms.validations.ValidationResult;

public class SampleForm {

    private TextBox textBox;
    private IntegerBox integerBox;
    private CheckBox checkBox;

    private TextArea textArea;

    private FieldsGrouping fieldsGrouping = FieldsGrouping.create();

    public SampleForm() {

        textBox = TextBox.create("field1");
        integerBox = IntegerBox.create("field2");
        checkBox = CheckBox.create("field3");
        textArea = TextArea.create("field4");

        fieldsGrouping.group(textBox, integerBox, checkBox, textArea)
                .setAutoValidation(false)
                .addValidator(ValidationResult::valid)
                .setReadOnly(true)
                .onKeyPress(keyboardEvents -> keyboardEvents
                        .onEnter(evt -> {
                            if (fieldsGrouping.validate().isValid()) {
                                //do something on enter only if all fields are valid
                            }
                        }));

    }
}
```

- `KeyboardsEvents` now allow adding listeners to several elements at once.

@bschmelcher This should land in the HEAD-SNAPSHOT more testing from your side is highly appreciated.
