### ISSUE TITLE
MultiSelect : space between elements is too large

### ISSUE THREAD

**Issue by nchamouard** [DominoKit/domino-ui#649]
Hello,

Spacing between lines is perfect with the "single" Select : 
![Capture d’écran 2022-04-25 à 14 44 46](https://user-images.githubusercontent.com/38036161/165091680-224969bc-8e30-47e9-bc68-72f14f71594c.png)
 
But the MultiSelect provides an exaggerated space not consistent with the other elements
![Capture d’écran 2022-04-25 à 14 45 06](https://user-images.githubusercontent.com/38036161/165091983-724169e4-9e1c-4c4a-a11d-565ce5fd239a.png)

**Comment by vegegoku** [comment]
The fix will be applied to version 2.x.x

A new class added `CheckOption` that extends the SelectOption and adds a checkbox.

a new css class have been added `dui-minified` this can be attached to a checkbox to remove all of its decorations and minimize its size to be used with other components and control spacing.
