### ISSUE TITLE
Current RowIndex should be accessible inside CheckBox supplier

### ISSUE THREAD

**Issue by bschmelcher** [DominoKit/domino-ui#650]
**Is your feature request related to a problem? Please describe.**
We are trying to add HTML attributes to the checkbox which is created by the SelectionPlugin. The value of that attribute should contain the corresponding rowIndex of the row for testing purposes.
However, currently it's not possible to link the rowIndex to the attribute if we are doing it like this:
```
SelectionPlugin selectionPlugin = new SelectionPlugin(ColorScheme.RED);
        Supplier<CheckBox> checkBoxCreator = () -> {
            CheckBox checkBox = new CheckBox();
            checkBox.setAttribute("row-index", rowIndex)
            return checkBox;
        };
        selectionPlugin.setCheckBoxCreator(checkBoxCreator);
```

**Describe the solution you'd like**
It should be possible to access the current rowIndex inside the CheckBox Supplier to be able to use it for attributes.

**Comment by vegegoku** [comment]
Now you need a specific interface instead of just a supplier, and you will get an optional of a table row since for the header we dont have an actual table row.
