### ISSUE TITLE
Tables should support value change of multiple selected entries at once

### ISSUE THREAD

**Issue by bschmelcher** [DominoKit/domino-ui#657]
**Is your feature request related to a problem? Please describe.**
We would like users to be able to select multiple rows of a table to allow changing the values of all selected rows simultaneously.
This would greatly improve the user experience when working with large tables.

**Describe the solution you'd like**
It should be possible to somehow mark multiple rows of a table (maybe the SelectionPlugin could be used for that) to allow changing values of each selected row simultaneously.
So if for example three entries are selected currently and e.g. the textvalue of column A is changed in one of the selected entries, this change will apply to all selected rows.

**Comment by vegegoku** [comment]
Do you have a suggest way to do this? can you please explain how you would do that in the UI?

**Comment by bschmelcher** [comment]
Sure, the idea would be to do it like in the screenshot.
When changing the value of a field in the table (in the screenshot from A to B), it will be checked if there are any rows currently selected.
If that's the case, the change which is normally applied to the row where the change is done, will be applied to all selected rows:
![image](https://user-images.githubusercontent.com/102970139/172333531-985ffea1-cd5a-438b-8f3a-8f7835037420.png)

Another idea while doing this would be to allow selecting a row by ctrl-clicking it.

**Comment by vegegoku** [comment]
This is a very specific use case for you it seems and not something we can generalize for everyone and I prefer to keep such behaviors out of the scope of the component itself or its built-in plugins.

With that said doing this should be fairly easy with the current api. with a simple change handler on the field being edited get all selected rows that are editable and update the record for each row with the new value and call row.updateRow.
