### ISSUE TITLE
CSS Animations for tooltips/popovers/modals/windows

### ISSUE THREAD

**Issue by jhickman** [DominoKit/domino-ui#669]
It appears that the 'opacity' transition for tooltips and other popups such as Windows do not apply their fade-in animations.   This could be due to adding the css classes "fade", "in" at the same time as appending the element to the DOM.   From my understanding, CSS animations will require a separate event loop that applies a style change to an element already in the DOM; otherwise, the browser will only render the 'final state' and not the actual animation when appending.

I created a small fiddle to demonstrate.   In the fiddle, I have 2 functions.  One where it adds the 'in' css class in the same event loop as appending the element to the DOM; and another function where I use a 0ms timeout to apply the 'in' css class.

https://jsfiddle.net/jhickman/c2q4nvte/

In Tooltip.java (in particular.  I haven't looked at the other popover classes), it's adding both 'fade' and 'in' to the element that has just been appended to the body.   The animation doesn't occur.   

A quick test would be to modify the `.fade` css style to increase the transition from .15s to something much more noticeable like 2s.   Any widget that utilizes the fade CSS _should_ show the longer animation for opacity.

**Expected behavior**
The expected behavior would be for CSS animations to work as intended.

Possible solution (at least in Tooltip) is to use a timeout for adding the 'in' CSS:
```java
DomGlobal.setTimeout(arg -> element.addCss("in"));
```

**Comment by rjeeb** [comment]
The animation was fixed for `fade-in` and `fade-out` for all 4 components.

Based on the MDN [documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions#javascript_examples)  we should use `setTimeout` to add the css for the transition to begin
