### ISSUE TITLE
Window centerVertically() does not work

### ISSUE THREAD

**Issue by jhickman** [DominoKit/domino-ui#672]
**Describe the bug**
It appears that when you call `.centerVertically()` on a Window, it will add the `v-center` style class to the first child of the modal (the `modal-dialog`).

This appears to cause the content INSIDE the drop shadow to be centered rather than centering the entire modal in the browser.

**Expected behavior**
I'm assuming that `.centerVertically()` is intended to center the modal/window in the client area.

**Screenshots**
![image](https://user-images.githubusercontent.com/861908/179580137-5863eb08-548d-4cd8-b061-26d2ef36119d.png)

**Additional context**
In Chrome dev tools, if I remove the `v-center` class from the first child, and then add `top: 50%`, it gives what I want; however, it doesn't appear that I can call `.setTop("50%")` on the window as that value gets overwritten inside the private method `Window.updatePosition()`.   Appears to force the 'top' style to either (100 + offset) px, or uses the double windowTop field.. as px.  So, not a way to use a percentage for the top.

**Comment by rjeeb** [comment]
The fix was applied to every type of modals. For windows, there is a special handling as the top is calculated.
