### ISSUE TITLE
Tabs will not disable

### ISSUE THREAD

**Issue by jhickman** [DominoKit/domino-ui#678]
When trying to disable tabs, it doesn't appear that disabling actually does anything other than adding the 'disabled' css class to the element.

Here's some example code that produces this issue
```java
parent.appendChild(TabsPanel.create()
    .appendChild(Tab.create("Tab 1")
        .appendChild(span().textContent("Tab 1 content"))
    )
    .appendChild(Tab.create("Tab 2") 
        .disable()  // only adds the 'disabled' css class
        .appendChild(span().textContent("You shouldn't be seeing this"))
    )
);
```

**Expected behavior**
When using the following Tab methods for disabling, the tab should become unclickable.
* .disable()
* .setDisabled(true)

**Comment by jhickman** [comment]
Should mention that this also impacts VerticalTabsPanel and VerticalTab

**Comment by vegegoku** [comment]
Yes it seems disabled  is not being taken into consideration at all, and the disable methods are just being inherited from the Base class.

**Comment by rjeeb** [comment]
Disabled style has been added to `Tab` and `VerticalTab`. Also, `enable` and `disable` methods have been overridden in `TabsPanel` and `VerticalTabsPanel` to disable all of their tabs children.
