### ISSUE TITLE
Readonly TextBox getting 'disabled' too

### ISSUE THREAD

**Issue by jhickman** [DominoKit/domino-ui#679]
It appears, from ValueBox.setReadOnly, it's also setting the input as disabled.   "read only" fields should still receive focus.

**Expected behavior**
When setting a TextBox to readonly, it should still be focusable, via tab or click.

**Work around**
When building the UI, using ordered operations, we can set to readonly, and then re-enable it
```java
TextBox.create("Foo")
  .setReadOnly(true)
  .setDisabled(false)
```

**Comment by rjeeb** [comment]
`Readonly` now does not disable input field, it just makes it readonly.
