### ISSUE TITLE
Support global button default elevation

### ISSUE THREAD

**Issue by jhickman** [DominoKit/domino-ui#687]
Currently in DominoUI, Buttons default to "elevation-1".   The application I'm working in needs to default to buttons being flush with the panel they're on (thus, being elevation-none or .elevate(0)). 

Because of this, developers have to remember to always add `.elevate(0)` when creating UIs.  

This request is to support a global option to support a default button elevation.  Maybe something like
```java
DominoUIConfig.INSTANCE.setDefaultButtonElevation(0);
```

**Comment by rjeeb** [comment]
`DominoUIConfig.INSTANCE.setDefaultButtonElevation(0);` has been introduced.
