### ISSUE TITLE
Cannot 'unfloat' field labels

### ISSUE THREAD

**Issue by jhickman** [DominoKit/domino-ui#688]
**Describe the bug**
I have a theme that needs the field labels to always float.  Looks like this:
![image](https://user-images.githubusercontent.com/861908/183741377-92a29682-7d08-4544-b222-92c599e2fc39.png)

So, in an entryPoint, I configure this default behavior with this:
```java
public void onModuleLoad() {
  DominoUIConfig.INSTANCE.setFloatLabels(true);
}
```

However, there are times that I need certain fields to not float labels (for any input that may not have a label).   When I try to create with `.nonfloating()` or `setFloating(false)` it doesn't do anything (the `floating` css class stays on the element).   
```java
TextBox.create()
  .nonfloating()
  .setPlaceholder("Enter value here")
```

Looking at the code, I believe I have found the issue.   When `.setFloating(true)` is called, it sets the boolean field `permaFloating` to true.   And with my setup, the constructor will set this to true due to the DominoUIConfig.

In `nonfloating()`, it first calls `unfloatLabel()` which checks the `permaFloating` value; and since it's true, it'll just return without removing the 'floating' css style.   However, the `nonfloating()` next line is `this.permaFloating = false`, which means in order to turn off floating, i have to call `.nonfloating()` twice.  The following code is the work around
```java
TextBox.create()
  .nonfloating()
  .nonfloating()
  .setPlaceholder("Enter value here")
```

**Comment by jhickman** [comment]
Maybe I need to understand the floating label mechanism a bit more, and maybe this should be partly a feature request instead.   The bug is still there for sure, but I think I'm looking for a different bit of behavior.

When I turn off the floating (where it removes the '.floating' css class), it removes the placeholder, and adds the floating style back when the field is focused; thus causing issues with my layout when tabbing/clicking into textboxes.

What would be best for me is some class (or lack of a class) when there is/isn't a <label> element added.  CSS doesn't support parent selectors, and the `:has` selector is  in CSS v4 spec, so that's not available either.

**Comment by vegegoku** [comment]
Or maybe we redo the css so that the css class is on the label element itself instead of the parent.. :thinking:

**Comment by jhickman** [comment]
The solution I had to go with was just to add a marker css class to the field and avoid the nonfloating altogether.   Made it a bit simpler
