### ISSUE TITLE
Data table - Separate alignment for headers

### ISSUE THREAD

**Issue by jhickman** [DominoKit/domino-ui#689]
When changing the text alignment of a column config (`.alignRight()` or `.alignCenter()`), it will also align the header the same.  Is it possible to separate these such that the header alignment can be a separate setting/method?    I have a usecase where the header alignment differs from the cell alignment

**Comment by rjeeb** [comment]
`headerAlignLeft()`, `headerAlignRight()` and `headerAlignCenter()` have been introduced to align the header text
