### ISSUE TITLE
Implement three state DataTable sorting

### ISSUE THREAD

**Issue by armogur** [DominoKit/domino-ui#692]
**Is your feature request related to a problem? Please describe.**
Currently DataTable header sorting has two state: ASC, DESC. If a user applied sorting on a column there is no way to go back to unsorted.

**Describe the solution you'd like**
It would be nice to have a three state sorting, so when a user clicks on a sortable column the states will go cycle like this: SortDirection.ASC -> SortDirection.DESC -> SortDirection.NONE

**Describe alternatives you've considered**
Currently the only way is to reimplement the SortPlugin

**Additional context**
It would be good if the behaviour can be applied at a constructor level with keeping the current empty constructor, like these:

1. Empty constructor defaults to the current behaviour (two states)
2. A new constructor with boolean input argument: **boolean threeStateSorting**
- **false** keeps the current behaviour
- **true** uses the new three state sort direction.
4. It would be also nice to have a resetSortingOrder() function in SortPlugin so it can be used from for example event handlers.

**Comment by vegegoku** [comment]
SortDirection now is ASC, DESC, and NONE
