### ISSUE TITLE
DataTable loses selection when sorting

### ISSUE THREAD

**Issue by jhickman** [DominoKit/domino-ui#702]
When sorting a column whilst using the SelectionPlugin, the selected rows are lost.

**Expected behavior**
Retained row/record selection when sorting.

**Comment by vegegoku** [comment]
This implies that either the same records are present in the data table or that we loop over the records after the sort and check them against a preserved list of the records that were selected, then auto select the previously selected records and ignore the other records.

**Comment by vegegoku** [comment]
Selection can be retained now by calling `setRetainSelectionOnDataChange` on the selection plugin with the value '`true`
