### ISSUE TITLE
Data table don't scale well on extra small screens

### ISSUE THREAD

**Issue by masterdany88** [DominoKit/domino-ui#71]
Data table don't hide columns that not fit small screens.
![screenshot_2018-08-14-14-51-09](https://user-images.githubusercontent.com/1161910/44094038-59b322f8-9fd5-11e8-8021-88e083572445.png)

**Comment by vegegoku** [comment]
This feature is not yet implemented.
recently we have added media queries utils which will help us implement this, we will also include a convenient way to display the row in small screen if the column are still need to be visible.

**Comment by vegegoku** [comment]
Data table now allows showing and hiding columns based on screen size, one can implement columns that will only appear on smaller screen with compact view of the data, while hiding normal columns on larger screens.
