### ISSUE TITLE
In some cases ModalBackDrop is not removed

### ISSUE THREAD

**Issue by FrankHossfeld** [DominoKit/domino-ui#713]
Testing the latest SNAPSHOT I ran into some trouble which does not happen with RC13.

Loading a Screen, a ModalDialog is displayed and shows a "work in progress" message. On that screen there are three cards. Each of the cards has its own loader. The loader locks the card during data loading.   So, at loading the screen the modal dialog is shown and the three loaders are locking the card. 

Once everything is loaded, the "work in progress" modal is closed and the cards are unlocked. 

With the HEAD-SNAPSHOT version the MODAL_BACKDROP did not get removed.

Running the page in Chrome debugger, it works.

@vegegoku PM me please, I can show you the problem live

**Comment by vegegoku** [comment]
This seems to be caused by calling hide instead of close on the modal dialog, or calling hide before calling the close method. adding a hide listener to close the modal can fix this.
