### ISSUE TITLE
data table: grouping row does not fit datatable with

### ISSUE THREAD

**Issue by FrankHossfeld** [DominoKit/domino-ui#714]
The latest SNAPSHOT has a problem with the grouping column of a data table.

I'll add an image that shows the problem. Had no chance to dig into it cause #713 blocks my testing.

![DT-grouping_bug](https://user-images.githubusercontent.com/8287845/193559929-c96fab6b-f30c-4c75-aaf6-70c03c93e395.png)

**Comment by vegegoku** [comment]
I just tested this by building an running the demo locally and it works, do you have a reproducer?
