### ISSUE TITLE
Implement live grid for large data sets

### ISSUE THREAD

**Issue by vegegoku** [DominoKit/domino-ui#725]
Ability to support and maintain high performance on large data sets without requiring pagination
aka "live grid" -- similar to scroll loading and pagination together)

original issue #683

**Comment by Ri-gers** [comment]
Hi, is there any update on this? For me, using a DataTable while having a few hundred up to some thousand elements causes a lot of rendering time. Any plans on implementing virtual scrolling?

**Comment by vegegoku** [comment]
added to to domino-ui-pro

**Comment by Ri-gers** [comment]
Hi, what exactly is meant by the 'pro' label?

**Comment by vegegoku** [comment]
> Hi, what exactly is meant by the 'pro' label? And is there a showcase for it somewhere?

We will announce it soon, we are still working on that, and yes the show case will be available when we are done.

**Comment by Ri-gers** [comment]
Does this also include searching/filtering the whole table even if only a part of all items is shown by default (using SearchTableAction)?

**Comment by Ri-gers** [comment]
> > Hi, what exactly is meant by the 'pro' label? And is there a showcase for it somewhere?
> 
> We will announce it soon, we are still working on that, and yes the show case will be available when we are done.

Hi,
any updates on an ETA, features, payment details etc.? I need more information regarding domino-ui-pro so that I can provide these information to my company/manager. I would really appreciate an update, thank you in advance.
