### ISSUE TITLE
Select form element does not have scroll bar

### ISSUE THREAD

**Issue by masterdany88** [DominoKit/domino-ui#73]
Select don't have scroll back and user can see how many options are there. Second think it's that when you want scroll with thumb it make hovered option selected
![screenshot_2018-08-15-09-31-51](https://user-images.githubusercontent.com/1161910/44136896-c7806c3e-a06e-11e8-885b-647eb849ad58.png)

**Comment by rjeeb** [comment]
When scrolling, the option should not be selected so this is a bug and we'll work on it, thanks.

**Comment by masterdany88** [comment]
I've also ment scroll bar instead. Something that will indicate the size of options list and position on the list, like in browser page f.e.
Can I see those changes applied in demo?
