### ISSUE TITLE
searchHeaderBarTableAction.getTextBox().setValue("my search string") does not trigger a search event

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#745]
**Describe the bug**
As discussed on gitter:
I have a `SearchTableAction` and there I can do `searchHeaderBarTableAction.getTextBox().setValue("my search string");` but this does not trigger the `SearchTableAction::search()`and since `search() `is `private` there is no way I can trigger the search manually. 

vegegoku suggested on [Jan. 06 23:35](https://gitter.im/DominoKit/domino?at=63b8a232410c633d4812c876)
> I would actually fix this by allowing it to work like other filters, so you can just set the value then do `table.getSearchContext().direSearchEvent()` this would be the best fix I think.

**Comment by vegegoku** [comment]
a fix have been applied, now it is possible to trigger the search after the set value by calling `datatable.getSearchContext().fireSearchEvent()`

**Comment by schube** [comment]
Thank you very much!!!
