### ISSUE TITLE
Tooltip drawing off screen with header ActionItem

### ISSUE THREAD

**Issue by howudodat** [DominoKit/domino-ui#759]
**Describe the bug**
when I set the tooltip to the icon it is visible, when I set it on the action item, it's painted off screen

**To Reproduce**
Steps to reproduce the behavior: Use the following code to add Action Items
```
protected LayoutActionItem btnRefresh =             
    LayoutActionItem.create(Icons.ALL.refresh())
        .setTooltip("Refresh")
        .addClickListener(l->onRefresh());
protected LayoutActionItem btnSave = 
    LayoutActionItem.create(
        Icons.ALL.save()
            .setTooltip("Save This Record"))
        .addClickListener(l->onSave());
**Expected behavior**
A clear and concise description of what you expected to happen.
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser chrome
 - Version 109.0.5414.119 (Official Build) (64-bit)

[Screencast from 02-05-2023 06:56:03 AM.webm](https://user-images.githubusercontent.com/3333605/216827013-4b51c541-d147-424c-9974-dc6733742f32.webm)

**Comment by vegegoku** [comment]
Fixed in version 2.x.x
