### ISSUE TITLE
Bug: BestSideUpDownDropDirection calculation for downSpace

### ISSUE THREAD

**Issue by jhickman** [DominoKit/domino-ui#765]
There appears to be a calculation issue with BestSideUpDownDropDirection; specifically the downSpace variable.

Currently, [it has](https://github.com/DominoKit/domino-ui/blob/master/domino-ui/src/main/java/org/dominokit/domino/ui/menu/direction/BestSideUpDownDropDirection.java#L36):
```java
double downSpace = innerHeight - targetRect.height;
```

This doesn't take into account the target position; just the window height minus target elements height.    It looks like the `rightSpace` variable is calculated correctly.    

I was able to change `downSpace` to the following and it appears to have fixed the issue.

```java
double downSpace = innerHeight - targetRect.bottom - window.pageYOffset;
```

**Comment by vegegoku** [comment]
Ok I found that actually I am missing the top calculations, the

 down space(green) = window inner height(yellow) - the target height(red) - target top(blue) 
 
 And this should work in regards the element position I guess.

![image](https://user-images.githubusercontent.com/5379625/221779996-f40f5b2e-3c96-490e-b929-7b436c607cc4.png)

**Comment by vegegoku** [comment]
![menu-best-side-up-down](https://user-images.githubusercontent.com/5379625/221784772-471a700a-0d39-41ea-bb04-e49a1d5d43a9.gif)

**Comment by jhickman** [comment]
Fix LGTM
