### ISSUE TITLE
Feature Request: DataTable SortPlugin to allow configurable icons

### ISSUE THREAD

**Issue by jhickman** [DominoKit/domino-ui#768]
Currently, the SortPlugin for DataTable has hardcoded icons for sort header.    This request is to support configuration options of setting our own icons.

Another request is to support NOT having an icon.   For example, I'm okay  with the ascending/descending icons, but for a table that has sort on all of the columns, I don't want to show the sort icon everywhere.

**Comment by vegegoku** [comment]
Now the user can configure the sort plugin like this 
```java
                .addPlugin(new SortPlugin<Contact>().configure(sortPluginConfig -> sortPluginConfig
                                .setAscendingIcon(Icons.ALL::chevron_double_up_mdi)
                                .setDescendingIcon(Icons.ALL::chevron_double_down_mdi)
                                .setDescendingIcon(Icons.ALL::chevron_double_down_mdi)
                                .setUnsortedIcon(Icons.ALL::menu_swap_outline_mdi)
                                .setShowIconOnSortedColumnOnly(true)
                                .setTriStateSort(true)
                        )
                )
```

**Comment by FrankHossfeld** [comment]
Do you think it is possible to define the icons inside DominoUIConfig? So, I can do that in one place for the whole application.

**Comment by jhickman** [comment]
Fix LGTM

**Comment by vegegoku** [comment]
For now a simple factory in the app can do this, meanwhile I think we are bloating the config with different kind of configurations but the current design does not help with this, In version 2 I am thinking of a better implementation for the configuration the should scale as needed.
