### ISSUE TITLE
Bug: Disabled MenuItem still receive events

### ISSUE THREAD

**Issue by jhickman** [DominoKit/domino-ui#769]
Disabled menu items appear to have the style applied, but will still execute the click handlers.

sample code:

```java
Button.create("click")
  .setDropMenu(Menu.create()
    .appendChild(MenuItem.create("Test")
      .disable()
      .addClickListener(evt -> DomGlobal.alert("fail"))
    )
  )
```

**Comment by vegegoku** [comment]
Trying to reproduce this and it seems the clickListeners does not work after disable but Selection listeners still working.

**Comment by jhickman** [comment]
fix LGTM
