### ISSUE TITLE
Select component to be compatible with HTML form element

### ISSUE THREAD

**Issue by rjeeb** [DominoKit/domino-ui#775]
Values inside the HTML form can be gotten by using `FormData` which depends on input elements that exist inside the form. In the case of Select, there is no `<select>` element so it won't work with HTML forms.

A solution can be to add a hidden `<select>` element to support this. The `<select>` element should have all the options added to the Select and when a value is selected in the component, then the value of the `<select` element should be changed.

**Comment by vegegoku** [comment]
A work around for this is to have a hidden textbox with a changeHandler in the select to fill it, and this is already fixed in next upcoming major version.
