### ISSUE TITLE
DataTable header background is transparent 

### ISSUE THREAD

**Issue by FrankHossfeld** [DominoKit/domino-ui#777]
That's the basic look of a DataTable:

![ok](https://user-images.githubusercontent.com/8287845/231225579-f0644e41-e161-4551-88a0-0d6ec896d98c.png)

The background of the header look s normal. Now scroll down:

![bug](https://user-images.githubusercontent.com/8287845/231225748-7ca0566e-396b-4f2a-85b5-a787f8aa5050.png)

The background of the column headers are transparent and the content of the scrolled up part of the DataTable body is visible.

Adding: `this.dataTable.headerElement().setBackgroundColor("white");` solve the issue.

I'll create a small project to reproduce the issue.

[issue-dti.zip](https://github.com/DominoKit/domino-ui/files/11202708/issue-dti.zip)

**Comment by FrankHossfeld** [comment]
Update:
this error happens in case you use the following structure:

`card.appendChild(DominoElement.div()).appendChild(dataTable)); `

here the error exists.

Switching back to:

`card.appendChild(dataTable)); `

Using:

`card.appendChild(DominoElement.div().styler(style -> style.setBackgroundColor("inherit"))).appendChild(dataTable)); `

also works

**Comment by FrankHossfeld** [comment]
Think we can close that one ...

**Comment by howudodat** [comment]
Is that the best way to handle this?  Just curious, I'm no expert in css and html apps, but doesn't that make themeing, or support for dark mode harder?
