### ISSUE TITLE
Feature: new component: color picker

### ISSUE THREAD

**Issue by mP1** [DominoKit/domino-ui#781]
**Is your feature request related to a problem? Please describe.**

A color picker is currently missing. Was hoping for something that had some combination such as

- sliders to control RED | GREEN | BLUE
- text boxes for RED | GREEN | BLUE showing and editing
- sliders to control HUE | SATURATION | VALUE
- text boxes for HUE | SAT | VALUE showing and editing
- a canvas showing all the colors supporting a picker to pick a color.
- im not sure how to mix rgb and hsv viewing/editing

**Describe the solution you'd like**
Perhaps the picker should provide a callbacks which are invoked when a color is selected passing three component values one each for Red/Green/Blue.

**Comment by vegegoku** [comment]
added to domino-ui-pro
