### ISSUE TITLE
Card header action can't be clicked when combined with tooltip (1.0.0-RC19)

### ISSUE THREAD

**Issue by wernz0r** [DominoKit/domino-ui#795]
First of all: Thanks for all the work you guys put into domino-ui! I really appreciate it! 👍 

Here's a little bug i found in the current release of 1.0.0-RC19

**Describe the bug**
Since domino-ui version 1.0.0-RC19, card header actions no longer work if they have a tooltip. The icon of the header action is displayed normally, but the click event is not executed.

**To Reproduce**
To reproduce you can use this little showcase with domino-ui version 1.0.0-RC19:
```
Card.create("My showcase")
    .addHeaderAction(
        Icons.ALL.close().setTooltip("My tooltip", PopupPosition.LEFT),
        event -> Notification.create("this click does not work").show()
    )
    .addHeaderAction(
        Icons.ALL.more_vert(),
        event -> Notification.create("click works").show()
    )
    .setWidth("500px")
    .appendChild(Paragraph.create("Lorem ipsum dolor"))
```

**Expected behavior**
Clicking a header action should trigger the click event.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome, Version 114.0.5735.199

**Comment by FrankHossfeld** [comment]
MIght be releated to: https://github.com/DominoKit/domino-ui/issues/790

**Comment by howudodat** [comment]
> MIght be releated to: #790

yes, it's the same bug

**Comment by wernz0r** [comment]
you guys are right. #790 describes the problem even better. therefor i'm closing this issue. thanks for drawing my attention to this.
