### ISSUE TITLE
v2 New MenuBar component

### ISSUE THREAD

**Issue by mP1** [DominoKit/domino-ui#822]
Currently menus (let ignore context menu) must be added to buttons etc. The menu item itself is not visible, all items including the first or top only become visible when the drop down button is clicked, then the menu list appears.

It would be great if a MenuBar component exists. A MenuBar will always be visible and when an item is selected, a drop down menu will become visible. It would also be nice if the keyboard could then be used to travel up and down a single menu list, or across to other items in the menu bar.

Sample Menu bar which is always visible wherever it is positioned.
```
File Edit View History
``` 

The menu bar items could be styled similarly to the menu items in the drop downs.

**Comment by vegegoku** [comment]
Added to domino-ui pro
