### ISSUE TITLE
V2: Hide dropdown when focus lost

### ISSUE THREAD

**Issue by howudodat** [DominoKit/domino-ui#826]
**Describe the bug**
When the user clicks on another element when a drop down menu is visible, it should hide

**To Reproduce**
create and show a DropButton menu
click on another element

**Expected behavior**
The dropdown menu should hide

**Screenshots**
[Screencast from 08-28-2023 07:13:33 AM.webm](https://github.com/DominoKit/domino-ui/assets/3333605/46502d92-d2c0-4d45-a931-9d49c5b26ef8)

**Comment by vegegoku** [comment]
also #828
