### ISSUE TITLE
Feature Request: Add ability to make stepper read-only, or to be able to block going backwards in a stepper

### ISSUE THREAD

**Issue by ainslec** [DominoKit/domino-ui#83]
Hello,

I'd like to use the Stepper in a wizard UI type use-case, but some steps are "points of no return" and therefore I'd like to be able to stop the user from clicking an earlier steps and being able to edit the information there. If there was a validation method something like

public boolean canGoBackTo(Step currentStep, Step priorStep, int currentStepIndex, int priorStepIndex) {
   // implementor implements this
}

... that would be great. If this method returns false, then Domino could block the "click" event.

Chris

**Comment by vegegoku** [comment]
What if instead we add a flag to the stepper to mark the default behavior, but also allow each step to override that flag for itself. Knowing that this only applies to clicks on the step header while other cases can be handled by the custom navigation buttons.

**Comment by vegegoku** [comment]
you can now call `stepper.disableClickNavigation` to disable navigation when step header is clicked

**Comment by vegegoku** [comment]
Can you please confirm if this fix the issue for you?

**Comment by vegegoku** [comment]
@ainslec does this work for your use case?

**Comment by ainslec** [comment]
I think it should work for the use case, as I should be able to enable and disable navigation on the fly. BUt I have not yet been able to test.

**Comment by ainslec** [comment]
Thinking about this some more, I think that a granular approach is required, more than the blunt approach of disable click or enable click events on the header. For example, there may be points of no return in a stepper. For example, step 1, 2, 3, once stepped through, cannot be modified, but then 4,5,6, might be able to be traversed. The suggested resolution (stepper.disableClickNavigation()) would not allow for granularity of deciding which steps  are permitted to be stepped into. Therefore, I think that adding a click validation method, would allow fine grained control over the stepper for these advanced scenarios.

Or maybe I'm misunderstanding something about how disableClickNavigation() should be used?

**Comment by vegegoku** [comment]
i will assume this is already tested and working
