### ISSUE TITLE
V2: text elements should all align the same

### ISSUE THREAD

**Issue by howudodat** [DominoKit/domino-ui#830]
**Is your feature request related to a problem? Please describe.**
different text elements seem to align differently inside a row

**Describe the solution you'd like**
all text elements, in fact all elements should align the same in a row

**Describe alternatives you've considered**
manually setting css for each element that needs aligned.

```
row = Row.create();
row.appendChild(Column.span1().appendChild(p("Contact:") ));
row.appendChild(Column.span1().appendChild(p("TYPE").addCss(dui_font_bold) ));
row.appendChild(Column.span1().appendChild(p("Name:") ));
row.appendChild(Column.span2().appendChild(p("PETER").addCss(dui_font_bold) ));
row.appendChild(Column.span1().appendChild(p("Mobile:") ));
row.appendChild(Column.span2().appendChild(a("tel:111-222-3333").setTextContent("111-222-3333").addCss(dui_font_bold) ));
row.appendChild(Column.span1().appendChild(p("Email:") ));
row.appendChild(Column.span3().appendChild(a("mailto:peter@foo.bar").setTextContent("peter@foo.bar").addCss(dui_font_bold) ));
```

![image](https://github.com/DominoKit/domino-ui/assets/3333605/bfab9f34-d393-469f-a236-4ee92968a35a)
![image](https://github.com/DominoKit/domino-ui/assets/3333605/211b8ee7-f207-4ed3-b2be-d383785d49ba)

**Comment by FrankHossfeld** [comment]
First of all, use this code. It does the same, but is much more readable and is not so boiler-plated:

```
    Row row = Row.create().span1(p("Contact:"))
                                            .span1(p("TYPE").addCss(dui_font_bold))
                                            .span1(p("Name:"))
                                            .span2(p("PETER").addCss(dui_font_bold) )
                                            .span1(p("Mobile:"))
                                            .span2(a("tel:111-222-3333").setTextContent("111-222-3333").addCss(dui_font_bold))
                                            .span1(p("Email:"))
                                            .span3(a("mailto:peter@foo.bar").setTextContent("peter@foo.bar").addCss(dui_font_bold));
```

and avoid using p(). This adds margin-top and margin bottom,  use `div().textContent("Contact:")` instead.

**Comment by howudodat** [comment]
That was very helpful.  My solution was to create my own ElementsFactory so I could have a similar shortcut to p() just t()
```
public interface MyElements extends ElementsFactory {
	  /**
	   * t.
	   *
	   * @param text a {@link java.lang.String} object
	   * @return a {@link org.dominokit.domino.ui.elements.DivElement} object
	   */
	  default DivElement t(String text) {
	    return  new DivElement(dom.div()).setTextContent(text);
	  }
}

```

then I can call it with:  appendChild(t("Name:") ));

PS.  The reason I am not using builder style is because a lot of the UI is built with user settings, I simplified the code above, but a lot of code looks like:
if (UserPrefs.show("something")) row.appendChild(some_element);

**Comment by vegegoku** [comment]
I prefer not to change the default behavior of those html elements and let the user do what is needed to align them as he needs.
