### ISSUE TITLE
Sub-components in Card Header / RHS

### ISSUE THREAD

**Issue by ainslec** [DominoKit/domino-ui#84]
I see that cards allow that Cars are permitted titles, and also permitted header actions (icons). I kind of wonder if it's possible (or feasible) to be able to add any given component on the right hand side of the card header (such as a progress bar).

No problem if it can't be done. Just checking.

**Comment by vegegoku** [comment]
It is already possible and doable, in our form sample we do this 
https://dominokit.github.io/domino-ui-demo/index.html?theme=pink#form-sample

I will share a sample code here soon

**Comment by rjeeb** [comment]
This is a sample code of how we do that in our form sample

```java
Button addButton = Button.createDefault(Icons.ALL.add())
			.setContent("ADD")
			.linkify()
			.style()
			.setMarginTop("-10px")
			.get();
card.getHeaderBar()
	.appendChild(addButton
		.addClickListener(evt -> {})
		.asElement());
```

Try it and start a discussion in the channel if there is any problem
