### ISSUE TITLE
v2: Dialog -> use the content height as dialog height 

### ISSUE THREAD

**Issue by FrankHossfeld** [DominoKit/domino-ui#846]
Using a dialog requires setting in height in Pixel. Ohterwiese the dialog will - depending on the value of `setStrechHeight()` - use a heigh, which in many cases does not fit the height of the content. In the end. it is necessary  to seht the height with `setHeight`.

It would be nice to have something like `setContentFit(true)` that tell the dialog to use the height of the content.

Or, is there already something that does it and I missed?

**Comment by vegegoku** [comment]
All you need to do is to set the content body height to fit content
```java
                .withContentBody((parent, self) -> {
                    self.addCss(SpacingCss.dui_h_fit);
                })
```

https://github.com/DominoKit/domino-ui/assets/5379625/7fefedc6-885c-43f4-8d3a-d430ea627523

**Comment by FrankHossfeld** [comment]
This one is used with a fixed height in px:

![account-height](https://github.com/DominoKit/domino-ui/assets/8287845/2e593f99-0d7b-4870-909a-34e28ad3a1c6)

and this one using fit ....

![account-fit](https://github.com/DominoKit/domino-ui/assets/8287845/54ff3134-95ca-48f3-8fae-4d0aab48b89c)

may be I am doing something wrong?
