### ISSUE TITLE
Upgrade elemento to 1.2.x

### ISSUE THREAD

**Issue by adrian-haenni** [DominoKit/domino-ui#850]
The used elemento version is outdated. Please upgrade org.jboss.elemento:elemento to v1.2.x, but be aware it contains some major changes with new class names and more.

**Comment by FrankHossfeld** [comment]
IIRC, Elemento requires at least Java 11 ...

**Comment by vegegoku** [comment]
elemento 1.2.x bring some breaking changes, not sure we want  to introduce breaking changes to a stable release, plus in v2 we are not using elemento anymore
