### ISSUE TITLE
Scroll loading does not work if the table is not displayed completely horizontally

### ISSUE THREAD

**Issue by JuliusRuppert** [DominoKit/domino-ui#862]
**Describe the bug**
When having a table, that is not displayed completely horizontally, the scroll loading does not work as expected. When scrolling down to the last entry, new entries are displayed only sporadically. Problem appears on v1 and v2. 

**To Reproduce**
1. Go to [Domino UI v1 Demo Scroll Loading](https://dominokit.com/domino-ui/demo/v1/datatable/scroll-loading) or [Domino UI v2 Demo Scroll Loading](https://dominokit.com/domino-ui/demo/v2/datatable/scroll-loading)
2. Reduce window width, so that the table is not displayed completely and a horizontally scroll bar is displayed.
3. The Scoll Loading does only load new entries sporadic and not every time when we scroll to the very bottom of the table.

**Expected behavior**
The scoll loading should load new entrties even if the table is not completely displayed horizontally, which may be the default case when having many columns. 

**Desktop:**
- OS: Windows 10
- Browser: Edge 
- Version: 118.0.2088.61
- Browser: Firefox 
- Version: 118.0.2

**Comment by JuliusRuppert** [comment]
Hi @vegegoku,
thanks for fast fixing.
I implemented your changes in my code and tested it. In Firefox everything works fine. But with Edge and Chrome there is now the same problem when the table is displayed in full width. When it has horizontal scroll bars it works, but it does not work without.
Do you know why this happens?
Thanks

**Comment by vegegoku** [comment]
The is issue is a little bit complicated it seems because the scroll bars. zoom and other factors affect the calculation for the scroll reaching the bottom, and it seems it has different behavior for different browsers. we have added an offset as part of the plugin config to make it configurable so the scrollbar does not need to reach the exact bottom , try playing with that while I investigate the issue again.

**Comment by vegegoku** [comment]
It is working on chrome, can you please prepare a reproducible project for this. I am not sure now what is causing the issue for you/
https://github.com/DominoKit/domino-ui/assets/5379625/3067013e-5254-48ba-a826-5a758ece5f74

**Comment by JuliusRuppert** [comment]
Seems to depend on the display resolution. I previously tested on 3840x2160. When changing to 1920x1080 it works for me as well in Chrome.

**Comment by vegegoku** [comment]
This is on a much higher resolution
https://github.com/DominoKit/domino-ui/assets/5379625/dd0e50a4-777d-46c3-ab96-820c86980835

**Comment by JuliusRuppert** [comment]
I have the same problems when compiling the development branch of the domino-ui-demo using SNAPSHOT-HEAD as it is in this commit https://github.com/DominoKit/domino-ui-demo/commit/85a6c245b78f623f98a5771deb8ec2672a9256a0.
This problem only appears in Chromium Browsers. I played a little around with the os display scale. When being on 100% everything works fine. But when I change it to a zoom, e.g. 125% it does not work any more. Maybe this is related to the problem you mentioned above in this https://github.com/DominoKit/domino-ui/issues/862#issuecomment-1790499106
