### ISSUE TITLE
Implement getRecords() for LocalListScrollingDataSource

### ISSUE THREAD

**Issue by JuliusRuppert** [DominoKit/domino-ui#863]
**Is your feature request related to a problem? Please describe.**
In our project we want to get all table entries from a `LocalListScrollingDataSource`. 

**Describe the solution you'd like**
Having a function `getRecords()` for `LocalListScrollingDataSource` returning a List containing all table entries like in `LocalListDataStore` would solve this problem.

**Comment by vegegoku** [comment]
> Hi @vegegoku, would it be possible to implement this method to v1 as well? Would be great if you could do this. Thanks

Would please file an issue and link it with this one, So I dont forget to include it in next release cycle.
