### ISSUE TITLE
silently setting select doesn't pass notification to dropdown

### ISSUE THREAD

**Issue by howudodat** [DominoKit/domino-ui#869]
**Describe the bug**
There are times you may want to silently set a select or multi-select (ie: setting default parameters) without trigger change handlers.  Doing so sets the value in the textbox but does not pass the selection to the dropdown.  It also results in the user needing to select the item twice in order to de-select it.

**To Reproduce**
see code below, 

- click on the select dropdown, selected items are not highlighted.  
- Click on a selected item (visually nothing happens)
- Click on that same selected item and now it deselects

**Expected behavior**
The dropdown should also receive notice that the item was selected

**Screenshots**
![Screenshot from 2023-10-29 07-42-33](https://github.com/DominoKit/domino-ui/assets/3333605/43669d4c-1b86-48c4-9c52-b1b74e9b777a)

**Code**
```
MultiSelect<String> select =  MultiSelect.<String>create("Country")
	.appendChild(SelectOption.create("USA", "USA", "America (USA)"))
	.appendChild(SelectOption.create("ARG", "ARG", "Argentina"))
	.appendChild(SelectOption.create("BRA", "BRA", "Brazil"))
	.appendChild(SelectOption.create("DEN", "DEN", "Denmark"))
	.appendChild(SelectOption.create("CRO", "CRO", "Croatia"))
	.appendChild(SelectOption.create("IND", "IND", "India"))
	.appendChild(SelectOption.create("SPA", "SPA", "Spain"))
	.appendChild(SelectOption.create("FRA", "FRA", "France"))
	.appendChild(SelectOption.create("JOR", "JOR", "Jordan"))
	.selectAt(0)
	.addChangeListener(
		(oldValue, newValue) -> {
			Notification.create("Item selected [ " + newValue + " ]")
				.show();
		});

content.appendChild(select);
// select.pauseChangeListeners();
select.selectByValue("BRA", true);
select.selectByValue("IND", true);
```

**Comment by vegegoku** [comment]
I could not reproduce this, it worked for both silent and active change handlers.


https://github.com/DominoKit/domino-ui/assets/5379625/03519954-f23d-40ab-8a6f-688cd264d72b

**Comment by howudodat** [comment]
Here's a video to go with the code.  You'll notice that the value shows USA, Brazil and India selected.  But the dropdown does not.  Also in order to de-select Brazil, I had to do it twice.  sorry the pointer is not visible.  I'll go find another screen recorder tool that shows the pointer and update the video

https://github.com/DominoKit/domino-ui/assets/3333605/a7556b71-27c5-46c3-8ba5-346caba3492a
