### ISSUE TITLE
component visible overlap with SplitPanel's

### ISSUE THREAD

**Issue by jhickman** [DominoKit/domino-ui#871]
When using a SplitPanel in V2, it's possible for the content to be visible when resizing the splitter.   

Below is an example where I have a div with blue background and it is visible when I resize the splitter to be smaller than that component.

![image](https://github.com/DominoKit/domino-ui/assets/861908/174abbca-3ea9-4e4f-b674-71ce4f81c7fc)

![image](https://github.com/DominoKit/domino-ui/assets/861908/05eea8aa-e090-4649-a6f6-f43bdec3f4d1)

Not necessarily a bug, but maybe it would make sense to have some reasonable default for the SplitPanel overflow; be it hidden, auto, etc.    I feel that the components shouldn't, by default, be able to 'bleed' over into the other panes.

**Comment by vegegoku** [comment]
Is there a reproducible for this, I have been trying to reproduce this in the demo app but seems I cant get the same effect.

**Comment by jhickman** [comment]
Was able to do it locally with this bit:

```java
this.div = div()
        .addCss(dui_flex, dui_flex_col)
        .setHeight("100%")
        .appendChild(
            HSplitPanel.create()
                .addCss(dui_flex_1)
                .appendChild(SplitPanel.create()
                    .setWidth("50%")
                    .appendChild(div()
                        .setHeight("100%")
                        .setPadding("50px")
                        .setOverFlow("auto")
                        .appendChild(div()
                            .setBackgroundColor("blue")
                            .setColor("white")
                            .setWidth("200px")
                            .textContent("foo"))
                    )
                )
                .appendChild(SplitPanel.create()
                    .setWidth("50%")
                    .appendChild(div()
                        .setPadding("50px")
                        .textContent("bar"))
                )
        );
```
