### ISSUE TITLE
Use static imports instead of inheriting interfaces for ElementsFactory, SVGFactory and DominoCss

### ISSUE THREAD

**Issue by vegegoku** [DominoKit/domino-ui#884]
Following up with the discussion here https://github.com/DominoKit/domino-ui/discussions/879
We are going to switch to the new static import style instead of implementing the interfaces `ElementsFactory` and `DominoCss`

This means that the components now needs to at least add the following imports statement

```java
import static org.dominokit.domino.ui.utils.Domino.*;
```
Or add individual static imports.

At the same time for any custom component that inherits the interfaces will still function, and anyone who still prefers the old style for their own custom component they can still use the interfaces since they will remain untouched by themselves.

**Comment by jhickman** [comment]
If you're like me and don't like star imports, you may have intellij configured to automatically expand out the star imports.   

However, there are certain ones that I prefer to stay as star imports such as
- org.mockito.Mockito.*
- org.junit.jupiter.api.Assertions.*

You can add org.dominokit.domino.ui.utils.Domino to your star import whitelist in Intellij.    This way, when you 'organize imports' it won't expand out and you lose access to the other methods available in the Domino class.
This is under Settings > Editor > Code Style > Java > Imports

![image](https://github.com/DominoKit/domino-ui/assets/861908/143c3b2d-a82a-4d94-a1c4-70e2f7d60a68)
