### ISSUE TITLE
Select component improvements

### ISSUE THREAD

**Issue by jhickman** [DominoKit/domino-ui#886]
Not necessarily a bug; maybe some improvements on UX for Select components

This is all for Domino V2

* General Select
  * Selects do not open dropdown by keyboard interactions
    * it looks like the 'searchable' Select will open when hitting enter, but I cannot figure out how to open up the dropdown for normal Selects
  * When the dropdown is open, typing doesn't navigate selection to anything.   
    * Typically, with selects, you can type and it'll navigate to the item that starts with the characters typed.
  * Normally with selects, you _should_ be able to type without the dropdown being open and it'll select the item that starts with what you have typed
* Searchable Select
  * when typing in a search, it might be nice for the 'selection' to be the top such that hitting enter will select that item
    * Right now, at least on the demo page, when typing "denmark", by "de" it has already narrowed down to the single item, but hitting enter doesn't do anything (as a user may expect)
    * Also, the "create" option appears first (in the demos) so that you have to arrow down _through_ that one before you get to the one you were searching for.
    * It appears that when you arrow down through the 'create' item to the list, there's no way of getting back up to the 'create' option without using the mouse.

**Comment by vegegoku** [comment]
This was a very interesting and valuable feedback on select, thank you.
Everything from this feedback have been implemented with one single note 

> it looks like the 'searchable' Select will open when hitting enter, but I cannot figure out how to open up the drop-down for normal Selects

Both normal and searchable selects open the menu when you press enter, this was confirmed in the website demo sample, but I still added the arrow down interaction, so pressing enter or arrow down both will open the menu.
