### ISSUE TITLE
Dependency to gwt-time-emul and break the project compilation in Eclipse

### ISSUE THREAD

**Issue by foal** [DominoKit/domino-ui#894]
**Describe the bug**
After update from 2.0.0-RC4 to HEAD-SHAPSHOT I see multiple errors "The package java.time is accessible from more than one module: <unnamed>, java.base"

**To Reproduce**
1. Use `java.time.*` objects inside GWT code
2. Update Domino UI to the latest SNAPSHOT

**Expected behavior**
No error from Java compiler

**Screenshots**
![image](https://github.com/DominoKit/domino-ui/assets/458209/ef348e8d-a558-440d-90f3-f3673b90041a)

**Additional context**
Workaround:
Add exclude of  `gwt-time-emul` to `domino-ui`
```xml
<dependency>                                     
	<groupId>org.dominokit</groupId>             
	<artifactId>domino-ui</artifactId>           
	<exclusions>                                 
		<exclusion>                              
			<groupId>org.dominokit</groupId>     
			<artifactId>gwt-time-emul</artifactId
		</exclusion>                             
	</exclusions>                                
</dependency>              
 ```
And add dummy `Time.gwt.xml` to the GWT project

**Comment by vegegoku** [comment]
The exclusion will be needed anyway if you have your own time emul, but we will follow the new emulation approach to fix this issue, thank you for reporting

**Comment by vegegoku** [comment]
I pushed an update, the time emul dependency or the java.time.Time are no longer needed.
