### ISSUE TITLE
Wrong (?) modal windows position on open

### ISSUE THREAD

**Issue by foal** [DominoKit/domino-ui#895]
**Describe the bug**
After update from 2.0.0-RC4 to SNAPSHOT the modal window has wrong horizontal position - too right. 

The modal window using as a standalone component in the plain GWT application

```
public class PhotoViewerPopup extends Window {

	public PhotoViewerPopup() {
		super("");
		setModal(true);
		setDraggable(false);
		setStretchWidth(DialogSize.VERY_LARGE);
		setStretchHeight(DialogSize.VERY_LARGE);
		setFixed();
		hideResizing();
		loader = Loader.create(getAppendTarget(), LoaderEffect.BOUNCE).setLoadingText("Loading...");
	}

	public void open(FormSubmissionInfo fsp) {
		loader.start();
                //To "fix" issue uncomment line below
               // setWindowLeft((DomGlobal.window.innerWidth - modalElement.element().getBoundingClientRect().width) / 2).setFixed();
		open();
                //Load data..... 
	}
}
```
**Expected behavior**
Windows shows on the center of viewport

**Screenshots**
Wrong:
![image](https://github.com/DominoKit/domino-ui/assets/458209/cbee2c02-c339-4c58-a81e-83802fcbb46c)

Correct:
![image](https://github.com/DominoKit/domino-ui/assets/458209/76202f61-2795-417b-9894-a5624361e655)

**Workaround**
Add `setWindowLeft((DomGlobal.window.innerWidth - modalElement.element().getBoundingClientRect().width) / 2).setFixed();` into `open` method

**Comment by vegegoku** [comment]
I am not able to reproduce this bug, my guess this is caused by the content, it seems the content is stretching the window after it is positioned.

**Comment by foal** [comment]
It is hardly to reproduce on clean application. All what I know is a fact that on 2.0.0-RC4 it works correct and on current SN it required the provided workaround. 

I think it is a specific issue of my application. I have reported this issue to point you on "possible" bug in the new code have added after 2.0.0-RC4 release.
