### ISSUE TITLE
When click outside a modal the modal gets dismissed

### ISSUE THREAD

**Issue by mahmoudzamel** [DominoKit/domino-ui#91]
Differently from an expected modal behavior; a modal gets dismissed when clicking outside the modal area. Can we oblige a modal to only be dismissed from an action button within the modal?

**Comment by vegegoku** [comment]
Set auto close to false

**Comment by mahmoudzamel** [comment]
Yup!

**Comment by vegegoku** [comment]
Notice that you can define a close handler for the modal dialog and this close handler will be triggered whether auto close is on or off, so normally auto close will act as if the user clicked the cancel or close button.
