### ISSUE TITLE
SelectionPlugin: MultiSelectHeader checkbox should get unchecked if not all table entries are checked

### ISSUE THREAD

**Issue by bschmelcher** [DominoKit/domino-ui#910]
**Describe the bug**
If the MultiSelectHeader checkbox of the SelectionPlugin is checked, currently it is staying checked even when no table rows are checked after a change.
This is observable using LocalListDataStore.setData (where the table data is refreshed and table rows are re-added unchecked), and also using pagination where the selected rows get unchecked when changing pages.

**To Reproduce**
1. Go to https://dominokit.com/domino-ui/demo/v1/datatable/mix-plugins or https://dominokit.com/domino-ui/demo/v2/datatable/mix-plugins
2. Click the "Select all" Checkbox in the header
3. Switch to another page of pagination
4. See error, no table entries are checked but the header checkbox is still checked.

**Expected behavior**
Header "Select all" checkbox should not be checked if not all table rows are checked

**Screenshots**
Before changing page:
![image](https://github.com/DominoKit/domino-ui/assets/102970139/ab301f99-ae64-47b9-a5a1-74501bc54c0d)
After changing page:
![image](https://github.com/DominoKit/domino-ui/assets/102970139/14f5131a-ae1f-401f-b991-e25abc94c1f2)

**Additional context**
If the Header Checkbox would be somehow accessible, it could be unchecked manually but it is directly appended as a HTMLElement in the SelectionPlugin, and controlled via a changeHandler and a datatable-SelectionListener (V1, haven't checked V2 yet).

**Comment by howudodat** [comment]
looks like the recent changes to SelectionPlugin created a bug.  if multiselect is true, it works fine.  if multiselect is false, then SelectionPlugin#updateHeaderCheckBox() crashes on lines 330 and 332 because headerCheckBox is null
