### ISSUE TITLE
domino-ui demo(v2), "form-sample" & "login-sample" can't open

### ISSUE THREAD

**Issue by raindroplvy** [DominoKit/domino-ui#930]
The domino-ui demo(v2) can‘t open the following samples:

https://dominokit.com/domino-ui/demo/v2/forms/form-sample
https://dominokit.com/domino-ui/demo/v2/forms/login-sample

**Comment by FrankHossfeld** [comment]
Looks like this issues are related to: https://github.com/DominoKit/domino-ui-demo and should be added there.

**Comment by vegegoku** [comment]
We removed booth samples, they are old from early versions and required some maintainability as we are moving, and there are more better samples and so we wont keep those.
