### ISSUE TITLE
overflow tabs support

### ISSUE THREAD

**Issue by raindroplvy** [DominoKit/domino-ui#931]
Is there a plan to support overflow tabs like this:
![1715417278340](https://github.com/DominoKit/domino-ui/assets/5383383/4b94f8ac-189a-48f8-b8a4-3a5631bf170b)

**Comment by raindroplvy** [comment]
Who can give some advice?

**Comment by vegegoku** [comment]
Yes we doing to support it eventually.

**Comment by FrankHossfeld** [comment]
@vegegoku do you think, this will also work for vertical tabs?

**Comment by vegegoku** [comment]
> @vegegoku do you think, this will also work for vertical tabs?

It will
