### ISSUE TITLE
Select loses focus after selection

### ISSUE THREAD

**Issue by doctorj** [DominoKit/domino-ui#937]
After value is selected, element doesn't have focus anymore. It happens when value is selected with keyboard (enter) and also when value is selected with mouse.

Here is an example from domino-ui demo where pressing tab after selecting passes focus to first element at the top.

https://github.com/DominoKit/domino-ui/assets/360289/68eb3a10-3f8b-4d74-a7d7-cad18b51fbb8

**Comment by FrankHossfeld** [comment]
Yep, have seen that also. Makes working with forms much more difficult.

**Comment by doctorj** [comment]
@FrankHossfeld 

I compared AbstractSelect and AbstractSuggestBox and noticed that there is close listener (which is missing in AbstractSelect) for SuggestBox options menu added, like this
```
.addCloseListener(component -> focus())

```
So, you can just try something like this for yours Selects and it should work:
```
yourSelect.getOptionsMenu().addCloseListener(component -> yourSelect.focus());
```
