### ISSUE TITLE
V2 Expose SuggestBox loader icon

### ISSUE THREAD

**Issue by howudodat** [DominoKit/domino-ui#941]
I would like to hide the loader icon in the SuggestBox so that the text field consumes more space.
As an alternative, the loader icon could cover the delete icon
![image](https://github.com/DominoKit/domino-ui/assets/3333605/e11b554f-f2f2-42f0-bdb8-1c3c4405b1d2)

Peter

**Comment by vegegoku** [comment]
fixed in https://github.com/DominoKit/domino-ui/issues/935
