### ISSUE TITLE
DominoUIConfig for different "parts" of the application

### ISSUE THREAD

**Issue by schube** [DominoKit/domino-ui#943]
**Is your feature request related to a problem? Please describe.**
I am setting `getTableTextHeaderFilterSearchDelay` with 

		 DominoUIConfig.CONFIG.setUIConfig(new UIConfig() {
	            
	            @Override
	            public int getTableTextHeaderFilterSearchDelay() {
                    return 500;
                
	            }
	        });

which is fine for my remote data store, because I do not want to trigger a search for each letter typed.

But the same application has also a local data store, where I do NOT want that delay. I would rather like an instant search in that case. 

Currently, there is no way to provide different configurations, since the config is global.

(Maybe I miss something?)

**Describe the solution you'd like**
I think a GLOBAL configuration is not that good, see scenario described above. 
I would like to create multiple instances of DominoUIConfig and pass that to my components (such as Datatable)

**Additional context**
DominoUI 2.0

Thank you!

**Comment by vegegoku** [comment]
now you can use `setOwnConfig` on a delayed header filter, this kind of configuration will be added to other components per request.

**Comment by schube** [comment]
Thank you!
