### ISSUE TITLE
Select inner divs overlap outer divs height

### ISSUE THREAD

**Issue by bschmelcher** [DominoKit/domino-ui#945]
**Describe the bug**
Using domino-ui version 1.0.6, the inner divs of Selects overlap the outer div in height, because no height:100% is set for the inner divs.
For the div with class **field-cntr** inside the select-div, a fixed height is set by domino-ui-components.css
For the divs inside the **field-cntr** div, no height is set. So the inner divs(**flex-layout** and **field-input-cntr**) can overlap the outer div.
The issue is getting worse when the line-height property of **flex-layout** is being changed.

This issue can be observed without any DOM/CSS modifications with the newest Chrome-Version (126.0.6478.115). It's also present in domino-ui-demo. I'm not exactly sure why this occured now with the Chromium-Update, but changing the line-height of the table in Firefox also will lead to the same issue.

**To Reproduce**
1. Go to https://dominokit.com/domino-ui/demo/v1/datatable/mix-plugins
2. See the Filter Selects at the top of the table

**Expected behavior**
Inner divs should not overlap outer divs in Select

**Screenshots**
![image](https://github.com/DominoKit/domino-ui/assets/102970139/77c58ce1-4b68-4b1a-9d75-5d184bd10f6d)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 126.0.6478.115

**Additional context**
Setting the height of the **flex-layout** and **field-input-cntr** divs of the select to 100% fixes this.

**Comment by MarkusAchenbach** [comment]
HI,
will there be a backport to v1.x.x ? (would be highly appreciated)

**Comment by FrankHossfeld** [comment]
HI Markus,
it looks like the changes are made in the 1.0.0-development branch. So, no action required.
cu Frank
