### ISSUE TITLE
DateBox should close the popup when cleared and call change listeners when value is null

### ISSUE THREAD

**Issue by howudodat** [DominoKit/domino-ui#954]
Create a way to clear a datebox

DateBox.clear() doesn't close the calendar popup
DateBox.setData(null) doesn't call any of the change handlers

As a user I should be able to clear a date selection...

```
public class NowDateBox extends DateBox {

	public static NowDateBox create() {
		return new NowDateBox();
	}

	public static NowDateBox create(String label) {
		return new NowDateBox(label, new Date(), new CalendarInitConfig());
	}

	public NowDateBox() {
		super();
		addNow();
	}

	public NowDateBox(String label) {
		super(label);
		addNow();
	}

	public NowDateBox(String label, Date date, CalendarInitConfig calendarInitConfig) {
		super(label, date, calendarInitConfig);
		addNow();
	}

	protected void addNow() {
		this.withCalendar((db, cal) -> cal.withFooter((calendar, footer) -> footer.addCss(dui_flex, dui_justify_center)
			.appendChild(Button.create(Icons.calendar_today(), "TODAY")
				.addClickListener(evt -> calendar.setDate(new Date())))
			.appendChild(Button.create(Icons.calendar_today(), "CLEAR")
				.addClickListener(evt -> 
				{
					clear();
				})))

		);
	}


```

**Comment by howudodat** [comment]
ok, scratch most of that, I was forgetting that I could call setValue on the DateBox to clear it out.  However setDate(null) is still an issue.  Here is working code for the Clear button:

```
	protected void addNow() {
		this.withCalendar((db, cal) -> cal.withFooter((calendar, footer) -> footer.addCss(dui_flex, dui_justify_center)
			.appendChild(Button.create(Icons.calendar_today(), "TODAY")
				.addClickListener(evt -> calendar.setDate(new Date())))
			.appendChild(Button.create(Icons.calendar_today(), "CLEAR")
				.addClickListener(evt -> 
				{
					cal.hide();
					setValue(null);
				})))

		);
	}
```

**Comment by vegegoku** [comment]
We dont have a `setDate(...)` function for the DateBox and there is no `setValue(..)` for the calendar, the DateBox is a form field and uses the setValue, I fixed so it now clears and call change listeners when the value is null and will also close the calendar popup. as for the calendar it will always have a Date and by default clearing the calendar will set it to the specified default date.

so now you can just call clear or setValue null on the DateBox.
