### ISSUE TITLE
Migration from java.util.Date to java.time .* API

### ISSUE THREAD

**Issue by loic-leprieur** [DominoKit/domino-ui#958]
**Is your feature request related to a problem? Please describe.**

The old API java.util.Date is always frustrating to work with. In order to work properly a lot of wacky code had to be added to my projects. If only java.time was available in Domino-UI it would be a huge improvement in our code base and avoid shooting ourself in the foot when timezones or calculation on dates are used. 

**Describe the solution you'd like**

I am currently stuck before breaking changes 2.0 version because in order to migrate a gigantic amount of code would have to be rewritten from nearly zero. So if v2.0 and later already supports java.time then I'll just be a bit upset but at least I would know migrating will be even more necessary at some point.  

**Describe alternatives you've considered**

Plan for a migration sprint.

**Comment by FrankHossfeld** [comment]
I agree, but ... this problem is more related to GWT as to domino-ui. domino-ui is based on GWT and GWT uses the old Date API.  Maybe start a discussion here:  https://matrix.to/#/#gwtproject_gwt:gitter.im
