### ISSUE TITLE
Add Multi Selection for Tree Component

### ISSUE THREAD

**Issue by Ri-gers** [DominoKit/domino-ui#982]
It would be great to have a Tree variant where multiple items could be selected instead of a single one. For example you could check a checkbox next to a (root) node and then all children would be selected. Parent nodes could have a state like selected/not selected/indeterminate (somewhat similar to the Trees here: https://dominokit.com/solutions/domino-ui/v2/docs/data-table/tree-eager).
A usecase could be that you configure permissions for users - if you check a root node, a user is allowed to do everything, if only a child is checked in the Tree, they can only perform a subaction etc.

**Comment by vegegoku** [comment]
Initially we intended to add this as enhancement to the existing Tree component, but the existing implementation didn't help in that matter, I had to re-implement most of the component in a way that allow providing different implementations for the Tree component, and it was challenging to keep the original API unchanged.

So based on how much efforts it took to implement the feature itself was added to the pro components, while we have the  base implementation here, this means none pro users will still benefit from this as it allows them to further customize it.

**Comment by Ri-gers** [comment]
> Initially we intended to add this as enhancement to the existing Tree component, but the existing implementation didn't help in that matter, I had to re-implement most of the component in a way that allow providing different implementations for the Tree component, and it was challenging to keep the original API unchanged.
> 
> So based on how much efforts it took to implement the feature itself was added to the pro components, while we have the base implementation here, this means none pro users will still benefit from this as it allows them to further customize it.

Thanks for the info and implementing it so quickly! Any ETA when to expect details for domino-ui-pro?

**Comment by vegegoku** [comment]
> > Initially we intended to add this as enhancement to the existing Tree component, but the existing implementation didn't help in that matter, I had to re-implement most of the component in a way that allow providing different implementations for the Tree component, and it was challenging to keep the original API unchanged.
> > So based on how much efforts it took to implement the feature itself was added to the pro components, while we have the base implementation here, this means none pro users will still benefit from this as it allows them to further customize it.
> 
> Thanks for the info and implementing it so quickly! Any ETA when to expect details for domino-ui-pro?

We are now discussion some of the details about this in the team, and preparing the infrastructure to support it.
